### ISSUE TITLE
Unhandled exception (#a9900c21)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2675] opened 2017-09-01 03:48 UTC
```
sqlmap version: 1.0.12.8#dev
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -u ************************************************ --dbms mysql --dbs --tamper='D:\WorK\广西电网\考试\myp.py'
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2653, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 905, in _setTamperingFunctions
    elif os.path.exists(os.path.join(paths.SQLMAP_TAMPER_PATH, script if script.endswith(".py") else "%s.py" % script)):
  File "Python27/lib/ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 9: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-09-01 12:21
Duplicate of #2348. Please update

**Closed by stamparm** 2017-09-01 12:21 UTC
