### ISSUE TITLE
Unhandled exception (#c54f6953)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2801] opened 2017-11-25 22:40 UTC
```
sqlmap version: 1.1.11.36#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u ********************************************************* --dbs -v 1
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2638, in init
    parseTargetUrl()
  File "lib/core/common.py", line 1427, in parseTargetUrl
    _ = conf.hostname.encode("idna")
  File "Python27/lib/encodings/__init__.py", line 100, in search_function
    level=0)
  File "Python27/lib/encodings/idna.py", line 1
SyntaxError: Non-ASCII character '\x8b' in file Python27/lib/encodings/idna.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by stamparm** [comment] 2017-11-27 09:57
Duplicate of #2800

**Closed by stamparm** 2017-11-27 09:57 UTC
