### ISSUE TITLE
Unhandled exception (#dee263af)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2949] opened 2018-02-26 10:27 UTC
```
sqlmap version: 1.2.2.9#dev
Python version: 2.7.14
Operating system: Windows-7-6.1.7601-SP1
Command line: sqlmap.py -u ****************************************************************************************** --dbs --tamper=between,bluecoat,charencode,charunicodeencode,concat2concatws,equaltolike,greatest,halfversionedmorekeywords,ifnull2ifisnull,modsecurityversioned,modsecurityzeroversioned,multiplespaces,nonrecursivereplacement,percentage,randomcase,securesphere,space2comment,space2hash,space2morehash,space2mysqldash,space2plus,space2randomblank,unionalltounion,unmagicquotes,versionedkeywords,versionedmorekeywords,xforwardedfor
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2636, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 965, in _setTamperingFunctions
    function()
  File "tamper/concat2concatws.py", line 15, in dependencies
    singleTimeWarnMessage("tamper script '%s' is only meant to be run against %s" % (os.path.basename(__file__).split(".")[0], DBMS.MYSQL))
NameError: global name 'os' is not defined
```

**Comment by stamparm** [comment] 2018-02-26 12:38
Duplicate of #2923 (fixed)

**Closed by stamparm** 2018-02-26 12:38 UTC
