### ISSUE TITLE
Unhandled exception (#420a49f0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2816] opened 2017-12-05 09:13 UTC
```
sqlmap version: 1.1.11.25#dev
Python version: 2.7.14
Operating system: posix
Command line: /usr/bin/sqlmap --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 154, in main
    else:
  File "share/sqlmap/lib/controller/controller.py", line 69, in <module>
    from lib.core.target import initTargetEnv
  File "share/sqlmap/lib/core/target.py", line 65, in <module>
    from lib.core.settings import SESSION_SQLITE_FILE
ImportError: cannot import name SESSION_SQLITE_FILE
```

**Comment by stamparm** [comment] 2017-12-05 09:37
Duplicate of #2812 (fixed)

**Closed by stamparm** 2017-12-05 09:37 UTC
