### ISSUE TITLE
Unhandled exception (#6df9a406)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3104] opened 2018-05-16 17:28 UTC
```
Running version: 1.2.3.51#dev
Python version: 2.7.14
Operating system: Linux-3.10.49-perf-g8a25d40-aarch64-with-libc
Command line: sqlmap.py -u *************************************** --dbs
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 536, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 1058, in heuristicCheckSqlInjection
    infoMsg += "be injectable"
  File "lib/controller/checks.py", line 1058, in heuristicCheckSqlInjection
    infoMsg += "be injectable"
  File "usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "usr/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "usr/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "usr/lib/python2.7/pdb.py", line 279, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "usr/lib/python2.7/pdb.py", line 556, in do_ignore
    bpnum = int(args[0].strip())
IndexError: list index out of range
```

**Comment by stamparm** [comment] 2018-05-17 20:55
Duplicate of #3103

**Closed by stamparm** 2018-05-17 20:55 UTC
