### ISSUE TITLE
Unhandled exception (#749b5c87)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3080] opened 2018-05-02 21:10 UTC
```
sqlmap version: 1.1.11.30#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ********************************************************************************************************************************************************************************** --risk=3 --level=5 -D ****** --proxy-file=C:\Users\*************\Desktop\k.txt -T USERagent -C ************************** --dump --no-cast --tamper=between --random-agent
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 655, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 187, in dumpTable
    value = inject.getValue(query, blind=False, time=False, dump=True) or ""
  File "lib/request/inject.py", line 417, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 325, in errorUse
    count = unArrayizeValue(_oneShotErrorUse(countedExpression, countedExpressionFields))
  File "lib/techniques/error/use.py", line 124, in _oneShotErrorUse
    page, headers, _ = Request.queryPage(payload, content=True, raise404=False)
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "Python27/lib/urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "Python27/lib/urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by stamparm** [comment] 2018-05-03 11:15
Duplicate of #2886 (patched)

**Closed by stamparm** 2018-05-03 11:15 UTC
