### ISSUE TITLE
Unhandled exception (#57b755ed)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5818] opened 2024-11-26 09:10 UTC
```
Running version: 1.8.11.9#dev
Python version: 3.7.8
Operating system: Windows-2012ServerR2-6.3.9600-SP0
Command line: sqlmap.py -r ***** -p username --level 3 --risk 3 --tamper=space2comment.py --dbms mysql --dbs --technique E --sql-query=************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************ --hex --threads 1 --proxy=**********************
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 189, in action
    conf.dumper.sqlQuery(query, conf.dbmsHandler.sqlQuery(query))
  File "plugins/generic/custom.py", line 71, in sqlQuery
    output[i] = joinValue(output[i])
  File "lib/core/common.py", line 3722, in joinValue
    retVal = delimiter.join(value)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by stamparm** [comment] 2024-11-27 08:19
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5810

**Closed by stamparm** 2024-11-27 08:19 UTC
