### ISSUE TITLE
Unhandled exception (#4fc7672c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5807] opened 2024-11-16 09:23 UTC
```
Running version: 1.8.11.8#dev
Python version: 3.11.9
Operating system: Linux-6.6.15-amd64-x86_64-with-glibc2.38
Command line: /usr/bin/sqlmap -u ****************************************** -p id --thread 10 --sql-shell
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 222, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/controller/controller.py", line 732, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
  File "/share/sqlmap/plugins/generic/custom.py", line 130, in sqlShell
    output = self.sqlQuery(query)
             ^^^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/plugins/generic/custom.py", line 68, in sqlQuery
    if "SELECT" in sqlType and isListLike(output):
       ^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by stamparm** [comment] 2024-11-16 17:51
Duplicate of #5806

**Closed by stamparm** 2024-11-16 17:51 UTC
