### ISSUE TITLE
Unhandled exception (#8f9c4eef)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4478] opened 2020-12-14 13:17 UTC
```
Running version: 1.4.12.5#dev
Python version: 2.7.18
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=*********************************************************************************** --crawl=1 --threads=10 --retries=0 --timeout=5 --dbms=mysql --technique=EU --random-agent --is-dba --exclude-sysdbs --current-db --forms --batch --answers=**************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1543, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1116, in queryPage
    page, headers, code = Connect.getPage(url=conf.csrfUrl or conf.url, data=conf.data if conf.csrfUrl == conf.url else None, method=conf.csrfMethod or (conf.method if conf.csrfUrl == conf.url else None), cookie=conf.parameters.get(PLACE.COOKIE), direct=True, silent=True, ua=conf.parameters.get(PLACE.USER_AGENT), referer=conf.parameters.get(PLACE.REFERER), host=conf.parameters.get(PLACE.HOST))
  File "lib/request/connect.py", line 872, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 398, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", getUnicode("".join(responseHeaders.headers if responseHeaders else [])), page)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 14: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2020-12-14 14:09
Duplicate of #4465 (fixed)

p.s. https://github.com/sqlmapproject/sqlmap/commit/92054b5d63c726f82733bb6798fc9cc243c29dc8

**Closed by stamparm** 2020-12-14 14:09 UTC
