### ISSUE TITLE
Injections Not Being Saved

### ISSUE THREAD

**Issue by akmlvl** [sqlmapproject/sqlmap#3095] opened 2018-05-12 20:57 UTC
There is a weired problem where injections are not being saved i think sqlmap dosen't save the session sqlite file correctly  everytime it keep scanning again even when it have detected injection points it runs like there is no session each time 
the 1.1.6 version dosen't have this problem it saves the session correctly you should probably look at this problem because it keep hapening many times

**Comment by stamparm** [comment] 2018-05-12 23:08
Unable to reproduce:

1) First run:
![1](https://user-images.githubusercontent.com/921555/39962275-f762b552-5649-11e8-88a9-713f9b74a34b.png)

2) Second run:
![2](https://user-images.githubusercontent.com/921555/39962277-063dcf26-564a-11e8-88d7-e165fac79e8e.png)

**Comment by stamparm** [comment] 2018-05-12 23:35
Basic thing with Issues is that they have to either 1) be reproducible or 2) user provides detailed report of the workflow which led to the "problem". How to proceed in this kind of cases without anything useful to deal with?

**Comment by akmlvl** [comment] 2018-05-12 23:46
dude i will provide you a detailled screenshot and log but i can't at this moment  and  im postivie about the issue try testing from a web request txt file you may be able to reproduce it  dosen't happen 100% of the times and try with --risk=3 --level=3

**Comment by stamparm** [comment] 2018-05-12 23:50
What should be the content of request file: JSON, XML, SOAP, POST-FORM, GET-FORM,....? How many times should I rerun with `--risk=3 --level=3`? Against which target (any)? What are the other switches/options to use? If the percentage is not 100% what is it then? 30%, 40%, 50%?

**Comment by stamparm** [comment] 2018-05-12 23:53
I have just rerun everything for 30 times with `--level=3 --risk=3` with GET-FORM against the same target and everything was fine.

Should I rerun 200 more times? Should I use some other switch/option? Should I switch from GET to POST? Should I try at different time of the day (morning)?

**Comment by akmlvl** [comment] 2018-05-12 23:55
Its a post-form and im only running the risk=3 and level=3 and dbms switch considering the target it happened on mssql and mysql (didn't tried others) and it happens 40% of the times

**Comment by akmlvl** [comment] 2018-05-12 23:58
Oh try at late night you may reproduce it :3 
Bruh just wait for the screenshots and the log

**Comment by akmlvl** [comment] 2018-05-15 10:50
@stamparm 
# First RUN
![firstrun](https://user-images.githubusercontent.com/16985737/40052510-f655422c-5835-11e8-8621-5d8b947809a9.png)
# Second RUN
![secondrun](https://user-images.githubusercontent.com/16985737/40052522-010650b2-5836-11e8-9808-8acdfe19150f.png)
![second](https://user-images.githubusercontent.com/16985737/40052527-03b7400a-5836-11e8-8310-b2fa03059baa.png)

**Comment by stamparm** [comment] 2018-05-15 20:42
How to reproduce?

**Comment by stamparm** [comment] 2018-05-15 20:46
Tested this moment with cookie injection inside a testing environment and couldn't reproduce

**Comment by akmlvl** [comment] 2018-05-15 21:55
well actually i can't tell you exactly you how to reproduce it since it dosen't happen all the time and i said from the begining it's a weired problem bizard 
i will run it with -v 3 switch and give you the results

**Comment by stamparm** [comment] 2018-05-17 21:15
Closing this down as there is a lack of information here to address it properly

**Closed by stamparm** 2018-05-17 21:15 UTC
Labels: support
