### ISSUE TITLE
Unhandled exception (#b0673c42)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3085] opened 2018-05-04 14:04 UTC
```
sqlmap version: 1.1.12#stable
Python version: 2.7.9
Operating system: posix
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 154, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 27, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
    from plugins.dbms.mssqlserver.enumeration import Enumeration
  File "plugins/dbms/mssqlserver/enumeration.py", line 32, in <module>
    from plugins.generic.enumeration import Enumeration as GenericEnumeration
  File "plugins/generic/enumeration.py", line 19, in <module>
    from plugins.generic.databases import Databases
  File "plugins/generic/databases.py", line 35, in <module>
    from lib.core.decorators import stackedmethod
ImportError: cannot import name stackedmethod
```

**Comment by stamparm** [comment] 2018-05-04 14:19
Duplicate of #2812 (fixed)

**Closed by stamparm** 2018-05-04 14:19 UTC
