### ISSUE TITLE
Unhandled exception (#051cd75f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3120] opened 2018-05-26 05:37 UTC
```
sqlmap version: 1.1.11.30#dev
Python version: 2.7.13
Operating system: posix
Command line: ./sqlmap --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 154, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 27, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
    from plugins.dbms.mssqlserver.enumeration import Enumeration
  File "plugins/dbms/mssqlserver/enumeration.py", line 32, in <module>
    from plugins.generic.enumeration import Enumeration as GenericEnumeration
  File "plugins/generic/enumeration.py", line 19, in <module>
    from plugins.generic.databases import Databases
  File "plugins/generic/databases.py", line 35, in <module>
    from lib.core.decorators import stackedmethod
ImportError: cannot import name stackedmethod
```

**Comment by stamparm** [comment] 2018-05-28 08:40
Duplicate of #2812 (fixed)

**Closed by stamparm** 2018-05-28 08:40 UTC
