### ISSUE TITLE
Unhandled exception (#d13d40ef)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2864] opened 2018-01-05 15:20 UTC
```
sqlmap version: 1.0.9.32#dev
Python version: 2.7.9
Operating system: nt
Command line: sqlmap.py -u ***************************************** --dbs
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 100, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 141, in getDbs
    db = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/request/inject.py", line 429, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 593, in bisection
    dataToStdout(filterControlChars(val))
  File "lib/core/common.py", line 896, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-01-06 01:23
Duplicate of #2790

**Closed by stamparm** 2018-01-06 01:23 UTC
