### ISSUE TITLE
Unhandled exception (#b43ab7f8)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1902] opened 2016-05-26 09:31 UTC
```
sqlmap version: 1.0.5.39#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u *********************************************************** --sqlmap
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1369, in checkConnection
    page, headers = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1109, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 681, in getPage
    processResponse(page, responseHeaders)
  File "lib/request/basic.py", line 331, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None)
  File "lib/request/basic.py", line 131, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 41, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 1904, in parseXmlFile
    parse(stream, handler)
  File "Python27/lib/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "Python27/lib/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "Python27/lib/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "Python27/lib/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "Python27/lib/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "lib/parse/handler.py", line 50, in startElement
    self._match = re.search(self._regexp, self._banner, re.I | re.M)
  File "Python27/lib/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "Python27/lib/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "Python27/lib/sre_compile.py", line 572, in compile
    p = sre_parse.parse(p, flags)
  File "Python27/lib/sre_parse.py", line 709, in parse
    source = Tokenizer(str)
  File "Python27/lib/sre_parse.py", line 192, in __init__
    self.__next()
  File "Python27/lib/sre_parse.py", line 198, in __next
    if char[0] == "\\":
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by stamparm** [comment] 2016-05-26 13:35
Duplicate of #1900

**Closed by stamparm** 2016-05-26 13:35 UTC
