### ISSUE TITLE
Unhandled exception (#83754946)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1395] opened 2015-09-08 11:07 UTC
```
sqlmap version: 1.0-dev-nongit-20150908
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ************************************************** None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    init()
  File "lib/core/option.py", line 2494, in init
    _cleanupOptions()
  File "lib/core/option.py", line 1649, in _cleanupOptions
    conf.csvDel = conf.csvDel.decode("string_escape")  # e.g. '\\t' -> '\t'
  File "Python27/lib/encodings/__init__.py", line 100, in search_function
    level=0)
  File "Python27/lib/encodings/string_escape.py", line 1
SyntaxError: Non-ASCII character '\xa3' in file Python27/lib/encodings/string_escape.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by stamparm** [comment] 2015-09-08 12:06
Duplicate of #1344

**Closed by stamparm** 2015-09-08 12:06 UTC
