### ISSUE TITLE
Unhandled exception (#4bf2441f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1126] opened 2015-01-21 16:02 UTC
```
sqlmap version: 1.0-dev-nongit-20150119
Python version: 2.7.2
Operating system: posix
Command line: sdl --disable-col -c /sdcard/romtoolbox/assets/busybox -v 1 --timeout=30 --retries=3 --hpp --threads=1 --text-only --titles --risk=1 --level=1 --technique=BEUSTQ --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/sqlmap.py", line 76, in main
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 2297, in initOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 1935, in _mergeOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/parse/configfile.py", line 72, in configFileParser
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/ConfigParser.py", line 316, in readfp
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/ConfigParser.py", line 471, in _read
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 675, in readline
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 530, in readline
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 477, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 24: invalid start byte
```

**Comment by stamparm** [comment] 2015-01-21 21:14
Duplicate of #1064

**Closed by stamparm** 2015-01-21 21:14 UTC
