### ISSUE TITLE
Unhandled exception (#388485dc)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5251] opened 2022-11-30 17:43 UTC
```
Running version: 1.6.10.4#dev
Python version: 3.10.7
Operating system: Windows-10-10.0.19044-SP0
Command line: sqlmap.py -u ******************************************************************************** --dump-all
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 171, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 493, in dumpAll
    self.getTables()
  File "plugins/dbms/mssqlserver/enumeration.py", line 114, in getTables
    value = [safeSQLIdentificatorNaming(unArrayizeValue(_), True) for _ in value]
  File "plugins/dbms/mssqlserver/enumeration.py", line 114, in <listcomp>
    value = [safeSQLIdentificatorNaming(unArrayizeValue(_), True) for _ in value]
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-12-05 11:49
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5202 (fixed)

**Closed by stamparm** 2022-12-05 11:49 UTC
