### ISSUE TITLE
Unhandled exception (#1cb7278a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2849] opened 2017-12-25 23:18 UTC
```
sqlmap version: 1.0.11.14#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u ************************************************** --columns -T **** -D ***
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 151, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 112, in action
    conf.dumper.dbTableColumns(conf.dbmsHandler.getColumns(), CONTENT_TYPE.COLUMNS)
  File "plugins/generic/databases.py", line 802, in getColumns
    return self.getColumns(onlyColNames=onlyColNames, colTuple=colTuple, bruteForce=True)
  File "plugins/generic/databases.py", line 496, in getColumns
    return columnExists(paths.COMMON_COLUMNS)
  File "lib/techniques/brute/use.py", line 237, in columnExists
    runThreads(conf.threads, columnExistsThread, threadChoice=True)
  File "lib/core/threads.py", line 171, in runThreads
    print
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2017-12-27 10:39
Duplicate of #2790

**Closed by stamparm** 2017-12-27 10:39 UTC
