### ISSUE TITLE
Unhandled exception (#f21be241)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2002] opened 2016-07-02 16:10 UTC
```
sqlmap version: 1.0.6.66#dev
Python version: 2.7.12
Operating system: nt
Command line: C:\Users\трё \Downloads\sqlmapproject-sqlmap-1.0.6-68-gcb43c03\sqlmapproject-sqlmap-cb43c03\sqlmap.Ёє.py -v
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.\xf0\xf3.py", line 118, in main
    cmdLineOptions.update(cmdLineParser().__dict__)
  File "lib/parse/cmdline.py", line 914, in cmdLineParser
    (args, _) = parser.parse_args(argv)
  File "Python27/lib/optparse.py", line 1400, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "Python27/lib/optparse.py", line 1444, in _process_args
    self._process_short_opts(rargs, values)
  File "Python27/lib/optparse.py", line 1538, in _process_short_opts
    self.error(_("%s option requires an argument") % opt)
  File "Python27/lib/optparse.py", line 1583, in error
    self.print_usage(sys.stderr)
  File "Python27/lib/optparse.py", line 1603, in print_usage
    print >>file, self.get_usage()
  File "Python27/lib/optparse.py", line 1589, in get_usage
    self.expand_prog_name(self.usage))
  File "Python27/lib/optparse.py", line 1566, in expand_prog_name
    return s.replace("%prog", self.get_prog_name())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 7: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-02 16:14
Duplicate of #2000 (invalid)

**Closed by stamparm** 2016-07-02 16:14 UTC
