### ISSUE TITLE
Unhandled exception (#7605a8a4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4649] opened 2021-04-23 10:12 UTC
```
Running version: 1.3.10.30#dev
Python version: 3.9.1
Operating system: Windows-2012ServerR2-6.3.9600-SP0
Command line: Sqlmap.py -u **********************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "Sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2688, in init
    loadBoundaries()
  File "lib/parse/payloads.py", line 89, in loadBoundaries
    parseXmlNode(root)
  File "lib/parse/payloads.py", line 44, in parseXmlNode
    for element in node.getiterator("boundary"):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

**Comment by stamparm** [comment] 2021-04-25 18:05
Duplicate of #4126 (fixed)

**Closed by stamparm** 2021-04-25 18:05 UTC
