### ISSUE TITLE
Unhandled exception (#e336f074)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1400] opened 2015-09-09 09:48 UTC
```
sqlmap version: 1.0-dev-nongit-20150824
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ************************************************************ --dump -T ******** -D ************
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 115, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 127, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 182, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 397, in getValue
    value = _goUnion(query, unpack, dump)
  File "lib/request/inject.py", line 323, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 328, in unionUse
    runThreads(numThreads, unionThread)
  File "lib/core/threads.py", line 184, in runThreads
    logger.error("thread %s: %s" % (threading.currentThread().getName(), errMsg))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-22: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2015-09-09 09:49
Duplicate of #1393 (fixed)

**Closed by stamparm** 2015-09-09 09:49 UTC
