### ISSUE TITLE
Unhandled exception (#cc649d4a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2962] opened 2018-03-04 17:27 UTC
```
sqlmap version: 1.1.1.17#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py --random-agent -u ********************************************************************************************************************************************************************************************* --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 151, in main
    start()
  File "lib/controller/controller.py", line 528, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 531, in checkSqlInjection
    page, headers = Request.queryPage(reqPayload, place, content=True, raise404=False)
  File "lib/request/connect.py", line 1156, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 526, in getPage
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 128, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "lib/request/connect.py", line 286, in getPage
    requestMsg += ("%s%s" % (_.path or "/", ("?%s" % _.query) if _.query else "")) if not any((refreshing, crawling)) else url
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 31: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2018-03-05 09:16
Duplicate of #2585 (fixed)

**Closed by stamparm** 2018-03-05 09:16 UTC
