### ISSUE TITLE
Unhandled exception (#a49443f8)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1948] opened 2016-06-12 17:47 UTC
```
sqlmap version: 1.0-dev-nongit-20160612-0b4b
Python version: 2.6.6
Operating system: posix
Command line: sqlmap.py -u **************************************************** --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 101, in main
    init()
  File "lib/core/option.py", line 2567, in init
    _setSocketPreConnect()
  File "lib/core/option.py", line 1067, in _setSocketPreConnect
    thread.start()
  File "usr/lib64/python2.6/threading.py", line 474, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

**Comment by stamparm** [comment] 2016-06-13 12:29
Duplicate of #1925

**Closed by stamparm** 2016-06-13 12:29 UTC
