### ISSUE TITLE
Unhandled exception (#9eb5969c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3777] opened 2019-06-25 14:05 UTC
```
Running version: 1.3.6.50#dev
Python version: 2.7.16
Operating system: Linux-4.19.0-kali5-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py --url=****************************************** --tamper=unicodetobypasswaf.py --data=**************************************************************** --proxy=********************* --ignore-redirects --level=5 --risk=3 --text-only --threads=4 --dbms=mysql --user-agent=Mozilla/5.0 (compatible; Googlebot/2.1; +******************************* --referer=*************************************************************************************************************************** --headers=Content-Type: application/x-www-form-urlencoded --method=POST -H X-Requested-With: XMLHttpRequest --is-dba -v 2 --disable-precon --answers=************** -f --banner --parse-errors --skip-waf
Technique: UNION
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 560, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 1041, in heuristicCheckSqlInjection
    page, _, _ = Request.queryPage(payload, place, content=True, raise404=False)
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 801, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 384, in processResponse
    msg = extractErrorMessage(page)
  File "lib/core/common.py", line 2667, in extractErrorMessage
    if (1.0 * len(re.findall(r"[^A-Za-z,. ]", candidate))) / len(candidate) > MIN_ERROR_PARSING_NON_WRITING_RATIO:
ZeroDivisionError: float division by zero
```

**Comment by stamparm** [comment] 2019-06-26 09:07
Duplicate of #3775 (fixed)

**Closed by stamparm** 2019-06-26 09:07 UTC
