### ISSUE TITLE
Unhandled exception (#030459d1)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4215] opened 2020-05-24 21:14 UTC
```
Running version: 1.4.5#stable
Python version: 2.7.18
Operating system: Linux-3.18.91-14404620-QB20334066-aarch64-with-debian-kali-rolling
Command line: sqlmap.py ****************************************************** --dbs --batch --dbms=MYSQL --ignore-proxy --random-agent --tamper=space2comment bluecoat --drop-set-cookie --level 5 --risk 3 --tamper=overlongutf8 --hex --data -a
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 166, in main
    init()
  File "lib/core/option.py", line 2687, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 736, in _setTamperingFunctions
    script = safeFilepathEncode(script.strip())
  File "lib/core/common.py", line 2010, in safeFilepathEncode
    retVal = getBytes(filepath, sys.getfilesystemencoding() or UNICODE_ENCODING)
  File "lib/core/convert.py", line 259, in getBytes
    retVal = value.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 12: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2020-05-27 13:38
Duplicate of #4214

**Closed by stamparm** 2020-05-27 13:38 UTC
