### ISSUE TITLE
Unhandled exception (#856e4f79)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4009] opened 2019-11-13 07:27 UTC
```
Running version: 1.3.11.36#dev
Python version: 2.7.15+
Operating system: Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
Command line: sqlmap.py -u ***************************** --forms
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 163, in main
    init()
  File "lib/core/option.py", line 2659, in init
    _findPageForms()
  File "lib/core/option.py", line 437, in _findPageForms
    if findPageForms(page, conf.url, True, True):
  File "lib/core/common.py", line 4502, in findPageForms
    elif not re.sub(r"(%s)=[^&]*&?" % '|'.join(IGNORE_PARAMETERS), "", data):
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2019-11-13 09:55
Duplicate of #4008

**Closed by stamparm** 2019-11-13 09:55 UTC
