### ISSUE TITLE
Unhandled exception (#24f69148)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1368] opened 2015-08-29 06:21 UTC
```
sqlmap version: 1.0-dev-1f5e660
Python version: 2.6.6
Operating system: posix
Command line: sqlmap.py -u ******************************************* --random-agent --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 109, in main
    start()
  File "lib/controller/controller.py", line 394, in start
    checkStability()
  File "lib/controller/checks.py", line 1094, in checkStability
    checkDynamicContent(firstPage, secondPage)
  File "lib/controller/checks.py", line 986, in checkDynamicContent
    while not Request.queryPage():
  File "lib/request/connect.py", line 1100, in queryPage
    return comparison(page, headers, code, getRatioValue, pageLength)
  File "lib/request/comparison.py", line 31, in comparison
    _ = _adjust(_comparison(page, headers, code, getRatioValue, pageLength), getRatioValue)
  File "lib/request/comparison.py", line 85, in _comparison
    page = removeDynamicContent(page)
  File "lib/core/common.py", line 2607, in removeDynamicContent
    page = re.sub(r'(?s)%s.+%s' % (re.escape(prefix), re.escape(suffix)), '%s%s' % (prefix, suffix), page)
  File "usr/lib64/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
  File "usr/lib64/python2.6/re.py", line 273, in _subx
    template = _compile_repl(template, pattern)
  File "usr/lib64/python2.6/re.py", line 260, in _compile_repl
    raise error, v # invalid expression
error: bogus escape (end of line)
```

**Comment by stamparm** [comment] 2015-08-29 23:38
duplicate of #1367

**Closed by stamparm** 2015-08-29 23:38 UTC
Labels: duplicate
