### ISSUE TITLE
Unhandled exception (#e159330a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2586] opened 2017-06-18 08:33 UTC
```
sqlmap version: 1.1.4.39#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py **** http://www.entomopix.eu/orders.php?id= --level 5 --risk 3 tamper=between,bluecoat,charencode,charunicodeencode,concat2concatws,equaltolike,greatest,halfversionedmorekeywords,ifnull2ifisnull,modsecurityversioned,modsecurityzeroversioned,multiplespaces,nonrecursivereplacement,percentage,randomcase,securesphere,space2comment,space2hash,space2morehash,space2mysqldash,space2plus,space2randomblank,unionalltounion,unmagicquotes,versionedkeywords,versionedmorekeywords,xforwardedfor --dbms=mssql
Technique: None
Back-end DBMS: Microsoft SQL ****** (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in main
    init()
  File "lib/core/option.py", line 2606, in init
    ****************
  File "lib/core/common.py", line 1453, in **************
    conf.httpHeaders = filter(lambda key, value: key != HTTP_HEADER.HOST, conf.httpHeaders)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by stamparm** [comment] 2017-06-18 11:06
Duplicate of #2491 (fixed)

**Closed by stamparm** 2017-06-18 11:06 UTC
