### ISSUE TITLE
Unhandled exception (#539d9f9f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3999] opened 2019-11-06 14:14 UTC
```
Running version: 1.3.8.4#dev
Python version: 2.7.16
Operating system: Windows-10-10.0.18362
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    conf.showTime = True
  File "lib/core/option.py", line 2664, in init
    loadPayloads()
  File "lib/core/update.py", line 117, in update
    finally:
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by stamparm** [comment] 2019-11-06 23:04
Duplicate of #3898 (patched)

**Closed by stamparm** 2019-11-06 23:04 UTC
