### ISSUE TITLE
Unhandled exception (#dd57699e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4005] opened 2019-11-08 20:14 UTC
```
Running version: 1.3.11#stable
Python version: 3.7.4
Operating system: Darwin-18.7.0-x86_64-i386-64bit
Command line: /usr/local/bin/sqlmap -d ************************************************ --os-shell
Technique: DIRECT
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "/Cellar/sqlmap/1.3.11/libexec/plugins/generic/takeover.py", line 85, in osShell
    self.initEnv(web=web)
  File "/Cellar/sqlmap/1.3.11/libexec/lib/takeover/abstraction.py", line 223, in initEnv
    raise SqlmapFilePathException(msg)
lib.core.exception.SqlmapFilePathException: unable to mount the operating system takeover

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap", line 180, in main
    start()
  File "/Cellar/sqlmap/1.3.11/libexec/lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "/Cellar/sqlmap/1.3.11/libexec/lib/controller/controller.py", line 283, in start
    action()
  File "/Cellar/sqlmap/1.3.11/libexec/lib/controller/action.py", line 216, in action
    conf.dbmsHandler.osShell()
  File "/Cellar/sqlmap/1.3.11/libexec/plugins/generic/takeover.py", line 94, in osShell
    self.initEnv(web=web)
  File "/Cellar/sqlmap/1.3.11/libexec/lib/takeover/abstraction.py", line 200, in initEnv
    self.webInit()
  File "/Cellar/sqlmap/1.3.11/libexec/lib/takeover/web.py", line 182, in webInit
    if conf.url.endswith(ext):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by stamparm** [comment] 2019-11-08 21:41
Duplicate of #4004 (fixed)

**Closed by stamparm** 2019-11-08 21:41 UTC
