### ISSUE TITLE
bug!?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2920] opened 2018-02-09 03:39 UTC
[11:38:19] [INFO] testing connection to the target URL
/data/data/com.termux/files/usr/lib/python2.7/cookielib.py:1591: UserWarning: cookielib bug!
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/cookielib.py", line 1589, in make_cookies
    split_header_words(rfc2965_hdrs), request)
  File "/data/data/com.termux/files/usr/lib/python2.7/cookielib.py", line 1555, in _cookies_from_attrs_set
    cookie = self._cookie_from_cookie_tuple(tup, request)
  File "/data/data/com.termux/files/usr/lib/python2.7/cookielib.py", line 1548, in _cookie_from_cookie_tuple
    rest)
  File "/data/data/com.termux/files/usr/lib/python2.7/cookielib.py", line 755, in __init__
    if expires is not None: expires = int(expires)
ValueError: invalid literal for int() with base 10: 'Thu'

  _warn_unhandled_exception()

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment] 2018-02-09 17:21
I am unable to reproduce this. `cookielib` automatically discards invalid `Expires` attributes, hence I am not sure how that `Thu` managed to get through.

Can you either:
1) send me an URL (privately)
or
2) run sqlmap with -v 6 and copy paste a value for `Set-Cookie` that you see inside the responses (where that `Thu` or similar appears)

**Comment by stamparm** [comment] 2018-02-13 13:40
Closing because of not receiving any feedback

**Closed by stamparm** 2018-02-13 13:40 UTC
