### ISSUE TITLE
Unhandled exception (#e7768199)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5200] opened 2022-10-16 09:35 UTC
```
Running version: 1.6.10.4#dev
Python version: 2.7.17
Operating system: Linux-4.15.0-189-generic-x86_64-with-Ubuntu-18.04-bionic
Command line: sqlmap.py --tor-type SOCKS5 -u ************************************************************************************************************************************ --search -C **** --schema --exclude-sysdbs flu,bat,tec=E --output-dir=dumpasli --headers=************************************* --headers=User-Agent: Mozilla/5.0 (Manifest; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 131, in action
    conf.dumper.dbTableColumns(conf.dbmsHandler.getSchema(), CONTENT_TYPE.SCHEMA)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "plugins/generic/databases.py", line 948, in getSchema
    self.getTables()
  File "plugins/dbms/mssqlserver/enumeration.py", line 114, in getTables
    value = [safeSQLIdentificatorNaming(unArrayizeValue(_), True) for _ in value]
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-10-17 09:36
Duplicate of #5202 (fixed)

**Closed by stamparm** 2022-10-17 09:36 UTC
