### ISSUE TITLE
Unhandled exception (#8f025274)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1890] opened 2016-05-24 10:30 UTC
```
sqlmap version: 1.0.5.39#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -r 8.txt --dbms=mysql --dbs --tamper=space2comment --random-agent
Technique: UNION
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 487, in start
    check = checkDynParam(place, parameter, value)
  File "lib/controller/checks.py", line 983, in checkDynParam
    payload = agent.payload(place, parameter, value, getUnicode(randInt))
  File "lib/core/agent.py", line 105, in payload
    origValue = re.search(r"\w+\Z", origValue.split(BOUNDED_INJECTION_MARKER)[0]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by stamparm** [comment] 2016-05-24 10:31
Duplicate of #1889

**Closed by stamparm** 2016-05-24 10:31 UTC
