### ISSUE TITLE
Unhandled exception (#56657cc4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1885] opened 2016-05-21 13:29 UTC
```
sqlmap version: 1.0.4.21#dev
Python version: 2.7.5
Operating system: posix
Command line: /usr/local/bin/sqlmap -u *************************************
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 105, in main
    init()
  File "share/sqlmap/lib/core/option.py", line 2582, in init
    _setSocketPreConnect()
  File "share/sqlmap/lib/core/option.py", line 1067, in _setSocketPreConnect
    thread.start()
  File "lib64/python2.7/threading.py", line 746, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

**Comment by stamparm** [comment] 2016-05-22 16:00
Duplicate of #1865 (please update)

**Closed by stamparm** 2016-05-22 16:00 UTC
