### ISSUE TITLE
Unhandled exception (#b0659e2f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4512] opened 2021-01-05 12:46 UTC
```
Running version: 1.5.1.7#dev
Python version: 2.7.18
Operating system: Linux-5.4.0-kali3-amd64-x86_64-with-debian-kali-rolling
Command line: /usr/bin/sqlmap -u **********************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 216, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "/share/sqlmap/lib/controller/checks.py", line 1544, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/connect.py", line 1423, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/share/sqlmap/lib/request/connect.py", line 882, in getPage
    processResponse(page, responseHeaders, code, status)
  File "/share/sqlmap/lib/request/basic.py", line 384, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None, status)
  File "/share/sqlmap/lib/request/basic.py", line 151, in parseResponse
    headersParser(headers)
  File "/share/sqlmap/lib/parse/headers.py", line 37, in headersParser
    parseXmlFile(xmlfile, handler)
  File "/share/sqlmap/lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/lib/python2.7/xml/sax/expatreader.py", line 336, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/share/sqlmap/lib/parse/handler.py", line 65, in startElement
    if self._dbmsVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-01-05 13:51
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-01-05 13:51 UTC
