### ISSUE TITLE
Unhandled exception (#2ac5e6d0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2507] opened 2017-04-27 15:15 UTC
```
sqlmap version: 1.1.1.5#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ************************************************************* --tamper=sÔce2comment
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2662, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 905, in _setTamperingFunctions
    elif os.path.exists(os.path.join(paths.SQLMAP_TAMPER_PATH, script if script.endswith(".py") else "%s.py" % script)):
  File "lib/ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-04-30 06:34
Duplicate of #2348. Please update

**Closed by stamparm** 2017-04-30 06:34 UTC
