### ISSUE TITLE
Unhandled exception (#18a5e21e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1494] opened 2015-10-27 21:14 UTC
```
sqlmap version: 1.0-dev-nongit-20150721
Python version: 2.7.10
Operating system: posix
Command line: sqlmap.py -u *********************************************************************************************** --current-db
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1310, in checkConnection
    page, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1054, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 436, in getPage
    conn = urllib2.urlopen(req)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 485, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 321, in readheaders
    raise LineTooLong("header line")
LineTooLong: got more than 65536 bytes when reading header line
```

**Comment by stamparm** [comment] 2015-10-28 09:14
Duplicate of #1315 (fixed)

**Closed by stamparm** 2015-10-28 09:14 UTC
