### ISSUE TITLE
Unhandled exception (#1acc4e77)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2873] opened 2018-01-10 09:53 UTC
```
sqlmap version: 1.1.11.19#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u **************************************** --dump-all
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 655, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 471, in dumpAll
    self.dumpTable()
  File "plugins/generic/entries.py", line 71, in dumpTable
    if  ',' in conf.db:
TypeError: argument of type 'bool' is not iterable
```

**Comment by stamparm** [comment] 2018-01-10 14:52
Duplicate of #2786 (fixed)

**Closed by stamparm** 2018-01-10 14:52 UTC
