### ISSUE TITLE
Unhandled exception (#bb0df878)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1789] opened 2016-03-31 17:15 UTC
```
sqlmap version: 1.0-dev-nongit-20160226-0b4b
Python version: 2.7.3
Operating system: nt
Command line: sqlmap.py -r 1212.txt --tamper=between.py --tables --hex --threads 10 --technique=B --tamper between.py --dbms Oracle --columns
Technique: BOOLEAN
Back-end DBMS: Oracle (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 111, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 109, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "lib/core/dump.py", line 239, in dbTables
    self._write("Database: %s" % unsafeSQLIdentificatorNaming(db) if db else "Current database")
  File "lib/core/dump.py", line 70, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 835, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "thirdparty/colorama/ansitowin32.py", line 34, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 115, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 142, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 147, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2016-03-31 18:15
Duplicate of #1784. Please update

**Closed by stamparm** 2016-03-31 18:15 UTC
