### ISSUE TITLE
ValueError: database parameter must be string or APSW Connection object

### ISSUE THREAD

**Issue by senthilvit** [sqlmapproject/sqlmap#2475] opened 2017-04-11 13:25 UTC
## What's the problem (or question)?
receiving this error with any URL. I have downloaded the latest repo from GIT still the same behavior

sqlmap version: 1.1.4.13#dev
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -u ************************************************************************ None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 135, in main
    setRestAPILog()
  File "lib/utils/api.py", line 288, in setRestAPILog
    conf.databaseCursor.connect("client")
  File "lib/utils/api.py", line 73, in connect
    self.connection = sqlite3.connect(self.database, timeout=3, isolation_level=None)
ValueError: database parameter must be string or APSW Connection object

## Do you have an idea for a solution?
NO

## What are the running context details?

* Installation method - downloaded ZIP from sqlmap.org website
* Client OS - Windows 7
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
1.1.4.13#dev

* Target DBMS: Oracle

* Relevant console output (if any):
sqlmap version: 1.1.4.13#dev
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -u ************************************************************************ None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 135, in main
    setRestAPILog()
  File "lib/utils/api.py", line 288, in setRestAPILog
    conf.databaseCursor.connect("client")
  File "lib/utils/api.py", line 73, in connect
    self.connection = sqlite3.connect(self.database, timeout=3, isolation_level=None)
ValueError: database parameter must be string or APSW Connection object

* Exception traceback (if any):

**Comment by stamparm** [comment] 2017-04-11 16:04
Duplicate of #2471 (fixed)

**Closed** 2017-04-11 16:04 UTC
Labels: duplicate
