### ISSUE TITLE
Unhandled exception (#9c475790)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4711] opened 2021-06-15 06:14 UTC
```
Running version: 1.5.6.2#dev
Python version: 3.7.0
Operating system: Windows-10-10.0.19041-SP0
Command line: sqlmap.py -u **************************************************************************************************************************************** --auth-type=***** --auth-cred=******************* --batch --risk=3 --level=5 --random-agent -b --tamper=space2comment --dbms=mysql --tables --ignore-code=401
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 591, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 534, in checkSqlInjection
    falseResult = Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1450, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 629, in getPage
    responseHeaders[URI_HTTP_HEADER] = conn.geturl()
AttributeError: '_' object has no attribute 'geturl'
```

**Comment by stamparm** [comment] 2021-06-15 19:05
Duplicate of #4712 (fixed)

**Closed by stamparm** 2021-06-15 19:05 UTC
