### ISSUE TITLE
Unhandled exception (#6728abb0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5209] opened 2022-10-24 01:42 UTC
```
Running version: 1.6.10.4#dev
Python version: 3.7.0
Operating system: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Command line: sqlmap.py -r ************************ --random-agent --force-ssl -dbms mssql --technique=S --tables
Technique: STACKED
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 115, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/dbms/mssqlserver/enumeration.py", line 154, in getTables
    table = safeSQLIdentificatorNaming(table, True)
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-10-26 15:54
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5202 (fixed)

**Closed by stamparm** 2022-10-26 15:54 UTC
