### ISSUE TITLE
sqlmap stops instead of continuing

### ISSUE THREAD

**Issue by komer83** [sqlmapproject/sqlmap#3798] opened 2019-07-04 15:07 UTC
**Describe the bug**
sqlmap stops instead of continuing scanning when need to select. 

**To Reproduce**
1. Run '...'
2. See error
1. sqlmap -DBS --dump-all --dbms=mysql --risk=3 --level=5 -u XXXX.XXXX.XXXX
2. RE ANALYSE (EXTRACTVALUE)'
[11:00:13] [INFO] testing 'MySQL >= 5.1 time-based blind (heavy query - comment) - PROCEDURE ANALYSE (EXTRACTVALUE)'
[11:00:18] [INFO] testing 'MySQL >= 5.0.12 time-based blind - Parameter replace'
[11:00:18] [INFO] testing 'MySQL >= 5.0.12 time-based blind - Parameter replace (substraction)'
[11:00:18] [INFO] testing 'MySQL <= 5.0.11 time-based blind - Parameter replace (heavy queries)'
[11:00:18] [INFO] testing 'MySQL time-based blind - Parameter replace (bool)'
[11:00:19] [INFO] testing 'MySQL time-based blind - Parameter replace (ELT)'
[11:00:25] [INFO] testing 'MySQL time-based blind - Parameter replace (MAKE_SET)'
[11:00:26] [INFO] testing 'MySQL >= 5.0.12 time-based blind - ORDER BY, GROUP BY clause'
[11:00:26] [INFO] testing 'MySQL <= 5.0.11 time-based blind - ORDER BY, GROUP BY clause (heavy query)'
it is recommended to perform only basic UNION tests if there is not at least one other (potential) technique found. Do you want to reduce the number of requests? [Y/n] Y
bash: Y: command not found

[1]+  Stopped                 sqlmap -DBS --dump-all --dbms=mysql --risk=3 --level=5 -u XXXX.XXXX.XXXX
root@kali:~#  

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev] 1.3.7#stable
 - Installation method [e.g. git] Kali Linux
 - Operating system: [e.g. Microsoft Windows 10] Kali Linux
 - Python version [e.g. 3.5.2] 3.7

**Target details:**
 - DBMS [e.g. Microsoft SQL Server] MySQL
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment] 2019-07-04 22:09
Duplicate of #3749

**Closed by stamparm** 2019-07-04 22:09 UTC
Labels: bug report
