### ISSUE TITLE
Unhandled exception (#d25b54ea)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5269] opened 2022-12-20 14:22 UTC
```
Running version: 1.6.12.7#dev
Python version: 3.10.4
Operating system: Windows-10-10.0.19044-SP0
Command line: sqlmap.py -d *********************************************** -f --os-cmd=dir
Technique: DIRECT
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 281, in start
    action()
  File "lib/controller/action.py", line 218, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 60, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 219, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 183, in udfInjectSys
    return self.udfInjectCore(self.sysUdfs)
  File "lib/takeover/udf.py", line 147, in udfInjectCore
    self.udfSetRemotePath()
  File "plugins/dbms/mysql/takeover.py", line 41, in udfSetRemotePath
    if banVer and LooseVersion(banVer) >= LooseVersion("5.0.67"):
  File "C:/Python310/lib/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "C:/Python310/lib/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '10.3.34-'
```

**Comment by stamparm** [comment] 2022-12-20 14:37
Duplicate of #5268

**Closed by stamparm** 2022-12-20 14:37 UTC
