### ISSUE TITLE
bash: Y: order not found

### ISSUE THREAD

**Issue by Kuhitacop** [sqlmapproject/sqlmap#2646] opened 2017-08-03 20:17 UTC
Hello, when I get the typical Y/n/q message and I answer, I get this error:
custom injection marker ('*') found in option '-u'. Do you want to process it? [Y/n/q] Y
bash: Y: No order found

"No order found translated from Spanish"

thanks!

**Comment by Kuhitacop** [comment] 2017-08-03 20:38
[22:37:55] [INFO] testing if the target URL is stable
[22:37:55] [WARNING] target URL is not stable. sqlmap will base the page comparison on a sequence matcher. If no dynamic nor injectable parameters are detected, or in case of junk results, refer to user's manual paragraph 'Page comparison' and provide a string or regular expression to match on
how do you want to proceed? [(C)ontinue/(s)tring/(r)egex/(q)uit] C
bash: C: no se encontró la orden

**Comment by stamparm** [comment] 2017-08-04 06:18
Duplicate of #610

**Closed** 2017-08-04 06:18 UTC
Labels: duplicate
