### ISSUE TITLE
Unhandled exception (#e69df17b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1359] opened 2015-08-25 04:12 UTC
```
sqlmap version: 1.0-dev-nongit-20150825
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -r post.txt --dbms=mysql --ignore-proxy --level 3 --risk 3 -v 3
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    init()
  File "lib/core/option.py", line 2497, in init
    _setRequestFromFile()
  File "lib/core/option.py", line 522, in _setRequestFromFile
    _feedTargetsDict(conf.requestFile, addedTargetUrls)
  File "lib/core/option.py", line 390, in _feedTargetsDict
    _parseBurpLog(content)
  File "lib/core/option.py", line 367, in _parseBurpLog
    b = a.split('&')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by stamparm** [comment] 2015-08-26 08:54
Duplicate of #1355 and #1346

**Closed by stamparm** 2015-08-26 08:54 UTC
