### ISSUE TITLE
Unhandled exception (#b5df7905)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1526] opened 2015-11-07 16:24 UTC
```
sqlmap version: 1.0-dev-fb5a75c
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u ************************************************************************************* --random-agent -o -p id
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 109, in main
    start()
  File "lib/controller/controller.py", line 521, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 425, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/request/connect.py", line 1055, in queryPage
    pageLength = int(headers[HTTP_HEADER.CONTENT_LENGTH])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by stamparm** [comment] 2015-11-07 18:19
Duplicate of #1416 (fixed)

**Closed by stamparm** 2015-11-07 18:19 UTC
