### ISSUE TITLE
Unhandled exception (#c15d1062)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3521] opened 2019-03-06 20:33 UTC
```
Running version: 1.3.3.10#dev
Python version: 2.7.15
Operating system: Linux-3.18.14-14928722-QB20938408-armv8l-with-libc
Command line: sqlmap.py -g ****************************** --dbs --batch --tamper=space2comment --keep-alive --risk=2 --level=2 --smart --flush-session --output=Hasil
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 167, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 526, in start
    check = checkDynParam(place, parameter, value)
  File "lib/controller/checks.py", line 1135, in checkDynParam
    dynResult = Request.queryPage(payload, place, raise404=False)
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1280, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 776, in getPage
    logHTTPTraffic(requestMsg, "%s%s\r\n\r\n%s" % (responseMsg, logHeaders, (page or "")[:MAX_CONNECTION_CHUNK_SIZE]), start, time.time())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 526: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-03-07 13:59
Duplicate of #3522 (fixed)

**Closed by stamparm** 2019-03-07 13:59 UTC
