### ISSUE TITLE
Unhandled exception (#e5ea1a46)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4226] opened 2020-06-05 07:00 UTC
```
Running version: 1.3.6.57#dev
Python version: 2.7.15
Operating system: Windows-10-10.0.18362
Command line: sqlmap.py -r **************************** --tables
Technique: QUERY
Back-end DBMS: Oracle (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 683, in start
    action()
  File "lib/controller/action.py", line 113, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/generic/databases.py", line 227, in getTables
    dbs = self.getDbs()
  File "plugins/generic/databases.py", line 118, in getDbs
    values = inject.getValue(query, blind=False, time=False)
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 437, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 334, in errorUse
    count = unArrayizeValue(_oneShotErrorUse(countedExpression, countedExpressionFields))
  File "lib/techniques/error/use.py", line 92, in _oneShotErrorUse
    result = unArrayizeValue(_oneShotErrorUse(testQuery, chunkTest=True))
  File "lib/techniques/error/use.py", line 127, in _oneShotErrorUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.ERROR].vector
KeyError: 2
```

**Comment by stamparm** [comment] 2020-06-05 14:57
Duplicate of #4225

**Closed by stamparm** 2020-06-05 14:57 UTC
