### ISSUE TITLE
Unhandled exception (#7fc55288)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2157] opened 2016-09-06 02:41 UTC
```
sqlmap version: 1.0.5.46#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u ********************************************************** -p rid --random-agent -v 3 --delay 0.5 --retries 3 --tamper passdog --safe-url http://www.szrsrc.com.cn/ --safe-freq 3 --timeout 20 --time-sec 20
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 128, in main
    init()
  File "lib/core/option.py", line 2572, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 918, in _setTamperingFunctions
    raise SqlmapSyntaxException("cannot import tamper script '%s' (%s)" % (filename[:-3], msg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 75: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-09-06 11:58
Duplicate of #1960 (fixed)

**Closed by stamparm** 2016-09-06 11:58 UTC
