### ISSUE TITLE
Unhandled exception (#c7329026)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3649] opened 2019-05-11 15:26 UTC
```
Running version: 1.3.5.59#dev
Python version: 3.7.3
Operating system: Windows-10-10.0.17763-SP0
Command line: sqlmap.py -u *********************************************** --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 179, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 570, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 540, in checkSqlInjection
    elif threadData.lastComparisonRatio > UPPER_RATIO_BOUND and not any((conf.string, conf.notString, conf.regexp, conf.code, kb.nullConnection)):
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

**Comment by stamparm** [comment] 2019-05-12 02:01
Duplicate of #3644 (fixed)

**Closed by stamparm** 2019-05-12 02:01 UTC
