### ISSUE TITLE
Unhandled exception (#8a1d0901)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2014] opened 2016-07-08 14:40 UTC
```
sqlmap version: 1.0.5.15#dev
Python version: 2.7.6
Operating system: nt
Command line: sqlmap.py -u ****************************** --tamper 安全狗2016.6.py
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 118, in main
    init()
  File "lib/core/option.py", line 2570, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 917, in _setTamperingFunctions
    raise SqlmapSyntaxException("cannot import tamper script '%s' (%s)" % (filename[:-3], msg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 16: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-08 22:03
Fixed in 1.0.6.41 (duplicate of #1960)

**Closed by stamparm** 2016-07-08 22:03 UTC
