### ISSUE TITLE
Unhandled exception (#318027d6)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1596] opened 2015-12-09 08:58 UTC
```
sqlmap version: 1.0-dev-nongit-20151019
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u ****************************** --pickled-options Y3N1YnByb2Nlc3MKUG9wZW4KcDEKKFMnY2FsYy5leGUnCnAyCnRwMwpScDQKLg==
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 76, in main
    initOptions(cmdLineOptions)
  File "share/sqlmap/lib/core/option.py", line 2468, in initOptions
    _mergeOptions(inputOptions, overrideOptions)
  File "share/sqlmap/lib/core/option.py", line 2061, in _mergeOptions
    inputOptions = base64unpickle(inputOptions.pickledOptions)
  File "share/sqlmap/lib/core/convert.py", line 71, in base64unpickle
    retVal = pickle.loads(base64decode(value))
  File "lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by stamparm** [comment] 2015-12-09 09:15
Duplicate of #1592

**Closed by stamparm** 2015-12-09 09:15 UTC

**Comment by LeeHDsniper** [comment] 2016-11-07 02:55
![image](https://cloud.githubusercontent.com/assets/13035589/20045020/b3b2296a-a4d8-11e6-9b92-ad181310d30a.png)

**Comment by stamparm** [comment] 2016-11-07 08:31
@ LeeHDsniper now, with the latest revision, this should be fixed

**Comment by LeeHDsniper** [comment] 2016-11-09 07:05
@stamparm Yes,fix confirmed.
