### ISSUE TITLE
Unhandled exception (#9b21e86c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4246] opened 2020-06-25 11:16 UTC
```
Running version: 1.4.6.15#dev
Python version: 3.8.3
Operating system: Linux-3.18.91-14843133-QB28500970-aarch64-with-libc
Command line: sqlmap.py -u ************* --batch
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 340, in start
    conf.data = re.sub(r"\b(__\w+)=([^&]+)", lambda match: "%s=%s" % (match.group(1), urlencode(match.group(2), safe='%')), conf.data)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by stamparm** [comment] 2020-06-25 11:33
Duplicate of #4245 (fixed)

**Closed by stamparm** 2020-06-25 11:33 UTC
