### ISSUE TITLE
nope. i would just skip enumeration of database users and focus on something else. if `--tables` and `--dbs` are also blocked, you'll need to use `--common-...` switches

### ISSUE THREAD

**Issue by abhisheksdp** [sqlmapproject/sqlmap#5396] opened 2023-04-18 11:46 UTC
nope. i would just skip enumeration of database users and focus on something else. if `--tables` and `--dbs` are also blocked, you'll need to use `--common-...` switches

_Originally posted by @stamparm in https://github.com/sqlmapproject/sqlmap/issues/5036#issuecomment-1073975842_
            
##############
in my case my i am able to access the --banner but not able to access the --dbs or --tables , --users 

i am getting this error 

 schema names are going to be used on PostgreSQL for enumeration as the counterpart to database names on other DBMSes
[17:15:02] [INFO] fetching database (schema) names
[17:15:02] [INFO] fetching number of databases
[17:15:02] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[17:15:02] [INFO] retrieved:
[17:15:02] [WARNING] time-based comparison requires larger statistical model, please wait........................... (done)
[17:15:03] [WARNING] it is very important to not stress the network connection during usage of time-based payloads to prevent potential disruptions

[17:15:03] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[17:15:03] [ERROR] unable to retrieve the number of databases
[17:15:03] [INFO] falling back to current database
[17:15:03] [INFO] fetching current database
[17:15:03] [INFO] retrieved:
[17:15:03] [INFO] retrieved:
[17:15:03] [WARNING] on PostgreSQL you'll need to use schema names for enumeration as the counterpart to database names on other DBMSes
[17:15:03] [CRITICAL] unable to retrieve the database names

**Comment by stamparm** [comment] 2023-04-24 12:58
duplicate of #5399

**Closed by stamparm** 2023-04-24 12:58 UTC
