### ISSUE TITLE
Unhandled exception (#83cdf804)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4405] opened 2020-10-27 16:32 UTC
```
Running version: 1.4.10.20#dev
Python version: 2.7.18
Operating system: Linux-4.14.141-g9713385-aarch64-with-libc
Command line: sqlmap.py -u *************************************************** --dbs
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 704, in start
    action()
  File "lib/controller/action.py", line 107, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 142, in getDbs
    values = inject.getValue(query, blind=False, time=False)
  File "lib/core/decorators.py", line 94, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 422, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 351, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 251, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 141, in _oneShotUnionUse
    for row in json.loads(output[len(kb.chars.start):-len(kb.chars.stop)]):
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by stamparm** [comment] 2020-10-27 16:40
Duplicate of #4404 (fixed)

**Closed** 2020-10-27 16:40 UTC
Labels: duplicate
