### ISSUE TITLE
Unhandled exception (#20d4b5cd)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3273] opened 2018-10-04 10:02 UTC
```
Running version: 1.2.10.9#dev
Python version: 2.7.13
Operating system: Linux-4.12.0-kali2-686-i686-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py -d ******************************************** --os-cmd ping 10.11.0.44
Technique: DIRECT
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 164, in main
    start()
  File "lib/core/decorators.py", line 34, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 268, in start
    action()
  File "lib/controller/action.py", line 151, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 57, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 209, in initEnv
    self.xpCmdshellInit()
  File "lib/takeover/xp_cmdshell.py", line 250, in xpCmdshellInit
    result = self._xpCmdshellCheck()
  File "lib/takeover/xp_cmdshell.py", line 96, in _xpCmdshellCheck
    self.xpCmdshellExecCmd(cmd)
  File "lib/takeover/xp_cmdshell.py", line 185, in xpCmdshellExecCmd
    return inject.goStacked(self.xpCmdshellForgeCmd(cmd), silent)
  File "lib/request/inject.py", line 502, in goStacked
    return direct(expression)
  File "lib/request/direct.py", line 62, in direct
    conf.dbmsConnector.connect()
  File "lib/utils/sqlalchemy.py", line 62, in connect
    engine = _sqlalchemy.create_engine(conf.direct, connect_args={})
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 56, in create
    entrypoint = u._get_entrypoint()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 139, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 201, in load
    loader = self.auto_fn(name)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/dialects/__init__.py", line 30, in _auto_fn
    dialect, driver = name.split(".")
ValueError: too many values to unpack
```

**Comment by stamparm** [comment] 2018-10-04 11:43
Duplicate of #3272

**Closed by stamparm** 2018-10-04 11:43 UTC
