### ISSUE TITLE
Unhandled exception (#122facf5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4191] opened 2020-05-07 03:45 UTC
```
Runnin* version: 1.4.1.47#dev
Python version: 2.7.17
Operatin* system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=************************************************************************* --threads=1 --tamper=space2comment.py --tamper=base64encode.py --tamper=between.py --hex --retries=0 --null-connection --timeout=5 --risk=3 --level=1 --dbms=mysql,mssql --time-sec=15 --technique=BSTQ --random-a*ent -D * --tables --answers=*************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: BOOLEAN
Back-end DBMS: Microsoft SQL Server (fin*erprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 212, in main
    start()
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 697, in start
    action()
  File "lib/controller/action.py", line 113, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/dbms/mssqlserver/enumeration.py", line 135, in getTables
    count = inject.getValue(_, union=False, error=False, expected=EXPECTED.INT, charsetType=CHARSET_TYPE.DIGITS)
  File "lib/core/decorators.py", line 91, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 511, in getValue
    return extractExpectedValue(value, expected)
  File "lib/core/common.py", line 4814, in extractExpectedValue
    value = int(value) if value.isdigit() else None
ValueError: invalid literal for int() with base 10: '\xb9'
```

**Comment by stamparm** [comment] 2020-05-08 14:27
Duplicate of #4116 (fixed)

**Closed by stamparm** 2020-05-08 14:27 UTC
