### ISSUE TITLE
Unhandled exception (#fa0b24d4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2039] opened 2016-07-18 10:11 UTC
```
sqlmap version: 1.0.7.25#dev
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u ********************************************************** -D *************** --dump
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
  File "plugins/generic/databases.py", line 555, in getColumns
    values = unionUse(expression)
  File "lib/techniques/union/use.py", line 211, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 108, in _oneShotUnionUse
    root = xml.etree.ElementTree.fromstring("<root>%s</root>" % output)
  File "usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1999
```

**Comment by stamparm** [comment] 2016-07-18 10:25
Duplicate of #2026 (fixed)

**Closed by stamparm** 2016-07-18 10:25 UTC
