### ISSUE TITLE
Unhandled exception (#41438216)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4524] opened 2021-01-05 14:04 UTC
```
Running version: 1.5.1.7#dev
Python version: 3.9.1
Operating system: Windows-2012ServerR2-6.3.9600-SP0
Command line: sqlmap.py --output-dir=output --url=******************************************************************** --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql --technique=EU --random-agent --is-dba --exclude-sysdbs --current-db --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1544, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1423, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 882, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 384, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None, status)
  File "lib/request/basic.py", line 151, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 37, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/AppData/Local/Programs/Python/Python39/lib/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/AppData/Local/Programs/Python/Python39/lib/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/AppData/Local/Programs/Python/Python39/lib/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/AppData/Local/Programs/Python/Python39/lib/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/A/34/s/Modules/pyexpat.c", line 407, in StartElement
  File "/AppData/Local/Programs/Python/Python39/lib/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "lib/parse/handler.py", line 65, in startElement
    if self._dbmsVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-01-05 14:09
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-01-05 14:09 UTC
