### ISSUE TITLE
Unhandled exception (#c49f02b7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3931] opened 2019-09-16 14:31 UTC
```
Running version: 1.3.9.13#dev
Python version: 2.7.16+
Operating system: Linux-5.2.0-kali2-amd64-x86_64-with-debian-kali-rolling
Command line: /usr/bin/sqlmap -u **************************************** --forms
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 159, in main
    init()
  File "/share/sqlmap/lib/core/option.py", line 2656, in init
    _findPageForms()
  File "/share/sqlmap/lib/core/option.py", line 470, in _findPageForms
    if findPageForms(page, conf.url, True, True):
  File "/share/sqlmap/lib/core/common.py", line 4410, in findPageForms
    forms = ParseResponse(filtered, backwards_compat=False)
  File "/share/sqlmap/thirdparty/clientform/clientform.py", line 1074, in ParseResponse
    return _ParseFileEx(response, response.geturl(), *args, **kwds)[1:]
  File "/share/sqlmap/thirdparty/clientform/clientform.py", line 1110, in _ParseFileEx
    fp.feed(data)
  File "/share/sqlmap/thirdparty/clientform/clientform.py", line 880, in feed
    sgmllib.SGMLParser.feed(self, data)
  File "/lib/python2.7/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/lib/python2.7/sgmllib.py", line 193, in goahead
    self.handle_entityref(name)
  File "/share/sqlmap/thirdparty/clientform/clientform.py", line 761, in handle_entityref
    '&%s;' % name, self._entitydefs, self._encoding))
  File "/share/sqlmap/thirdparty/clientform/clientform.py", line 247, in unescape
    return re.sub(r"&#?[A-Za-z0-9]+?;", replace_entities, data)
  File "/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 0: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-09-16 17:07
Duplicate of #3926

**Closed by stamparm** 2019-09-16 17:07 UTC
