### ISSUE TITLE
Unhandled exception (#2e7c4232)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1737] opened 2016-02-29 16:44 UTC
```
sqlmap version: 1.0-dev-nongit-20160217-0b4b
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -d ************************************************** -v 3 --os=Windows --dbms=mssql -D ************** --tables
Technique: DIRECT
Back-end DBMS: Microsoft SQL Server (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 114, in main
    start()
  File "lib/controller/controller.py", line 258, in start
    action()
  File "lib/controller/action.py", line 32, in action
    setHandler()
  File "lib/controller/handler.py", line 97, in setHandler
    conf.dbmsConnector.connect()
  File "plugins/dbms/mssqlserver/connector.py", line 43, in connect
    self.connector = pymssql.connect(host="%s:%d" % (self.hostname, self.port), user=self.user, password=self.password, database=self.db, login_timeout=conf.timeout, timeout=conf.timeout)
  File "pymssql.pyx", line 584, in pymssql.connect (pymssql.c:9118)
    conn.query_timeout = timeout
  File "_mssql.pyx", line 402, in _mssql.MSSQLConnection.query_timeout.__set__ (_mssql.c:4132)
    check_and_raise(rtc, self)
  File "_mssql.pyx", line 1408, in _mssql.check_and_raise (_mssql.c:13444)
    return maybe_raise_MSSQLDatabaseException(conn)
  File "_mssql.pyx", line 1457, in _mssql.maybe_raise_MSSQLDatabaseException (_mssql.c:14091)
    raise ex
MSSQLDatabaseException: (916, 'The server principal "sqlmap" is not able to access the database **************** under the current security context. DB-Lib error message 916, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n')
```

**Comment by stamparm** [comment] 2016-03-01 14:34
Duplicate of #1731 (fixed)

**Closed by stamparm** 2016-03-01 14:34 UTC
