### ISSUE TITLE
Unhandled exception (#1580c1bc)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2334] opened 2017-01-07 06:20 UTC
```
sqlmap version: 1.1.1.3#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ****************************** --form
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 151, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1439, in checkConnection
    page, headers = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1152, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 697, in getPage
    processResponse(page, responseHeaders)
  File "lib/request/basic.py", line 366, in processResponse
    conf.parameters[PLACE.POST] = re.sub("(?i)(%s=)[^&]+" % name, r"\g<1>%s" % value, conf.parameters[PLACE.POST])
  File "Python27/lib/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "Python27/lib/re.py", line 291, in filter
    return sre_parse.expand_template(template, match)
  File "Python27/lib/sre_parse.py", line 833, in expand_template
    raise error, "invalid group reference"
error: invalid group reference
```

**Comment by stamparm** [comment] 2017-01-08 00:15
Duplicate of #2333

**Closed by stamparm** 2017-01-08 00:15 UTC
