### ISSUE TITLE
Unhandled exception (#62156d7a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1645] opened 2016-01-08 14:50 UTC
```
sqlmap version: 1.0-dev-nongit-201601080a8c
Python version: 2.7.9
Operating system: posix
Command line: sqlmap.py -u ****************************************************
Technique: UNION
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 565, in start
    percent = (100.0 * len(getFilteredPageContent(kb.originalPage)) / len(kb.originalPage))
  File "lib/core/common.py", line 1668, in getFilteredPageContent
    retVal = htmlunescape(retVal.strip())
  File "lib/core/convert.py", line 163, in htmlunescape
    retVal = re.sub(r"&#x([^;]+);", lambda match: chr(int(match.group(1), 16)), retVal)
  File "usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-01-08 15:05
Duplicate of #1639 (fixed)

**Closed by stamparm** 2016-01-08 15:05 UTC
