### ISSUE TITLE
Unhandled exception (#d79dcbac)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2875] opened 2018-01-12 13:06 UTC
```
sqlmap version: 1.2.1.6#dev
Python version: 2.6.6
Operating system: nt
Command line: sqlmap.py -r C:/max/16.txt --level=5 --risk=3 --dbs -D ************************* --dump
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 395, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 435, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 288, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 131, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 103, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 616, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 334, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "Python26/lib/urllib2.py", line 192, in __init__
    self.__original = unwrap(url)
  File "Python26/lib/urllib.py", line 1034, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by stamparm** [comment] 2018-01-17 11:39
Duplicate of #2886

**Closed by stamparm** 2018-01-17 11:39 UTC
