### ISSUE TITLE
Unhandled exception (#6796a93a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2091] opened 2016-08-09 16:16 UTC
```
sqlmap version: 1.0.8.16#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ************************************************************* --dbs
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in main
    start()
  File "lib/controller/controller.py", line 522, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 451, in checkSqlInjection
    falseRawResponse = "%s%s" % (falseHeaders, falsePage)
MemoryError
```

**Comment by stamparm** [comment] 2016-08-10 00:10
Duplicate of #2085

**Closed by stamparm** 2016-08-10 00:10 UTC
