### ISSUE TITLE
Unhandled exception (#94a062d3)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2866] opened 2018-01-05 21:45 UTC
```
sqlmap version: 1.2.1.5#dev
Python version: 2.7.5
Operating system: posix
Command line: sqlmap.py --random-agent -u ************************************************* -o --threads=10 --time-sec=20 -D webddxan-db1 --dump all
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 431, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 607, in dbTableValues
    self._write("| %s%s" % (value, blank), newline=False, console=console)
  File "lib/core/dump.py", line 73, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 908, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "lib/core/common.py", line 877, in setColor
    level = getattr(logging, level, None) if isinstance(level, basestring) else level
UnicodeEncodeError: 'ascii' codec can't encode characters in position 165-172: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2018-01-06 01:25
Duplicate of #2862

**Closed by stamparm** 2018-01-06 01:25 UTC
