### ISSUE TITLE
Unhandled exception (#ece21eb1)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2466] opened 2017-04-06 08:33 UTC
```
sqlmap version: 1.0.12.5#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ******************************** --tamper “C:\Python27\sqlmap\tamper\halfversionedmorekeywords.py
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2653, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 905, in _setTamperingFunctions
    elif os.path.exists(os.path.join(paths.SQLMAP_TAMPER_PATH, script if script.endswith(".py") else "%s.py" % script)):
  File "lib/ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa1 in position 0: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-04-06 09:40
Duplicate of #2348. Please update

**Closed by stamparm** 2017-04-06 09:40 UTC
