### ISSUE TITLE
Unhandled exception (#a3c7b9a3)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2497] opened 2017-04-20 15:11 UTC
```
sqlmap version: 1.1.4.39#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -r d:\py\sqlmap\11.txt --level 1 --tamper=apostrophenullencode.py --random-agent -D ********* --tables
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 150, in main
    start()
  File "lib/controller/controller.py", line 374, in start
    setupTargetEnv()
  File "lib/core/target.py", line 728, in setupTargetEnv
    _resumeHashDBValues()
  File "lib/core/target.py", line 441, in _resumeHashDBValues
    injection.data = dict(filter(lambda key, item: key in conf.tech, injection.data.items()))
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by stamparm** [comment] 2017-04-21 09:52
Duplicate of #2491 (fixed)

**Closed by stamparm** 2017-04-21 09:52 UTC
