### ISSUE TITLE
Unhandled exception (#cafae879)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2179] opened 2016-09-23 22:22 UTC
```
sqlmap version: 1.0.9.24#dev
Python version: 2.7.12
Operating system: posix
Command line: sqlmap.py -u *************************************************** --dbs
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 522, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 753, in checkSqlInjection
    checkSuhosinPatch(injection)
  File "lib/controller/checks.py", line 869, in checkSuhosinPatch
    if not checkBooleanExpression("%d=%s%d" % (randInt, ' ' * SUHOSIN_MAX_VALUE_LENGTH, randInt)):
  File "lib/request/inject.py", line 492, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, charsetType=CHARSET_TYPE.BINARY, suppressOutput=True, expectingNone=expectingNone)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 215, in unionUse
    _, _, _, _, _, expressionFieldsList, expressionFields, _ = agent.getFields(origExpr)
  File "lib/core/agent.py", line 532, in getFields
    if re.search("\A\w+\(.*\)", fieldsToCastStr, re.I) or (fieldsSelectCase and "WHEN use" not in query) or fieldsSubstr:
  File "usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2016-09-23 22:38
Duplicate of #2176 (fixed)

**Closed by stamparm** 2016-09-23 22:38 UTC
