### ISSUE TITLE
Unhandled exception (#688cd7a2)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1088] opened 2015-01-03 03:00 UTC
```
sqlmap version: 1.0-dev
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -u *************************************************** --data=UID=87710 --os-shell
Technique: TIME
Back-end DBMS: PostgreSQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 594, in start
    action()
  File "lib/controller/action.py", line 160, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 80, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 200, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 184, in udfInjectSys
    self.udfSetLocalPaths()
  File "plugins/dbms/postgresql/takeover.py", line 64, in udfSetLocalPaths
    self.udfLocalFile = os.path.join(self.udfLocalFile, "postgresql", "linux", "%d" % Backend.getArch(), majorVer, "lib_postgresqludf_sys.so")
NameError: global name 'os' is not defined
```

**Comment by stamparm** [comment] 2015-01-03 21:16
Duplicate of #895 (patched)

**Closed by stamparm** 2015-01-03 21:16 UTC
Labels: duplicate
