### ISSUE TITLE
Unhandled exception (#d3c93c81)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4581] opened 2021-02-17 11:59 UTC
```
Running version: 1.5#stable
Python version: 3.9.1+
Operating system: Linux-5.10.0-kali2-amd64-x86_64-with-glibc2.31
Command line: sqlmap.py -r ../recovery.req --batch --random-agent --dbms=mysql -p txtrecovery --tamper=space2comment --level 5 --risk 3 --privileges --threads 10 --no-cast --os-shell
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 221, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 85, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 219, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 183, in udfInjectSys
    return self.udfInjectCore(self.sysUdfs)
  File "lib/takeover/udf.py", line 147, in udfInjectCore
    self.udfSetRemotePath()
  File "plugins/dbms/mysql/takeover.py", line 41, in udfSetRemotePath
    if distutils.version.LooseVersion(banVer) >= distutils.version.LooseVersion("5.0.67"):
  File "/usr/lib/python3.9/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib/python3.9/distutils/version.py", line 339, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
```

**Comment by stamparm** [comment] 2021-02-17 13:40
Duplicate of #4504 (fixed)

**Closed by stamparm** 2021-02-17 13:40 UTC
