### ISSUE TITLE
Unhandled exception (#53e71072)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5214] opened 2022-10-29 08:22 UTC
```
Running version: 1.6.10.4#dev
Python version: 3.10.0
Operating system: Windows-10-10.0.19043-SP0
Command line: sqlmap.py -r ********************************** --count
Technique: TIME
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 147, in action
    conf.dumper.dbTablesCount(conf.dbmsHandler.getCount())
  File "plugins/generic/databases.py", line 1017, in getCount
    self.getTables()
  File "plugins/dbms/mssqlserver/enumeration.py", line 154, in getTables
    table = safeSQLIdentificatorNaming(table, True)
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-11-01 21:22
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5202 (fixed)

**Closed by stamparm** 2022-11-01 21:22 UTC
