### ISSUE TITLE
Unhandled exception (#aa6827dd)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4716] opened 2021-06-19 05:25 UTC
```
Running version: 1.5.6#pip
Python version: 3.6.1
Operating system: Darwin-20.5.0-iPhone13,3-64bit
Command line: sqlmap.py -u ************************************* --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "lib/request/connect.py", line 606, in getPage
    conn = _urllib.request.urlopen(req)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 224, in urlopen
    return opener.open(url, data, timeout)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 527, in open
    response = self._open(req, data)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 545, in _open
    '_open', req)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 505, in _call_chain
    result = func(*args)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/urllib/request.py", line 1322, in do_open
    r = h.getresponse()
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 1332, in getresponse
    response.begin()
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 298, in begin
    version, status, reason = self._read_status()
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 259, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socket.py", line 587, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 591, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 638, in checkSqlInjection
    page, headers, _ = Request.queryPage(reqPayload, place, content=True, raise404=False)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1450, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 882, in getPage
    return Connect._retryProxy(**kwargs)
  File "lib/request/connect.py", line 217, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 151, in _getPageProxy
    if (len(inspect.stack()) > sys.getrecursionlimit() // 2):   # Note: https://github.com/sqlmapproject/sqlmap/issues/4525
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 1465, in stack
    return getouterframes(sys._getframe(1), context)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 1442, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 1416, in getframeinfo
    lines, lnum = findsource(frame)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 751, in findsource
    module = getmodule(object, file)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 710, in getmodule
    f = getabsfile(module)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 679, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 659, in getsourcefile
    filename = (os.path.splitext(filename)[0] +
  File "/var/containers/Bundle/Application/7A9E78EC-7E9C-4825-A01C-98423EFFECBE/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/posixpath.py", line 121, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not OmniClass
```

**Comment by stamparm** [comment] 2021-06-21 15:14
Duplicate of #4715

**Closed by stamparm** 2021-06-21 15:14 UTC
