### ISSUE TITLE
Unhandled exception (#95955660)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1937] opened 2016-06-08 13:56 UTC
```
sqlmap version: 1.0.5.39#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -r 100.txt --dbms=mysql --dbs
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1369, in checkConnection
    page, headers = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1109, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 666, in getPage
    return Connect._retryProxy(**kwargs)
  File "lib/request/connect.py", line 175, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 125, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "lib/request/connect.py", line 666, in getPage
    return Connect._retryProxy(**kwargs)
  File "lib/request/connect.py", line 175, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 125, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "lib/request/connect.py", line 666, in getPage
    return Connect._retryProxy(**kwargs)
  File "lib/request/connect.py", line 175, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 125, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "lib/request/connect.py", line 344, in getPage
    headers = forgeHeaders({HTTP_HEADER.COOKIE: cookie, HTTP_HEADER.USER_AGENT: ua, HTTP_HEADER.REFERER: referer, HTTP_HEADER.HOST: host})
  File "lib/request/basic.py", line 94, in forgeHeaders
    if ("%s=" % cookie.name) in headers[HTTP_HEADER.COOKIE]:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 11: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-06-10 15:53
Duplicate of #1938

**Closed by stamparm** 2016-06-10 15:53 UTC
