### ISSUE TITLE
Unhandled exception (#a07ecf85)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4497] opened 2020-12-26 07:18 UTC
```
Running version: 1.4.12.5#dev
Python version: 2.7.14
Operating system: Windows-10-10.0.18362
Command line: sqlmap.py -u **************************************************** --data=******************************************* -D ******* -T user --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 704, in start
    action()
  File "lib/controller/action.py", line 163, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 248, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/core/decorators.py", line 94, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 423, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 352, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 429, in unionUse
    output = _oneShotUnionUse(expression, unpack)
  File "lib/techniques/union/use.py", line 94, in _oneShotUnionUse
    page, headers, _ = Request.queryPage(payload, content=True, raise404=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1413, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 890, in getPage
    logHeaders = getUnicode("".join(responseHeaders.headers).strip())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 69: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2020-12-26 21:22
Duplicate of #4469 (fixed)

**Closed by stamparm** 2020-12-26 21:22 UTC
