### ISSUE TITLE
Unhandled exception (#7463e4df)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1651] opened 2016-01-08 23:36 UTC
```
sqlmap version: 1.0-dev-nongit-201601080a8c
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u ********************************************************************* --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 380, in start
    checkWaf()
  File "lib/controller/checks.py", line 1161, in checkWaf
    _ = hashDBRetrieve(HASHDB_KEYS.CHECK_WAF_RESULT, True)
  File "lib/core/common.py", line 3855, in hashDBRetrieve
    if not kb.inferenceMode and not kb.fileReadMode and any(_ in (retVal or "") for _ in (PARTIAL_VALUE_MARKER, PARTIAL_HEX_VALUE_MARKER)):
  File "lib/core/common.py", line 3855, in <genexpr>
    if not kb.inferenceMode and not kb.fileReadMode and any(_ in (retVal or "") for _ in (PARTIAL_VALUE_MARKER, PARTIAL_HEX_VALUE_MARKER)):
TypeError: argument of type 'bool' is not iterable
```

**Comment by stamparm** [comment] 2016-01-08 23:43
Duplicate of #1649 (fixed)

**Closed by stamparm** 2016-01-08 23:43 UTC
