### ISSUE TITLE
Unhandled exception (#6a6404b2)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4251] opened 2020-06-30 06:41 UTC
```
Running version: 1.2.12.28#dev
Python version: 2.7.15
Operating system: Windows-10-10.0.18362
Command line: sqlmap.py -u ********************************************** --tamper sqlmap_bypass_D盾_tamper.py
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 146, in main
    init()
  File "lib/core/option.py", line 2506, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 769, in _setTamperingFunctions
    raise SqlmapSyntaxException("cannot import tamper module '%s' (%s)" % (filename[:-3], getSafeExString(ex)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb6 in position 44: ordinal not in range(128)
```

**Comment by caperoni** [comment] 2020-06-30 13:54
It's simple space to /*DJSAWW%2B%26Lt%3B%2B*/ bypass. Nothing else.

Just delete all Chinese words and you've got to go.

**Comment by stamparm** [comment] 2020-07-01 09:12
Duplicate of #3534 (fixed)

p.s. running 18 months old version

**Closed by stamparm** 2020-07-01 09:12 UTC
