### ISSUE TITLE
Unhandled exception (#4b39a62a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1317] opened 2015-07-27 17:19 UTC
```
sqlmap version: 1.0-dev-ff6b62a
Python version: 2.7.9
Operating system: posix
Command line: sqlmap.py -u ******************************************* --tor --tor-port=9150 --tor-type=SOCKS5 --check-tor --delay=1 --random-agent -p id --file-read=/fpc/www/talent.upc.edu/controllers/professionals.php
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 625, in start
    action()
  File "lib/controller/action.py", line 150, in action
    conf.dumper.rFile(conf.dbmsHandler.readFile(conf.rFile))
  File "plugins/generic/filesystem.py", line 213, in readFile
    fileContent = self.nonStackedReadFile(remoteFile)
  File "plugins/dbms/mysql/filesystem.py", line 32, in nonStackedReadFile
    result = inject.getValue("HEX(LOAD_FILE('%s'))" % rFile, charsetType=CHARSET_TYPE.HEXADECIMAL)
  File "lib/request/inject.py", line 378, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 323, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 347, in unionUse
    output = _oneShotUnionUse(expression, unpack)
  File "lib/techniques/union/use.py", line 76, in _oneShotUnionUse
    page, headers = Request.queryPage(payload, content=True, raise404=False)
  File "lib/request/connect.py", line 1054, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 436, in getPage
    conn = urllib2.urlopen(req)
  File "usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "usr/lib/python2.7/httplib.py", line 1127, in getresponse
    response.begin()
  File "usr/lib/python2.7/httplib.py", line 485, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "usr/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "usr/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "usr/lib/python2.7/httplib.py", line 321, in readheaders
    raise LineTooLong("header line")
LineTooLong: got more than 65536 bytes when reading header line
```

**Comment by stamparm** [comment] 2015-07-28 07:36
Duplicate of #1315

**Closed by stamparm** 2015-07-28 07:36 UTC
