### ISSUE TITLE
Unhandled exception (#0a2994a8)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3572] opened 2019-04-09 15:46 UTC
```
Running version: 1.3.3.10#dev
Python version: 2.7.15
Operating system: Windows-10-10.0.17134
Command line: sqlmap.py ********************* --headers=Content-Type: application/x-www-form-urlencoded --risk=3 --level=5 --random-agent --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 167, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 411, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1571, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1280, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 776, in getPage
    logHTTPTraffic(requestMsg, "%s%s\r\n\r\n%s" % (responseMsg, logHeaders, (page or "")[:MAX_CONNECTION_CHUNK_SIZE]), start, time.time())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 423: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-04-12 08:33
Duplicate of #3522 (fixed)

**Closed by stamparm** 2019-04-12 08:33 UTC
