### ISSUE TITLE
Unhandled exception (#d24fa802)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1648] opened 2016-01-08 21:45 UTC
```
sqlmap version: 1.0-dev-c7ea3d6
Python version: 2.7.10
Operating system: posix
Command line: sqlmap.py -u ***************************************************************************************** -v3 -p products_id
Technique: UNION
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 565, in start
    percent = (100.0 * len(getFilteredPageContent(kb.originalPage)) / len(kb.originalPage))
  File "lib/core/common.py", line 1668, in getFilteredPageContent
    retVal = htmlunescape(retVal.strip())
  File "lib/core/convert.py", line 163, in htmlunescape
    retVal = re.sub(r"&#x([^;]+);", lambda match: chr(int(match.group(1), 16)), retVal)
  File "System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "lib/core/convert.py", line 163, in <lambda>
    retVal = re.sub(r"&#x([^;]+);", lambda match: chr(int(match.group(1), 16)), retVal)
ValueError: chr() arg not in range(256)
```

**Comment by stamparm** [comment] 2016-01-08 22:11
Duplicate of #1647 (fixed)

**Closed by stamparm** 2016-01-08 22:11 UTC
