### ISSUE TITLE
Unhandled exception (#a6748220)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5808] opened 2024-11-16 09:37 UTC
```
Running version: 1.8.11.8#dev
Python version: 2.7.18
Operating system: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-Ubuntu-22.04-jammy
Command line: sqlmap.py -r /mnt/c/Users/Haris/Desktop/arynew.txt --sql-query=EXEC sp_configure 'show advanced options', 1; RECONFIGURE;
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 189, in action
    conf.dumper.sqlQuery(query, conf.dbmsHandler.sqlQuery(query))
  File "plugins/generic/custom.py", line 68, in sqlQuery
    if "SELECT" in sqlType and isListLike(output):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by stamparm** [comment] 2024-11-16 17:51
Duplicate of #5806

**Closed by stamparm** 2024-11-16 17:51 UTC
