### ISSUE TITLE
Unhandled exception (#99874183)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2009] opened 2016-07-06 09:41 UTC
```
sqlmap version: 1.0.5.23#dev
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -r C:\Users\*************\Desktop\post.txt --tamper 360.py
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 126, in main
    init()
  File "lib/core/option.py", line 2572, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 918, in _setTamperingFunctions
    raise SqlmapSyntaxException("cannot import tamper script '%s' (%s)" % (filename[:-3], msg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 38: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-06 09:44
Fixed in 1.0.6.41 (duplicate of #1960)

**Closed by stamparm** 2016-07-06 09:44 UTC
