### ISSUE TITLE
Unhandled exception (#65bc5c3c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4508] opened 2021-01-04 08:22 UTC
```
Running version: 1.3.12#stable
Python version: 3.9.0
Operating system: macOS-10.14.6-x86_64-i386-64bit
Command line: /usr/local/bin/sqlmap -u ********************************************************************** --method=POST --data=num_com=*
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 166, in main
    init()
  File "/Cellar/sqlmap/1.3.12/libexec/lib/core/option.py", line 2687, in init
    loadBoundaries()
  File "/Cellar/sqlmap/1.3.12/libexec/lib/parse/payloads.py", line 89, in loadBoundaries
    parseXmlNode(root)
  File "/Cellar/sqlmap/1.3.12/libexec/lib/parse/payloads.py", line 44, in parseXmlNode
    for element in node.getiterator("boundary"):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

**Comment by stamparm** [comment] 2021-01-04 11:40
Duplicate of #4126 (fixed long ago)

**Closed by stamparm** 2021-01-04 11:40 UTC
