### ISSUE TITLE
Unhandled exception (#cf69cf73)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4522] opened 2021-01-05 13:27 UTC
```
Running version: 1.5.1.7#dev
Python version: 2.7.15+
Operating system: Linux-4.18.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py -u ******************************* --random-agent -f --banner --current-user --passwords --tables --exclude-sysdbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1544, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1423, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 586, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "lib/request/redirecthandler.py", line 120, in http_error_302
    parseResponse(content, headers)
  File "lib/request/basic.py", line 151, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 37, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 336, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "lib/parse/handler.py", line 65, in startElement
    if self._dbmsVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-01-05 13:53
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-01-05 13:53 UTC
Labels: duplicate
