### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3683] opened 2019-05-19 10:40 UTC
Running version: 1.3.5.89#dev
Python version: 2.7.16rc1
Operating system: Linux-4.19.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: `sqlmap.py --url=*************************************************** --text-only --technique=EUS --dbms=mysql --random-agent --os=windows --no-cast --dump -D ****************** -U ************************ --dump-format=SQLITE --eta --skip-waf`
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 676, in start
    condition = True
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 448, in dumpTable
    attackDumpedTable()
  File "lib/utils/hash.py", line 673, in attackDumpedTable
    storeHashesToFile(attack_dict)
  File "lib/utils/hash.py", line 603, in storeHashesToFile
    f.write(item)
  File "/usr/lib/python2.7/codecs.py", line 708, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 4: ordinal not in range(128)

**Comment by stamparm** [comment] 2019-05-19 21:49
Duplicate of #3664 (fixed)

**Closed by stamparm** 2019-05-19 21:49 UTC
Labels: bug report
