### ISSUE TITLE
Unhandled exception (#f0b0f488)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1573] opened 2015-11-30 00:57 UTC
```
sqlmap version: 1.0-dev-nongit-20151129
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u ************************************************ -a
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 100, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 625, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 32, in action
    setHandler()
  File "share/sqlmap/lib/controller/handler.py", line 103, in setHandler
    if handler.checkDbms():
  File "share/sqlmap/plugins/dbms/mysql/fingerprint.py", line 159, in checkDbms
    self.getBanner()
  File "share/sqlmap/plugins/generic/enumeration.py", line 57, in getBanner
    kb.data.banner = unArrayizeValue(inject.getValue(query, safeCharEncode=False))
  File "share/sqlmap/lib/request/inject.py", line 423, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "share/sqlmap/lib/request/inject.py", line 279, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "share/sqlmap/lib/request/inject.py", line 127, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "share/sqlmap/lib/request/inject.py", line 99, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "share/sqlmap/lib/techniques/blind/inference.py", line 532, in bisection
    val = getChar(index, asciiTbl)
  File "share/sqlmap/lib/techniques/blind/inference.py", line 259, in getChar
    forgedPayload = safeStringFormat(payload, (expressionUnescaped, idx, posValue))
  File "share/sqlmap/lib/core/common.py", line 1627, in safeStringFormat
    raise Exception("wrong number of parameters during string formatting")
Exception: wrong number of parameters during string formatting
```

**Comment by stamparm** [comment] 2015-11-30 15:48
Duplicate of #1533. Same user, same bug. User has to update.

p.s. current line 1627 is:

`if any('%s' in _ for _ in conf.parameters.values()):`

**Closed by stamparm** 2015-11-30 15:48 UTC
