### ISSUE TITLE
Unhandled exception (#3c92907b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3763] opened 2019-06-17 12:40 UTC
```
Running version: 1.3.3.30#dev
Python version: 2.7.5
Operating system: Linux-4.11.8-1.el7.elrepo.x86_64-x86_64-with-centos-7.6.1810-Core
Command line: sqlmap.py -u *************************************************** --chunk
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 171, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 411, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1571, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1289, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 280, in getPage
    post = urllib.unquote(post)
  File "/usr/lib64/python2.7/urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by stamparm** [comment] 2019-06-17 12:52
Duplicate of #3541 (fixed 3 months ago)

**Closed by stamparm** 2019-06-17 12:52 UTC
