### ISSUE TITLE
Unhandled exception (#042d517b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1591] opened 2015-12-09 07:20 UTC
```
sqlmap version: 1.0-dev-nongit-201511240893
Python version: 2.6.6
Operating system: posix
Command line: sqlmap.py --pickled-options Y29zCnN5c3RlbQooUydkaXInCnRSLg==
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 86, in main
    initOptions(cmdLineOptions)
  File "lib/core/option.py", line 2519, in initOptions
    _mergeOptions(inputOptions, overrideOptions)
  File "lib/core/option.py", line 2101, in _mergeOptions
    if inputOptions.configFile:
AttributeError: 'int' object has no attribute 'configFile'
```

**Comment by stamparm** [comment] 2015-12-09 08:51
Duplicate of #1592

**Closed by stamparm** 2015-12-09 08:51 UTC
