### ISSUE TITLE
Unhandled exception (#4cdccd33)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3714] opened 2019-05-25 15:14 UTC
```
Running version: 1.3.5.140#dev
Python version: 2.7.16
Operating system: Linux-4.19.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap -u ************************************************** --dbms=mysql --all
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 180, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 673, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 165, in action
    conf.dbmsHandler.dumpAll()
  File "/share/sqlmap/plugins/generic/entries.py", line 500, in dumpAll
    self.dumpTable()
  File "/share/sqlmap/plugins/generic/entries.py", line 240, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "/share/sqlmap/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/inject.py", line 402, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "/share/sqlmap/lib/request/inject.py", line 338, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "/share/sqlmap/lib/techniques/union/use.py", line 408, in unionUse
    output = _oneShotUnionUse(expression, unpack)
  File "/share/sqlmap/lib/techniques/union/use.py", line 90, in _oneShotUnionUse
    page, headers, _ = Request.queryPage(payload, content=True, raise404=False)
  File "/share/sqlmap/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/connect.py", line 1322, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/share/sqlmap/lib/request/connect.py", line 798, in getPage
    processResponse(page, responseHeaders, code, status)
  File "/share/sqlmap/lib/request/basic.py", line 388, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", "".join(responseHeaders.headers), page)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 161: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-26 13:52
Duplicate of #3713

**Closed by stamparm** 2019-05-26 13:52 UTC
