### ISSUE TITLE
Unhandled exception (#22e486ae)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1928] opened 2016-06-06 04:09 UTC
```
sqlmap version: 1.0.6.24#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u ***************************************** --file-read D:\dtwww\include/config.php
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 147, in action
    conf.dumper.rFile(conf.dbmsHandler.readFile(conf.rFile))
  File "plugins/generic/filesystem.py", line 253, in readFile
    localFilePath = dataToOutFile(remoteFile, fileContent)
  File "lib/core/common.py", line 944, in dataToOutFile
    f.write(data)
  File "Python27/lib/codecs.py", line 706, in write
    return self.writer.write(data)
  File "Python27/lib/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 10: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-06-08 06:14
Duplicate of #1923 (fixed)

**Closed by stamparm** 2016-06-08 06:14 UTC
