### ISSUE TITLE
Unhandled exception (#bf9d2d96)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3021] opened 2018-04-02 02:29 UTC
```
Running version: 1.2.3.51#dev
Python version: 2.7.14
Operating system: Linux-3.18.31-perf-g8eb11cd-00002-gab1bae7-dirty-armv7l-with-libc
Command line: sqlmap.py -a -g *************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 536, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 1059, in heuristicCheckSqlInjection
    if Backend.getErrorParsedDBMSes():
  File "lib/core/common.py", line 450, in getErrorParsedDBMSes
    @staticmethod
  File "usr/lib/python2.7/bdb.py", line 51, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "usr/lib/python2.7/bdb.py", line 80, in dispatch_call
    self.user_call(frame, arg)
  File "usr/lib/python2.7/pdb.py", line 148, in user_call
    self.interaction(frame, None)
  File "usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "usr/lib/python2.7/pdb.py", line 279, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "usr/lib/python2.7/pdb.py", line 679, in do_run
    raise Restart
Restart
```

**Comment by stamparm** [comment] 2018-04-03 10:51
Duplicate of #3020 (fixed)

**Closed by stamparm** 2018-04-03 10:51 UTC
