### ISSUE TITLE
Unhandled exception (#99a5444b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4391] opened 2020-10-20 08:37 UTC
```
Running version: 1.4.10.9#dev
Python version: 3.7.7
Operating system: Windows-10-10.0.19041-SP0
Command line: sqlmap.py -m url.txt
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 301, in start
    for targetUrl, targetMethod, targetData, targetCookie, targetHeaders in kb.targets:
  File "lib/core/option.py", line 429, in __next__
    return self.next()
  File "lib/core/option.py", line 432, in next
    line = next(conf.bulkFile)
TypeError: 'str' object is not an iterator
```

**Comment by stamparm** [comment] 2020-10-20 10:19
Duplicate of #4383 (fixed)

**Closed by stamparm** 2020-10-20 10:19 UTC
