### ISSUE TITLE
union select long data error

### ISSUE THREAD

**Issue by sarahtarek8** [sqlmapproject/sqlmap#4114] opened 2020-02-12 11:54 UTC
when i try to get order by data or even pick like i get error 
on union but when i select specific data like where = i get data
wild card is not working with huge data 63 million row 
i tried --start worked fine but i cannot exclude thing 
i need to use --start --stop with i donot want pick zero values how to do 

ps when i try same target with time base attack i get data normally but in slow mode like 15 second a letter

**Comment by stamparm** [comment] 2020-02-17 11:36
1) You haven't filled anything from the Issue template. Not sure how to guess DBMS type. Also, not sure how to guess whether the problem is caused by sqlmap internal queries (i.e. for some DBMSes sqlmap forces `ORDER BY` because of non-deterministic query engine at the other end)
2) You haven't stated which options have you used in the first place, thus I don't know whether you've used `--dump`-alike or `--sql-query` to retrieve table content
3) I can only guess that in your kind of cases you should try to use `--force-partial`, currently hidden switch which will break down that whole dump into row by row data retrieval. Also, as I again have to guess, I am not sure whether your whole case is caused by the `ORDER BY` in the first place or by the size of retrieved content
4) Closing this all down as invalid. You can always try to do the stuff described in 3)

**Closed by stamparm** 2020-02-17 11:36 UTC
