### ISSUE TITLE
Unhandled exception (#aa9970ca)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2450] opened 2017-03-28 07:45 UTC
```
sqlmap version: 1.0.12.2#dev
Python version: 2.7.10
Operating system: nt
Command line: D:\sqlmap\sqlmap.pyc
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "usr/local/share/sqlmap/sqlmap.py", line 82, in main
TypeError: setPaths() takes exactly 1 argument (0 given)
```

**Comment by stamparm** [comment] 2017-03-28 13:15
Duplicate of #2368

**Closed by stamparm** 2017-03-28 13:15 UTC
