### ISSUE TITLE
Unhandled exception (#b551e0ea)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2197] opened 2016-09-28 23:24 UTC
```
sqlmap version: 1.0.9.41#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ******************************************************* --columns -D ******** --dump
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 334, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 593, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 369, in getChar
    if (timeBasedCompare or unexpectedCode) and not validateChar(idx, retVal):
  File "lib/techniques/blind/inference.py", line 217, in validateChar
    warnMsg = "detected HTTP code '%d' in validation phase is differing from expected '%d'" % (threadData.lastCode, kb.injection.data[kb.technique].trueCode)
TypeError: %d format: a number is required, not NoneType
```

**Comment by stamparm** [comment] 2016-09-29 00:04
Duplicate of #2192 (fixed)

**Closed by stamparm** 2016-09-29 00:04 UTC
