### ISSUE TITLE
Unhandled exception (#7903ec9e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1533] opened 2015-11-12 18:11 UTC
```
sqlmap version: 1.0-dev-nongit-20150901
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u ****************************************************************** --dbs
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 100, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 625, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 106, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "share/sqlmap/plugins/generic/databases.py", line 121, in getDbs
    count = inject.getValue(query, union=False, error=False, expected=EXPECTED.INT, charsetType=CHARSET_TYPE.DIGITS)
  File "share/sqlmap/lib/request/inject.py", line 437, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "share/sqlmap/lib/request/inject.py", line 279, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "share/sqlmap/lib/request/inject.py", line 127, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "share/sqlmap/lib/request/inject.py", line 99, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "share/sqlmap/lib/techniques/blind/inference.py", line 532, in bisection
    val = getChar(index, asciiTbl)
  File "share/sqlmap/lib/techniques/blind/inference.py", line 259, in getChar
    forgedPayload = safeStringFormat(payload, (expressionUnescaped, idx, posValue))
  File "share/sqlmap/lib/core/common.py", line 1627, in safeStringFormat
    raise Exception("wrong number of parameters during string formatting")
Exception: wrong number of parameters during string formatting
```

**Comment by stamparm** [comment] 2015-11-13 08:24
Duplicate of #1463 (user has to update)

**Closed by stamparm** 2015-11-13 08:24 UTC
