### ISSUE TITLE
Unhandled exception (#91ba0beb)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1905] opened 2016-05-26 09:31 UTC
```
sqlmap version: 1.0.5.39#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u *********************************************************** --sqlmap
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1369, in checkConnection
    page, headers = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1109, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 681, in getPage
    processResponse(page, responseHeaders)
  File "lib/request/basic.py", line 331, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None)
  File "lib/request/basic.py", line 131, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 41, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 1904, in parseXmlFile
    parse(stream, handler)
  File "Python27/lib/xml/sax/__init__.py", line 30, in parse
    parser = make_parser()
  File "Python27/lib/xml/sax/__init__.py", line 81, in make_parser
    return _create_parser(parser_name)
  File "Python27/lib/xml/sax/__init__.py", line 106, in _create_parser
    return drv_module.create_parser()
  File "Python27/lib/xml/sax/expatreader.py", line 421, in create_parser
    return ExpatParser(*args, **kwargs)
  File "Python27/lib/xml/sax/expatreader.py", line 91, in __init__
    xmlreader.IncrementalParser.__init__(self, bufsize)
  File "Python27/lib/xml/sax/xmlreader.py", line 113, in __init__
    XMLReader.__init__(self)
  File "Python27/lib/xml/sax/xmlreader.py", line 25, in __init__
    self._cont_handler = handler.ContentHandler()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by stamparm** [comment] 2016-05-26 13:34
Duplicate of #1900

**Closed by stamparm** 2016-05-26 13:34 UTC
