### ISSUE TITLE
Unhandled exception (#9a9a9305)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4621] opened 2021-03-29 17:01 UTC
```
Running version: 1.4.12.7#dev
Python version: 2.7.16
Operating system: Darwin-19.6.0-x86_64-i386-64bit
Command line: sqlmap.py -u *************************************************************************** --batch
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 558, in start
    check = checkDynParam(place, parameter, value)
  File "lib/controller/checks.py", line 1183, in checkDynParam
    dynResult = Request.queryPage(payload, place, raise404=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1413, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 872, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 398, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (getUnicode(_http_client.HTTPConnection._http_vsn_str), getUnicode(code or ""), getUnicode(status or ""), getUnicode("".join(responseHeaders.headers if responseHeaders else [])), getUnicode(page))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 8: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2021-03-29 20:14
Duplicate of #4465 (fixed)

**Closed by stamparm** 2021-03-29 20:14 UTC
