### ISSUE TITLE
Unhandled exception (#96504a25)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2181] opened 2016-09-24 09:23 UTC
```
sqlmap version: 1.0.9.24#dev
Python version: 2.7.9
Operating system: nt
Command line: sqlmap.py -r 2.txt --tamper=space2mssqlblank --current-user
Technique: STACKED
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 61, in action
    conf.dumper.currentUser(conf.dbmsHandler.getCurrentUser())
  File "plugins/generic/users.py", line 66, in getCurrentUser
    kb.data.currentUser = unArrayizeValue(inject.getValue(query))
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 157, in _goInferenceProxy
    _, _, _, _, _, expressionFieldsList, expressionFields, _ = agent.getFields(expression)
  File "lib/core/agent.py", line 532, in getFields
    if re.search("\A\w+\(.*\)", fieldsToCastStr, re.I) or (fieldsSelectCase and "WHEN use" not in query) or fieldsSubstr:
  File "Python27/lib/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2016-09-26 09:06
Duplicate of #2176 (fixed). Please update

**Closed by stamparm** 2016-09-26 09:06 UTC
