### ISSUE TITLE
Unhandled exception (#f8bcdfa7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4587] opened 2021-02-22 10:37 UTC
```
Running version: 1.5.1.7#dev
Python version: 2.7.18
Operating system: Linux-5.9.0-kali1-amd64-x86_64-with-debian-****-rolling
Command line: /usr/bin/sqlmap -u ************************************************* --technique=BEQUS --random-agent --level=2 --risk=3 --skip-waf --current-user --is-dba --exclude-sysdbs --dbs --time-sec=2 --banner --parse-errors --thread=3 --ignore-code=404,400,500,403,408 --output-dir=/home/****/Desktop/sqlmap
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 216, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 703, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 33, in action
    setHandler()
  File "/share/sqlmap/lib/controller/handler.py", line 173, in setHandler
    if conf.forceDbms == dbms or handler.checkDbms():
  File "/share/sqlmap/plugins/dbms/mysql/fingerprint.py", line 172, in checkDbms
    self.getBanner()
  File "/share/sqlmap/plugins/generic/enumeration.py", line 59, in getBanner
    bannerParser(kb.data.banner)
  File "/share/sqlmap/lib/parse/banner.py", line 114, in bannerParser
    parseXmlFile(xmlfile, handler)
  File "/share/sqlmap/lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/lib/python2.7/xml/sax/expatreader.py", line 336, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/share/sqlmap/lib/parse/handler.py", line 68, in startElement
    if self._techVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-02-22 21:45
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-02-22 21:45 UTC
