### ISSUE TITLE
Unhandled exception (#ad6a7eeb)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3523] opened 2019-03-07 07:10 UTC
```
Running *******: 1.3.3.10#dev
****** *******: 2.7.14
Operating system: **********************
******* line: sqlmap.py *** cartid=1 cfm?
Technique: ****
Back-end DBMS: ****
```
```
Traceback ***** recent call last):
  File "sqlmap.py", line 167, in main
    start()
  File ************************* line 53, in _
    result = f(*args, **kwargs)
  File ******************************* line 411, in start
    if *** ****************************************** ** *** checkString() ** *** checkRegexp():
  File *************************** line 1571, in ***************
    page, headers, _ = ******************************* ***********************
  File ************************* line 53, in _
    result = f(*args, **kwargs)
  File ************************* line 1280, in queryPage
    page, headers, **** = ************************ get=get, ********** ************** ************** ua=ua, referer=referer, ********** silent=silent, auxHeaders=auxHeaders, ****************** raise404=raise404, *******************************
  File ************************* line 608, in getPage
    ************************** "%s%s\r\n\r\n%s" % ************* *********** (page ** "")[:MAX_CONNECTION_CHUNK_SIZE]), start, time.time())
Uni****De****Err**: 'ascii' ****c can't de**** byte 0xc3 in ******** 293: **dinal *** in range(128)
```

**Comment by stamparm** [comment] 2019-03-07 13:56
Duplicate of #3522

**Closed by stamparm** 2019-03-07 13:56 UTC
