### ISSUE TITLE
a error from --common-tables by using newest version

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3374] opened 2018-11-18 09:33 UTC
```
[17:26:52] [INFO] tried 232/3316 items (7%)

[17:26:5217:26:52] [DEBUG] [] performed 10 queries in 0.66 seconds
[DEBUG17:26:52] performed 10 queries in 0.67 seconds
] [INFO

[] tried 234/3316 items (7%)17:26:52] [DEBUG] performed 10 queries in 0.67 seconds
17:26:52] [

[17:26:52INFO] [DEBUG] tried 235/3316 items (7%)] performed 10 queries in 0.68 seconds
```

**Comment by stamparm** [comment] 2018-11-19 08:32
Unable to reproduce. Tried with both `-v 3 --threads=...` and `-v 3`. Also, it is quite strange that you don't have `[PAYLOAD]` lines while using `-v 3`. Anyway, closing this down as unreproducible.

**Closed by stamparm** 2018-11-19 08:32 UTC
Labels: unreproducible

**Comment by huitc** [comment] 2018-12-14 03:12
https://github.com/sqlmapproject/sqlmap/issues/3397#issuecomment-445514739

**Comment by stamparm** [comment] 2018-12-14 09:42
@huitc I have a feeling that in those cases you've run couple of parallel sqlmap instances in same terminal. I can't help you there.

**Comment by stamparm** [comment] 2018-12-14 09:46
@huitc please retry it now. I've potentially found a "problem"
