### ISSUE TITLE
Unhandled exception (#3e0a1a52)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3751] opened 2019-06-12 04:35 UTC
```
Running version: 1.3.5.80#dev
Python version: 3.6.8
Operating system: Windows-10-10.0.17134-SP0
Command line: sqlmap.py --risk 3 --level 5 --batch --dump-all -v 3 --threads 8 -u *********************************************
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 675, in start
    action()
  File "lib/controller/action.py", line 165, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 480, in dumpAll
    self.getTables()
  File "plugins/generic/databases.py", line 417, in getTables
    kb.data.cachedTables[db] = sorted(tables) if tables else tables
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by stamparm** [comment] 2019-06-13 09:03
Duplicate of #3674 (patched)

**Closed by stamparm** 2019-06-13 09:03 UTC
