### ISSUE TITLE
Unhandled exception (#221f9466)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3750] opened 2019-06-11 13:17 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.16
Operating system: Windows-10-10.0.17134
Command line: sqlmap.py -u ********************************* --os-shell
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 204, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 84, in osShell
    self.shell()
  File "lib/takeover/abstraction.py", line 161, in shell
    self.runCmd(command)
  File "lib/takeover/abstraction.py", line 100, in runCmd
    conf.dumper.string("command standard output", output)
  File "lib/core/dump.py", line 137, in string
    self._write("%s:\n---\n%s\n---" % (header, _))
  File "lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self._write(text[start:end])
  File "thirdparty/colorama/ansitowin32.py", line 182, in _write
    self.wrapped.write(text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 82: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-06-13 09:00
Duplicate of #3700

**Closed by stamparm** 2019-06-13 09:00 UTC
