### ISSUE TITLE
Unhandled exception (#10fb9819)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2492] opened 2017-04-19 15:19 UTC
```
sqlmap version: 1.1.4.39#dev
Python version: 2.7.13
Operating system: nt
Command line: SQLmap/SQLmap.py -u **************************************** --dbs --risk=3 --level=3 --tamper=space2comment
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "SQLmap.py", line 150, in main
    start()
  File "lib/controller/controller.py", line 287, in start
    parseTargetUrl()
  File "lib/core/common.py", line 1447, in parseTargetUrl
    conf.httpHeaders = filter(lambda key, value: key != HTTP_HEADER.REFERER, conf.httpHeaders)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by stamparm** [comment] 2017-04-19 21:27
Duplicate of #2491 (fixed)

**Closed by stamparm** 2017-04-19 21:27 UTC
