### ISSUE TITLE
Unhandled exception (#5cc226a9)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3701] opened 2019-05-24 15:26 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.13
Operating system: Windows-7-6.1.7601-SP1
Command line: sqlmap.py -u ****************************************** -D ****** --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 453, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 605, in dbTableValues
    self._write("| %s%s" % (value, blank), newline=False, console=console)
  File "lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self._write(text[start:end])
  File "thirdparty/colorama/ansitowin32.py", line 182, in _write
    self.wrapped.write(text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 6: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-24 20:51
Duplicate of #3700

**Closed by stamparm** 2019-05-24 20:51 UTC
