### ISSUE TITLE
Unhandled exception (#50df72b5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3786] opened 2019-06-29 12:08 UTC
```
Running version: 1.3.5.77#dev
Python version: 3.7.3
Operating system: Darwin-18.6.0-x86_64-i386-64bit
Command line: sqlmap.py -u ************************************************* --data ************* --chunked --random-agent
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 420, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1589, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1314, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 500, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 523, in open
    req = meth(req)
  File "lib/request/chunkedhandler.py", line 17, in _http_request
    host = request.get_host()
AttributeError: 'Request' object has no attribute 'get_host'
```

**Comment by khalednassar702** [comment] 2019-06-29 15:30
run it using python 2.7

**Comment by stamparm** [comment] 2019-07-01 08:05
Duplicate of #3764 (patched)

**Closed by stamparm** 2019-07-01 08:05 UTC
