### ISSUE TITLE
Unhandled exception (#042d517b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1590] opened 2015-12-09 07:16 UTC
```
sqlmap version: 1.0-dev-nongit-20151019
Python version: 2.7.3
Operating system: nt
Command line: sqlmap.py --pickled-options Y29zCnN5c3RlbQooUydkaXInCnRSLg==
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 86, in main
    initOptions(cmdLineOptions)
  File "lib/core/option.py", line 2507, in initOptions
    _mergeOptions(inputOptions, overrideOptions)
  File "lib/core/option.py", line 2089, in _mergeOptions
    if inputOptions.configFile:
AttributeError: 'int' object has no attribute 'configFile'
```

**Comment by stamparm** [comment] 2015-12-09 08:51
Duplicate of #1592

**Closed by stamparm** 2015-12-09 08:51 UTC
