### ISSUE TITLE
sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, --

### ISSUE THREAD

**Issue by Abdullahki** [sqlmapproject/sqlmap#4183] opened 2020-04-30 16:34 UTC
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev]
 - Installation method [e.g. git]
 - Operating system: [e.g. Microsoft Windows 10]
 - Python version [e.g. 3.5.2]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by fgeek** [comment] 2020-05-01 11:13
@Abdullahki This bug report has zero information. You are probably missing required and mandatory command line options.

**Comment by stamparm** [comment] 2020-05-02 11:45
Duplicate of #2470, #2135, #2571 and #3048

**Closed by stamparm** 2020-05-02 11:45 UTC
Labels: bug report

**Comment by jockerkkk** [comment] 2020-05-14 14:18
![sqltlg](https://user-images.githubusercontent.com/65350931/81945508-94c89480-95d4-11ea-9f86-05402f49e95f.png)

**Comment by stamparm** [comment] 2020-05-14 15:01
@jockerkkk something is seriously wrong with your environment

![3333](https://user-images.githubusercontent.com/921555/81950631-78445080-9604-11ea-896d-e329880d1a06.png)

**Comment by stamparm** [comment] 2020-05-14 15:06
@jockerkkk The only way how to reproduce this was the usage of special Unicode character `“−” (U+2212)` (i.e. https://www.compart.com/en/unicode/U+2212)

![5555](https://user-images.githubusercontent.com/921555/81951204-294aeb00-9605-11ea-92e9-966c7ed4dff1.png)


This basically means that you most probably copy-pasted that same command line from some random site. I've stuff and I really don't know how to be polite in this kind of situations. I would now write something rude, but will restrain myself

I am marking this issue with FUBAR as there is no other better label to describe it

**Comment by jockerkkk** [comment] 2020-05-14 15:45
no matter which command is used, the same message always appears
sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, --list-tampers, --wizard, --update, --purge or --dependencies). Use -h for basic and -hh for advanced help

**Comment by jockerkkk** [comment] 2020-05-14 16:04
![15894722202873326702294857080100](https://user-images.githubusercontent.com/65350931/81957774-71f1ac80-95e3-11ea-80e0-1c444fdec4e2.jpg)

**Comment by stamparm** [comment] 2020-05-14 16:18
Can you retry with latest revision?

**Comment by jockerkkk** [comment] 2020-05-14 16:23
![15894733480938096394392737137205](https://user-images.githubusercontent.com/65350931/81959613-1c6acf00-95e6-11ea-9593-fa9ce05c2eb7.jpg)

**Comment by stamparm** [comment] 2020-05-14 16:26
Latest version of sqlmap is not the one you run. Do you know how to get latest version/revision?

**Comment by jockerkkk** [comment] 2020-05-14 16:34
![1589473916821846102928040574123](https://user-images.githubusercontent.com/65350931/81960464-60aa9f00-95e7-11ea-93ac-3927ebd37d59.jpg)

**Comment by jockerkkk** [comment] 2020-05-14 16:36
I already cloned and i also downloaded the updated zip file, and it keeps giving the same error

**Comment by stamparm** [comment] 2020-05-14 16:37
Give me screenshot with version 1.4.5.22#dev

**Comment by jockerkkk** [comment] 2020-05-14 16:40
![15894744200514557234436694727504](https://user-images.githubusercontent.com/65350931/81961251-7e2c3880-95e8-11ea-9a7a-6a66085960b0.jpg)

**Comment by jockerkkk** [comment] 2020-05-14 16:42
The version being used on my computer

**Comment by jockerkkk** [comment] 2020-05-14 17:04
![20200514_140310](https://user-images.githubusercontent.com/65350931/81963687-d0bb2400-95eb-11ea-832b-b6ac8fe96cea.jpg)

**Comment by stamparm** [comment] 2020-05-14 17:10
Please, don't be offended, but I believe that you are either trolling or we have serious communication issues. I said for you to send me a screenshot of a run with 1.4.5.22 and you send me a screenshot of a zip file. I won't respond to this issue any more
