### ISSUE TITLE
Unhandled exception (#a6e48246)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4843] opened 2021-10-04 12:56 UTC
```
Running version: 1.5.9.7#dev
Python version: 2.7.18
Operating system: Linux-5.10.0-kali9-amd64-x86_64-with-debian-kali-rolling
Command line: /usr/bin/sqlmap -u ******************************** --data ************************** -p uname --level=5 --risk=3 --batch --random-agent --batch --threads 5 --no-cast --sql-shell
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 216, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 703, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
  File "/share/sqlmap/plugins/generic/custom.py", line 117, in sqlShell
    output = self.sqlQuery(query)
  File "/share/sqlmap/plugins/generic/custom.py", line 62, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "/share/sqlmap/lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "/share/sqlmap/lib/request/inject.py", line 308, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "/share/sqlmap/lib/request/inject.py", line 154, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "/share/sqlmap/lib/request/inject.py", line 121, in _goInference
    length = queryOutputLength(injExpression, payload)
  File "/share/sqlmap/lib/techniques/blind/inference.py", line 728, in queryOutputLength
    count, length = bisection(payload, lengthExprUnescaped, charsetType=CHARSET_TYPE.DIGITS)
  File "/share/sqlmap/lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "/share/sqlmap/lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected." % threadData.lastCode
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-10-04 16:20
Duplicate of #4824 (fixed)

**Closed by stamparm** 2021-10-04 16:20 UTC
Labels: duplicate
