### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by ihacku** [sqlmapproject/sqlmap#1110] opened 2015-01-14 02:36 UTC
sqlmap version 1.0-dev-06ff8b3
python version Python 2.7.8
```
Traceback (most recent call last):
  File "./sqlmap.py", line 187, in <module>
    main()
  File "./sqlmap.py", line 156, in main
    shutil.rmtree(tempfile.tempdir, ignore_errors=True)
  File "/usr/local/lib/python2.7/shutil.py", line 228, in rmtree
    if os.path.islink(path):
  File "/usr/local/lib/python2.7/posixpath.py", line 142, in islink
    st = os.lstat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

file content
```
POST /url?action=save HTTP/1.1

Origin: http://site:80

Content-Length: 740

Accept-Language: zh-CN,zh;q=0.8

Accept-Encoding: gzip,deflate

Host: site:80

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

Connection: close

Referer: http://blabla

Cache-Control: max-age=0

Cookie: DvForum=UserID=28&usercookies=0&userclass=%B9%DC%C0%ED%D4%B1&username=%c4%c7%cb%ad%cb%ad&password=lalala&userhidden=2&StatUserID=lalala; 

boardid=1179&topicid=*&announceid=3585149&atype=0&a1=0&a2=0&atitle=sa&acodestr=8342&acontent=asd
```

**Comment by stamparm** [comment] 2015-01-14 04:17
Duplicate of #1106

**Closed by stamparm** 2015-01-14 04:17 UTC
