### ISSUE TITLE
Cant use sqlmap command outside own folder

### ISSUE THREAD

**Issue by moralitross** [sqlmapproject/sqlmap#5371] opened 2023-03-24 12:50 UTC
I cant use the command outside the sqlmap-dev folder I intsalled with the git clone command, neither by downloading the zip file, I have installed it in local disk C and program files but neither work. Im getting some error that i asume its a bug inside sqlmap, cause im replicating everything from random sources and still getting the warning and sqlmap doesnt do anything

**Comment by moralitross** [comment] 2023-03-24 13:38
im copying a request from burp into a txt file and it always says when sqlmap -r request.txt --dbs or sqlmap -u lnik --forms --threads 10 that it cant access the url or it doesnt find correct parameters, i have activated the http/2 in burp but i dont know what it is happening

**Comment by R-Rothrock** [comment] 2023-03-24 13:58
The output said it best:

> [14:39:43] [WARNING] if the problem persists please check that the provided target URL is reachable. In case that it is, you can try to rerun with switch '--random-agent' and/or proxy switches ('--proxy', '--proxy-file'...)

**Comment by moralitross** [comment] 2023-03-24 14:18
i will try, but im also connected to a vpn, could it be possible that the vpn is somehow interfiering?

**Comment by R-Rothrock** [comment] 2023-03-24 15:38
It’s possible, but this is no longer in the scope of the issue. You’ll have to troubleshoot by yourself. Best of luck.

**Comment by stamparm** [comment] 2023-03-24 21:39
Duplicate of #5372

**Closed by stamparm** 2023-03-24 21:39 UTC
Labels: bug report
