### ISSUE TITLE
Unhandled exception (#78a39b83)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2193] opened 2016-09-28 03:12 UTC
```
sqlmap version: 1.0.9.41#dev
Python version: 2.6.6
Operating system: posix
Command line: sqlmap.py -u ***************************************************************************************** --data=__VIEWSTATE=%2FwEPDwUKLTkxNTM3NzMzMGRkDDGg884YgdNEeEocIEt1Xx1PB437V0XOv0GG89%2FZCIA%3D&__VIEWSTATEGENERATOR=D23E6DBC&__EVENTVALIDATION=%2FwEdAAMep1aS5etb8LQhoJvwQtt3S17Zlia%2FUgBYAr3%2F0b4e8tTv9lpKmw7ne0TMjbLt7JyKycfSSfxwUWfqwOHyukD9YF5RVEcrO16mWMKT0ndSZA%3D%3D&txtNroCuenta=222222222222&btnAceptar=Aceptar --dbms=mssql --random-agent --privileges -p txtNroCuenta --risk=3 --level=3 -v3 --skip-waf --no-cast
Technique: TIME
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 85, in action
    conf.dumper.userSettings("database management system users privileges", conf.dbmsHandler.getPrivileges(), "privilege", CONTENT_TYPE.PRIVILEGES)
  File "plugins/dbms/mssqlserver/enumeration.py", line 49, in getPrivileges
    users = self.getUsers()
  File "plugins/generic/users.py", line 120, in getUsers
    count = inject.getValue(query, union=False, error=False, expected=EXPECTED.INT, charsetType=CHARSET_TYPE.DIGITS)
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 593, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 369, in getChar
    if (timeBasedCompare or unexpectedCode) and not validateChar(idx, retVal):
  File "lib/techniques/blind/inference.py", line 217, in validateChar
    warnMsg = "detected HTTP code '%d' in validation phase is differing from expected '%d'" % (threadData.lastCode, kb.injection.data[kb.technique].trueCode)
TypeError: %d format: a number is required, not NoneType
```

**Comment by stamparm** [comment] 2016-09-28 07:55
Duplicate of #2192 (fixed)

**Closed by stamparm** 2016-09-28 07:55 UTC
