### ISSUE TITLE
Unhandled exception (#c31c3504)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5513] opened 2023-09-01 06:09 UTC
```
Running version: 1.7.7.2#dev
Python version: 3.11.4
Operating system: Linux-6.3.0-kali1-amd64-x86_64-with-glibc2.37
Command line: /usr/bin/sqlmap -u ************************************************************************************************* -p category_id --risk 3 --level 5 --random-agent --hex --cookie ************************************************************ --threads 1 --time-sec 2 --tamper=space2comment.py -D ****************** --dump
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 222, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/controller/controller.py", line 732, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 163, in action
    conf.dbmsHandler.dumpTable()
  File "/share/sqlmap/plugins/generic/entries.py", line 251, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/request/inject.py", line 451, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/techniques/error/use.py", line 339, in errorUse
    if isNumPosStrValue(count):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/sqlmap/lib/core/common.py", line 3185, in isNumPosStrValue
    return ((hasattr(value, "isdigit") and value.isdigit() and int(value) > 0) or (isinstance(value, int) and value > 0)) and int(value) < MAX_INT
                                                               ^^^^^^^^^^
ValueError: Exceeds the limit (4300 digits) for integer string conversion: value has 23420 digits; use sys.set_int_max_str_digits() to increase the limit
```

**Comment by stamparm** [comment] 2023-09-03 06:15
Duplicate of #5510

**Closed by stamparm** 2023-09-03 06:15 UTC
