### ISSUE TITLE
Unhandled exception (#c95bfb30)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2126] opened 2016-08-24 05:53 UTC
```
sqlmap version: 1.0.8.20#dev
Python version: 2.7.12
Operating system: nt
Command line: C:\Python27\sqlmap\sqlmap.pyc
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 87, in main
    def checkEnvironment():
TypeError: setPaths() takes exactly 1 argument (0 given)
```

**Comment by stamparm** [comment] 2016-08-25 00:45
Duplicate of #2120

**Closed by stamparm** 2016-08-25 00:45 UTC
