### ISSUE TITLE
Unhandled exception (#c253a243)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1493] opened 2015-10-27 14:55 UTC
```
sqlmap version: 1.0-dev-nongit-20151027
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -r ~æ¡é¢/header.txt
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 91, in main
    init()
  File "share/sqlmap/lib/core/option.py", line 2479, in init
    _setRequestFromFile()
  File "share/sqlmap/lib/core/option.py", line 502, in _setRequestFromFile
    conf.requestFile = safeExpandUser(conf.requestFile)
  File "share/sqlmap/lib/core/common.py", line 1586, in safeExpandUser
    retVal = os.path.expanduser(filepath)
  File "lib/python2.7/posixpath.py", line 275, in expanduser
    pwent = pwd.getpwnam(path[1:i])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2015-10-28 09:12
Duplicate of #1347 (fixed)

**Closed by stamparm** 2015-10-28 09:12 UTC
