### ISSUE TITLE
Unhandled exception (#bebea546)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5231] opened 2022-11-15 04:30 UTC
```
Running version: 1.6.9#stable
Python version: 3.12.0a1
Operating system: Windows-2016Server-10.0.14393-SP0
Command line: sqlmap.py -u ********************* --random-agent --time-sec 5 --fresh-queries --level 5 --risk 3 --threads 1 --dbs
Technique: UNION
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 589, in start
    injection = checkSqlInjection(place, parameter, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/controller/checks.py", line 713, in checkSqlInjection
    reqPayload, vector = unionTest(comment, place, parameter, value, prefix, suffix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/techniques/union/test.py", line 391, in unionTest
    validPayload, vector = _unionTestByCharBruteforce(comment, place, parameter, value, prefix, suffix)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/techniques/union/test.py", line 325, in _unionTestByCharBruteforce
    count = _findUnionCharCount(comment, place, parameter, value, prefix, suffix, where)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/techniques/union/test.py", line 106, in _findUnionCharCount
    found = _orderByTechnique(lowerCount, upperCount) if conf.uCols else _orderByTechnique()
                                                                         ^^^^^^^^^^^^^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/techniques/union/test.py", line 70, in _orderByTechnique
    if _orderByTest(1 if lowerCount is None else lowerCount) and not _orderByTest(randomInt() if upperCount is None else upperCount + 1):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/techniques/union/test.py", line 67, in _orderByTest
    page, headers, code = Request.queryPage(payload, place=place, content=True, raise404=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 1529, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 621, in getPage
    conn = _urllib.request.urlopen(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 518, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 535, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 495, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "lib/request/httpshandler.py", line 134, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 1347, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1296, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1342, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1291, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "lib/core/patch.py", line 61, in _send_output
    self.__send_output(*args, **kwargs)
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1051, in _send_output
    self.send(msg)
  File "/Users/*************/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 989, in send
    self.connect()
  File "lib/request/httpshandler.py", line 98, in connect
    _ = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=protocol)
        ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by stamparm** [comment] 2022-11-20 23:40
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5216 (fixed)

**Closed by stamparm** 2022-11-20 23:40 UTC
