### ISSUE TITLE
Unhandled exception (#8d65c631)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3301] opened 2018-10-16 13:52 UTC
```
Running version: 1.2.10.23#dev
Python version: 2.7.6
Operating system: Linux-4.9.120-c9-x86_64-with-******-14.04-trusty
Command line: sqlmap.py --sqlmap-shell
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 164, in main
    start()
  File "lib/core/decorators.py", line 34, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 403, in start
    setupTargetEnv()
  File "lib/core/target.py", line 759, in setupTargetEnv
    _resumeHashDBValues()
  File "lib/core/target.py", line 459, in _resumeHashDBValues
    _resumeDBMS()
  File "lib/core/target.py", line 489, in _resumeDBMS
    for aliases, _, _, _ in DBMS_DICT.values():
ValueError: need more than 3 values to unpack
```

**Comment by stamparm** [comment] 2018-10-16 17:34
Duplicate of #3303

**Closed by stamparm** 2018-10-16 17:34 UTC
