### ISSUE TITLE
Unhandled exception (#b8c8e5cd)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3013] opened 2018-03-28 12:41 UTC
```
Running version: 1.2.3.40#dev
Python version: 2.7.9
Operating system: Windows-2012Server-6.2.9200
Command line: sqlmap.py **************************************** --forms --risk=3 --level=5 --no-cast --random-agent -D *********** -T ************** -C ************************* --dump --dump-format=HTML
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 650, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 409, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 432, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 131, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 103, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 616, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 334, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "lib/request/connect.py", line 834, in queryPage
    logger.log(CUSTOM_LOGGING.PAYLOAD, safecharencode(payload.replace('\\', BOUNDARY_BACKSLASH_MARKER)).replace(BOUNDARY_BACKSLASH_MARKER, '\\'))
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by stamparm** [comment] 2018-04-03 10:57
Duplicate of #3017

**Closed by stamparm** 2018-04-03 10:57 UTC
Labels: bug, miscellaneous, normal
