### ISSUE TITLE
Unhandled exception (#900aa527)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3890] opened 2019-08-21 19:33 UTC
```
Running version: 1.3.7#pip
Python version: 3.7.3
Operating system: Windows-7-6.1.7601-SP1
Command line: C:\Python\Python37\Scripts\sqlmap -u ************************************************** --file-write h:\shell.aspx --file-des d:\web\shell.aspx --hex
Technique: BOOLEAN
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "/encodings/hex_codec.py", line 15, in hex_encode
    return (binascii.b2a_hex(input), len(input))
TypeError: a bytes-like object is required, not 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 683, in start
    action()
  File "lib/controller/action.py", line 201, in action
    conf.dbmsHandler.writeFile(conf.fileWrite, conf.fileDest, conf.fileWriteType)
  File "plugins/generic/filesystem.py", line 295, in writeFile
    written = self.stackedWriteFile(localFile, remoteFile, fileType, forceCheck)
  File "plugins/dbms/mssqlserver/filesystem.py", line 411, in stackedWriteFile
    self._stackedWriteFileDebugExe(tmpPath, localFile, localFileContent, remoteFile, fileType)
  File "plugins/dbms/mssqlserver/filesystem.py", line 220, in _stackedWriteFileDebugExe
    chunkName = self._updateDestChunk(localFileContent, tmpPath)
  File "plugins/dbms/mssqlserver/filesystem.py", line 67, in _updateDestChunk
    fileScrLines = self._dataToScr(fileContent, chunkName)
  File "plugins/dbms/mssqlserver/filesystem.py", line 48, in _dataToScr
    strLineChar = encodeHex(lineChar, binary=False)
  File "lib/core/convert.py", line 173, in encodeHex
    retVal = codecs.encode(value, "hex")
TypeError: encoding with 'hex' codec failed (TypeError: a bytes-like object is required, not 'int')
```

**Comment by stamparm** [comment] 2019-08-22 08:28
Duplicate of #3796 (patched)

**Closed by stamparm** 2019-08-22 08:28 UTC
