### ISSUE TITLE
Unhandled exception (#821d3143)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3665] opened 2019-05-15 10:47 UTC
```
Running version: 1.3.3.47#dev
Python version: 2.7.13
Operating system: Windows-10-10.0.17763
Command line: sqlmap.py -u ********************************************* -D *********** --os-shell
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 171, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 666, in start
    action()
  File "lib/controller/action.py", line 204, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 83, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 198, in initEnv
    self.webInit()
  File "lib/takeover/web.py", line 270, in webInit
    backdoorContent = decloak(os.path.join(paths.SQLMAP_SHELL_PATH, "backdoors", "backdoor.%s_" % self.webPlatform))
  File "extra/cloak/cloak.py", line 38, in decloak
    with open(inputFile, "rb") as f:
IOError: [Errno 2] No such file or directory: u'C:\\sqlmap\\shell\\backdoors\\backdoor.php_'
```

**Comment by stamparm** [comment] 2019-05-15 12:04
Duplicate of #3648 (patched)

**Closed by stamparm** 2019-05-15 12:04 UTC
