### ISSUE TITLE
Unhandled exception (#fb966c37)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1866] opened 2016-05-13 13:28 UTC
```
sqlmap version: 1.0-dev-nongit-201605130a89
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u *************************************** --form --dbms --level 3 --risk 3 --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 101, in main
    init()
  File "share/sqlmap/lib/core/option.py", line 2571, in init
    _findPageForms()
  File "share/sqlmap/lib/core/option.py", line 613, in _findPageForms
    if conf.url and not checkConnection():
  File "share/sqlmap/lib/controller/checks.py", line 1331, in checkConnection
    page, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "share/sqlmap/lib/request/connect.py", line 1095, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "share/sqlmap/lib/request/connect.py", line 487, in getPage
    page = decodePage(page, responseHeaders.get(HTTP_HEADER.CONTENT_ENCODING), responseHeaders.get(HTTP_HEADER.CONTENT_TYPE))
  File "share/sqlmap/lib/request/basic.py", line 303, in decodePage
    kb.pageEncoding = kb.pageEncoding or checkCharEncoding(getHeuristicCharEncoding(page))
  File "share/sqlmap/lib/request/basic.py", line 226, in getHeuristicCharEncoding
    retVal = detect(page)["encoding"]
  File "share/sqlmap/thirdparty/chardet/__init__.py", line 28, in detect
    u = universaldetector.UniversalDetector()
AttributeError: 'module' object has no attribute 'UniversalDetector'
```

**Comment by stamparm** [comment] 2016-05-13 13:43
Duplicate of #1812

**Closed by stamparm** 2016-05-13 13:43 UTC
