### ISSUE TITLE
Unhandled exception (#c141a8f4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1939] opened 2016-06-08 15:02 UTC
```
sqlmap version: 1.0.5.0#dev
Python version: 2.7.11+
Operating system: posix
Command line: /usr/bin/sqlmap -r request.txt --os-pwn
Technique: STACKED
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 115, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 625, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 163, in action
    conf.dbmsHandler.osPwn()
  File "share/sqlmap/plugins/generic/takeover.py", line 261, in osPwn
    self.pwn(goUdf)
  File "share/sqlmap/lib/takeover/metasploit.py", line 699, in pwn
    debugMsg += "with return code %s" % self._controlMsfCmd(self._msfCliProc, func)
  File "share/sqlmap/lib/takeover/metasploit.py", line 553, in _controlMsfCmd
    ready_fds = select([stdin_fd], [], [], 1)
error: (4, 'Interrupted system call')
```

**Comment by stamparm** [comment] 2016-06-10 15:44
Duplicate of #1822 (fixed)

**Closed by stamparm** 2016-06-10 15:44 UTC
