### ISSUE TITLE
Unhandled exception (#7d5d6e72)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2846] opened 2017-12-23 19:03 UTC
```
sqlmap version: 1.1.12.7#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u ****************************************************************************************** --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 399, in start
    checkWaf()
  File "lib/controller/checks.py", line 1328, in checkWaf
    retVal = Request.queryPage(place=PLACE.GET, value=value, getRatioValue=True, noteResponseTime=False, silent=True)[1] < IDS_WAF_CHECK_RATIO
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 468, in getPage
    conn = urllib2.urlopen(req)
  File "Python27/lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "Python27/lib/urllib2.py", line 435, in open
    response = meth(req, response)
  File "Python27/lib/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "Python27/lib/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "Python27/lib/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "Python27/lib/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), http, code, msg, hdrs, fp)
NameError: global name 'http' is not defined
```

**Comment by stamparm** [comment] 2017-12-24 03:05
Duplicate of #2844

**Closed by stamparm** 2017-12-24 03:05 UTC
