### ISSUE TITLE
Unhandled exception (#47a3bac5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4850] opened 2021-10-07 05:52 UTC
```
Running version: 1.5.9.7#dev
Python version: 3.8.10
Operating system: Windows-10-10.0.19042-SP0
Command line: sqlmap.py -u ****************************************** --sql-shell
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 117, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 62, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 221, in _goInferenceProxy
    count = _goInference(payload, countedExpression, charsetType=CHARSET_TYPE.DIGITS, firstChar=firstChar, lastChar=lastChar)
  File "lib/request/inject.py", line 126, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected." % threadData.lastCode
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-10-07 21:31
Duplicate of #4824 (fixed)

**Closed by stamparm** 2021-10-07 21:31 UTC
