### ISSUE TITLE
Unhandled exception (#51c1bee4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3476] opened 2019-02-08 22:24 UTC
```
Running version: 1.3.2.5#dev
Python version: 2.7.15
Operating system: Linux-3.4.113-g157e2ed-armv7l-with-libc
Command line: sqlmap.py -u ****************************************************************************** -D ********* -T ******** -C *********** --dump
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    init()
  File "lib/core/option.py", line 2538, in init
    _createHomeDirectories()
  File "lib/core/option.py", line 1445, in _createHomeDirectories
    warnMsg += "'%s' (%s). " % (directory, getUnicode(ex))
NameError: global name 'getUnicode' is not defined
```

**Comment by stamparm** [comment] 2019-02-09 14:01
Duplicate of #3469 (fixed)

**Closed by stamparm** 2019-02-09 14:01 UTC
