### ISSUE TITLE
Unhandled exception (#e4251ce2)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2993] opened 2018-03-17 10:52 UTC
```
Running version: 1.2.3.7#dev
Python version: 2.7.14
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py -r anodaz.txt --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 537, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 1009, in heuristicCheckSqlInjection
    page, _, _ = Request.queryPage(payload, place, content=True, raise404=False)
  File "lib/request/connect.py", line 938, in queryPage
    auxHeaders[value.split(',')[0]] = value.split(',', 1)[1]
IndexError: list index out of range
```

**Comment by stamparm** [comment] 2018-03-18 23:10
Duplicate of #2969 (fixed)

**Closed by stamparm** 2018-03-18 23:10 UTC
