### ISSUE TITLE
Unhandled exception (#20d9c9b1)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1132] opened 2015-01-23 14:10 UTC
```
sqlmap version: 1.0-dev-nongit-20150123
Python version: 2.7.2
Operating system: posix
Command line: sdl --disable-col -u sqlmap -u âhttp://www.sdzzxd.com/login.aspâ âforms -v 1 --timeout=30 --retries=3 --threads=1 --risk=1 --level=1 --technique=BEUSTQ
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/sqlmap.py", line 91, in main
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 2323, in init
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/common.py", line 1246, in parseTargetUrl
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/encodings/idna.py", line 164, in encode
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/encodings/idna.py", line 95, in ToASCII
LookupError: unknown encoding: punycode
```

**Comment by stamparm** [comment] 2015-01-23 15:45
Duplicate of #1011

**Closed by stamparm** 2015-01-23 15:45 UTC
