### ISSUE TITLE
Unhandled exception (#1e76a18d)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3454] opened 2019-01-28 03:43 UTC
```
Running version: 1.3.1.75#dev
Python version: 2.7.15+
Operating system: Linux-4.19.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap -u ************************************************************ --dump -D ********* --threads=10 --batch --output-dir=./sqlserverdump --dump-format=SQLITE
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 166, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 41, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 666, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "/share/sqlmap/plugins/generic/entries.py", line 203, in dumpTable
    value = inject.getValue(query, blind=False, time=False, dump=True) or ""
  File "/share/sqlmap/lib/core/decorators.py", line 41, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/inject.py", line 422, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "/share/sqlmap/lib/techniques/error/use.py", line 328, in errorUse
    count = unArrayizeValue(_oneShotErrorUse(countedExpression, countedExpressionFields))
  File "/share/sqlmap/lib/techniques/error/use.py", line 66, in _oneShotErrorUse
    retVal = hashDBRetrieve(expression, checkConf=True)
  File "/share/sqlmap/lib/core/common.py", line 4371, in hashDBRetrieve
    retVal = conf.hashDB.retrieve(_, unserialize) if kb.resumeValues and not (checkConf and any((conf.flushSession, conf.freshQueries))) else None
  File "/share/sqlmap/lib/utils/hashdb.py", line 82, in retrieve
    for row in self.cursor.execute("SELECT value FROM storage WHERE id=?", (hash_,)):
OperationalError: unable to open database file
```

**Comment by stamparm** [comment] 2019-01-29 11:40
Duplicate of #3455

**Closed by stamparm** 2019-01-29 11:40 UTC
