### ISSUE TITLE
Unhandled exception (#e93dcc69)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5226] opened 2022-11-05 09:20 UTC
```
Running version: 1.6.10.4#dev
Python version: 3.10.2
Operating system: Windows-10-10.0.17763-SP0
Command line: sqlmap.py -u *********************************************** --forms --risk=3 --level=4 --random-agent -v4 --no-cast --thread=10 --batch D master --tables
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 115, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/dbms/mssqlserver/enumeration.py", line 114, in getTables
    value = [safeSQLIdentificatorNaming(unArrayizeValue(_), True) for _ in value]
  File "plugins/dbms/mssqlserver/enumeration.py", line 114, in <listcomp>
    value = [safeSQLIdentificatorNaming(unArrayizeValue(_), True) for _ in value]
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-11-07 10:39
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5202 (fixed)

**Closed by stamparm** 2022-11-07 10:39 UTC
