### ISSUE TITLE
Unhandled exception (#d0185006)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3565] opened 2019-04-02 11:27 UTC
```
Running version: 1.3.3.44#dev
Python version: 2.7.16
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=************** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql,mssql,oracle,sibase,sqlite,pgsql,firebird,access,maxdb --technique=EUBSTQ --random-agent --is-dba --exclude-sysdbs --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 164, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 29, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
    from plugins.dbms.mssqlserver.enumeration import Enumeration
  File "plugins/dbms/mssqlserver/enumeration.py", line 32, in <module>
    from plugins.generic.enumeration import Enumeration as GenericEnumeration
  File "plugins/generic/enumeration.py", line 20, in <module>
    from plugins.generic.entries import Entries
  File "plugins/generic/entries.py", line 46, in <module>
    from lib.utils.hash import attackDumpedTable
  File "lib/utils/hash.py", line 88, in <module>
    from lib.core.wordlist import Wordlist
  File "lib/core/wordlist.py", line 6
    """
Copyright (c) 2006-2019 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""
       
                                                              
                                             
  ^
SyntaxError: I/O error while reading
```

**Comment by stamparm** [comment] 2019-04-03 09:21
Duplicate of #3564

**Closed by stamparm** 2019-04-03 09:21 UTC
