### ISSUE TITLE
Unhandled exception (#af844f6a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1153] opened 2015-02-03 07:35 UTC
```
sqlmap version: 1.0-dev-nongit-20150203
Python version: 2.7.9
Operating system: nt
Command line: sqlmap.py -u ****************************************************** None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 77, in main
    cmdLineOptions.update(cmdLineParser().__dict__)
  File "lib/parse/cmdline.py", line 791, in cmdLineParser
    for arg in (sys.argv if not IS_WIN else shlex.split(" ".join(sys.argv))):
  File "Python27/lib/shlex.py", line 279, in split
    return list(lex)
  File "Python27/lib/shlex.py", line 269, in next
    token = self.get_token()
  File "Python27/lib/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "Python27/lib/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by stamparm** [comment] 2015-02-03 09:07
Duplicate of #1148

**Closed by stamparm** 2015-02-03 09:07 UTC
