### ISSUE TITLE
Unhandled exception (#5236213f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1949] opened 2016-06-13 04:49 UTC
```
sqlmap version: 1.0.5.122#dev
Python version: 2.7.3
Operating system: nt
Command line: sqlmap.py -u *********************************************************************************** --level=5 --risk=3 --dbs
Technique: BOOLEAN
Back-end DBMS: Firebird (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 106, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 120, in getDbs
    query = rootQuery.blind.count
AttributeError: 'DictObject' object has no attribute 'blind'
```

**Comment by stamparm** [comment] 2016-06-13 12:28
Duplicate of #1747

**Closed by stamparm** 2016-06-13 12:28 UTC
