### ISSUE TITLE
Unhandled exception (#9a309988)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1816] opened 2016-04-19 02:00 UTC
```
sqlmap version: 1.0-dev-nongit-201512160a8c
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ************************************************* --data=********************************************************** --level 3 --risk 3 --dbms=sybase -D **** -T E7DT_02_ADMINDIV --dump
Technique: UNION
Back-end DBMS: Sybase (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 127, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
TypeError: getColumns() got an unexpected keyword argument 'dumpMode'
```

**Comment by stamparm** [comment] 2016-04-19 07:27
Duplicate of #1628 (fixed almost 2 years ago)

**Closed by stamparm** 2016-04-19 07:27 UTC
