### ISSUE TITLE
Unhandled exception (#966d69f7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4820] opened 2021-09-25 04:00 UTC
```
Running version: 1.5.9.7#dev
Python version: 2.7.11
Operating system: Windows-10-10.0.17763
Command line: sqlmap.py -r *************************************** --flush-session --level=5 --risk=3 --skip-waf --tamper=space2comment,modsecurityzeroversioned --dump-all
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 171, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 493, in dumpAll
    self.getTables()
  File "plugins/generic/databases.py", line 410, in getTables
    table = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 308, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 154, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 126, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected." % threadData.lastCode
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-09-25 23:11
Duplicate of #4824

**Closed by stamparm** 2021-09-25 23:11 UTC
