### ISSUE TITLE
Unhandled exception (#23dc153f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4155] opened 2020-03-26 19:38 UTC
```
Running version: 1.4.2.42#dev
Python version: 3.7.4
Operating system: Windows-10-10.0.18362-SP0
Command line: sqlmap.py -r ******************************** --dbs --time-sec 20 --random-agent --level 5 --risk 3
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "lib/core/datatype.py", line 44, in __getattr__
    return self.__getitem__(item)
KeyError: 'liveTest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 169, in main
    elif conf.liveTest:
  File "lib/core/datatype.py", line 46, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'liveTest'
```

**Comment by stamparm** [comment] 2020-04-02 21:25
Duplicate of #4095

**Closed by stamparm** 2020-04-02 21:25 UTC
