### ISSUE TITLE
Unhandled exception (#d95d75ba)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2054] opened 2016-07-21 05:41 UTC
```
sqlmap version: 1.0.7.37#dev
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -u ****************************************** -D ********* -T eims_User -C *********************************************** --dump
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 143, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 193, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 218, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 115, in _oneShotUnionUse
    child.attrib.get(column, "").decode("base64")
  File "lib/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "lib/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-21 07:25
Duplicate of #2052

**Closed by stamparm** 2016-07-21 07:25 UTC
