### ISSUE TITLE
Unhandled exception (#1187fa63)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3705] opened 2019-05-24 17:12 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.16
Operating system: Darwin-18.5.0-x86_64-i386-64bit
Command line: /usr/local/bin/sqlmap -r ************************ --level 5 --batch --random-agent -D ******* --dump --start 1 --stop 3
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 180, in main
    start()
  File "/Cellar/sqlmap/1.3.4/libexec/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/Cellar/sqlmap/1.3.4/libexec/lib/controller/controller.py", line 673, in start
    action()
  File "/Cellar/sqlmap/1.3.4/libexec/lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "/Cellar/sqlmap/1.3.4/libexec/plugins/generic/entries.py", line 205, in dumpTable
    value = inject.getValue(query, blind=False, time=False, dump=True) or ""
  File "/Cellar/sqlmap/1.3.4/libexec/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/Cellar/sqlmap/1.3.4/libexec/lib/request/inject.py", line 430, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "/Cellar/sqlmap/1.3.4/libexec/lib/techniques/error/use.py", line 449, in errorUse
    value = _errorFields(expression, expressionFields, expressionFieldsList)
  File "/Cellar/sqlmap/1.3.4/libexec/lib/techniques/error/use.py", line 256, in _errorFields
    dataToStdout("%s\n" % status)
  File "/Cellar/sqlmap/1.3.4/libexec/lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 55: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-24 20:52
Duplicate of #3700

**Closed by stamparm** 2019-05-24 20:52 UTC
