### ISSUE TITLE
Unhandled exception (#d947168c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3064] opened 2018-04-22 13:42 UTC
```
Running version: 1.2.4.1#dev
Python version: 2.7.14
Operating system: Linux-3.18.14-12478549-armv8l-with-libc
Command line: sqlmap.py -u *******************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/core/decorators.py", line 34, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 400, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1565, in checkConnection
    if conf.hostname in (threadData.lastRedirectURL[1] or "") and threadData.lastRedirectURL[1].startswith("https://"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 34: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2018-04-24 17:54
Duplicate of #3022 (fixed)

**Closed by stamparm** 2018-04-24 17:54 UTC
