### ISSUE TITLE
Unhandled exception (#6ee8dce5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5833] opened 2024-12-20 09:55 UTC
```
Running version: 1.8.11.9#dev
Python version: 3.6.8
Operating system: Linux-3.10.0-1160.105.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Command line: sqlmap.py -r ***** --random-agent --risk=3 level=5 --batch --technique=E --sql-shell
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 130, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 71, in sqlQuery
    output[i] = joinValue(output[i])
  File "lib/core/common.py", line 3722, in joinValue
    retVal = delimiter.join(value)
TypeError: sequence item 17: expected str instance, NoneType found
```

**Comment by stamparm** [comment] 2024-12-20 13:03
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5810

**Closed by stamparm** 2024-12-20 13:03 UTC
