### ISSUE TITLE
Unhandled exception (#8a02e2a3)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2783] opened 2017-11-17 12:39 UTC
```
sqlmap version: 1.1.10#stable
Python version: 2.7.10
Operating system: posix
Command line: /usr/local/bin/sqlmap -r r20 --tamper=space2comment --time-sec=30
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 155, in main
    start()
  File "Cellar/sqlmap/1.1.10/libexec/lib/controller/controller.py", line 545, in start
    injection = checkSqlInjection(place, parameter, value)
  File "Cellar/sqlmap/1.1.10/libexec/lib/controller/checks.py", line 410, in checkSqlInjection
    templatePayload = agent.payload(place, parameter, value="", newValue=origValue, where=where)
  File "Cellar/sqlmap/1.1.10/libexec/lib/core/agent.py", line 169, in payload
    retVal = paramString.replace(_, self.addPayloadDelimiters(newValue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 85: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-12-05 10:34
Duplicate of #2766 (fixed)

**Closed by stamparm** 2017-12-05 10:34 UTC
