### ISSUE TITLE
Unhandled exception (#d887544e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1713] opened 2016-02-15 21:51 UTC
```
sqlmap version: 1.0-dev-nongit-201601110a89
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap --url ******************************************************************** --dbms=Postgresql --threads=10 --users --passwords
Technique: BOOLEAN
Back-end DBMS: PostgreSQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 110, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 626, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 81, in action
    conf.dbmsHandler.getPasswordHashes(), "password hash", CONTENT_TYPE.PASSWORDS)
  File "share/sqlmap/plugins/generic/users.py", line 322, in getPasswordHashes
    attackCachedUsersPasswords()
  File "share/sqlmap/lib/utils/hash.py", line 405, in attackCachedUsersPasswords
    results = dictionaryAttack(kb.data.cachedUsersPasswords)
  File "share/sqlmap/lib/utils/hash.py", line 935, in dictionaryAttack
    _bruteProcessVariantB(user, hash_, kwargs, hash_regex, suffix, retVal, found_, 0, 1, kb.wordlists, custom_wordlist)
  File "share/sqlmap/lib/utils/hash.py", line 611, in _bruteProcessVariantB
    current = __functions__[hash_regex](password=word, uppercase=False, **kwargs)
  File "share/sqlmap/lib/utils/hash.py", line 126, in postgres_passwd
    retVal = "md5%s" % md5(password + username).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbd in position 0: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-02-16 07:42
Duplicate of #1635 (please update)

**Closed by stamparm** 2016-02-16 07:42 UTC
