### ISSUE TITLE
Unhandled exception (#d6dd5553)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2859] opened 2018-01-03 16:41 UTC
```
sqlmap version: 1.1.12.7#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -r ***** --dbs --banner --random-agent --level=4 --risk=3 --no-cast -D ******************* -T ****** -C ************************************************************************************* --dump --start=26000 --technique=B --eta
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 100, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 141, in getDbs
    db = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/request/inject.py", line 434, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 287, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 130, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 102, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 628, in bisection
    progress.progress(time.time() - charStart, index)
NameError: global name 'charStart' is not defined
```

**Comment by stamparm** [comment] 2018-01-06 01:27
Duplicate of #2824 (fixed)

**Closed by stamparm** 2018-01-06 01:27 UTC
