### ISSUE TITLE
Unhandled exception (#3b20617a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3081] opened 2018-05-03 03:10 UTC
```
Running version: 1.2.4#pip
Python version: 2.7.10
Operating system: Darwin-17.5.0-x86_64-i386-64bit
Command line: /usr/local/bin/sqlmap -r /Users/***/Desktop/4.txt
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 398, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1557, in checkConnection
    if conf.hostname in (threadData.lastRedirectURL[1] or "") and threadData.lastRedirectURL[1].startswith("https://"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb6 in position 58: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2018-05-03 11:07
Duplicate of #3022 (fixed)

**Closed by stamparm** 2018-05-03 11:07 UTC
