### ISSUE TITLE
Unhandled exception (#5b6e6a17)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2871] opened 2018-01-09 18:42 UTC
```
sqlmap version: 1.2.1.5#dev
Python version: 2.7.13rc1
Operating system: nt
Command line: sqlmap.py -u *************************************************** T members --columns -U ********************************* --dump
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 222, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 418, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 434, in errorUse
    runThreads(numThreads, errorThread)
  File "lib/core/threads.py", line 187, in runThreads
    print
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-01-12 15:16
Duplicate of #2790

**Closed by stamparm** 2018-01-12 15:16 UTC
