### ISSUE TITLE
Unhandled exception (#1a88f8fe)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4892] opened 2021-11-24 14:26 UTC
```
Running version: 1.3.10.26#dev
Python version: 2.7
Operating system: Windows-8-6.2.9200
Command line: sqlmap.py -u ******************************************* --batch -th 10 -D ************** -T ***************** --dump-all
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 693, in start
    action()
  File "lib/controller/action.py", line 169, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 503, in dumpAll
    self.dumpTable()
  File "plugins/generic/entries.py", line 451, in dumpTable
    attackDumpedTable()
  File "lib/utils/hash.py", line 718, in attackDumpedTable
    results = dictionaryAttack(attack_dict)
  File "lib/utils/hash.py", line 1104, in dictionaryAttack
    process.start()
  File "C:/Python27/lib/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "C:/Python27/lib/multiprocessing/forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:/Python27/lib/multiprocessing/forking.py", line 364, in get_command_line
    opts = util._args_from_interpreter_flags()
  File "C:/Python27/lib/subprocess.py", line 506, in _args_from_interpreter_flags
    v = getattr(sys.flags, flag)
AttributeError: 'sys.flags' object has no attribute 'hash_randomization'
```

**Comment by stamparm** [comment] 2021-11-27 19:21
Duplicate of #1104

**Closed by stamparm** 2021-11-27 19:21 UTC
