### ISSUE TITLE
Unhandled exception (#ad69a83a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5196] opened 2022-10-13 20:39 UTC
```
Running version: 1.6.10.4#dev
Python version: 2.7.18
Operating system: Windows-10-10.0.22000
Command line: sqlmap.py -u ****************************************************************************** -C **** --search
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 179, in action
    conf.dbmsHandler.search()
  File "plugins/generic/search.py", line 632, in search
    self.searchColumn()
  File "plugins/dbms/mssqlserver/enumeration.py", line 363, in searchColumn
    foundTbl = safeSQLIdentificatorNaming(unArrayizeValue(foundTbl), True)
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-10-17 09:36
Duplicate of #5202 (fixed)

**Closed by stamparm** 2022-10-17 09:36 UTC
