### ISSUE TITLE
Unhandled exception (#b590afb8)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3725] opened 2019-05-29 15:44 UTC
```
Running version: 1.3.5.140#dev
Python version: 2.7.16
Operating system: Windows-10-10.0.16299
Command line: sqlmap.py -u ********************************************************************** -b --dbs --cookie=******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 420, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1506, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1322, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 798, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 388, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", "".join(responseHeaders.headers), page)
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by stamparm** [comment] 2019-05-30 18:17
Duplicate of #3710 (fixed)

**Closed by stamparm** 2019-05-30 18:17 UTC
