### ISSUE TITLE
Unhandled exception (#053dbf62)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2608] opened 2017-07-13 08:55 UTC
```
sqlmap version: 1.1.6.17#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -r C:\Users\******\AppData\Local\Temp\\1499936101316.req
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 150, in main
    start()
  File "lib/controller/controller.py", line 391, in start
    setupTargetEnv()
  File "lib/core/target.py", line 737, in setupTargetEnv
    _createTargetDirs()
  File "lib/core/target.py", line 674, in _createTargetDirs
    f.write("  # %s" % subprocess.list2cmdline(sys.argv))
  File "Python27/lib/codecs.py", line 706, in write
    return self.writer.write(data)
  File "Python27/lib/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 30: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-07-13 09:02
Duplicate of #2596 (patched)

**Closed by stamparm** 2017-07-13 09:02 UTC
