### ISSUE TITLE
Unhandled exception (#f7db55be)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2983] opened 2018-03-13 19:45 UTC
```
Running version: 1.2.3.24#dev
Python version: 2.7.14+
Operating system: Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py -u ****************************************** --data ********************************************************************************************************* --param-del   --technique B --eval true=true.replace(",",",-it.id%2b");order_by="id,"*true.count(",")+"id" --tamper commalesslimit --sql-query SELECT user_name FROM wp_users WHERE id=2
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 398, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1517, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1042, in queryPage
    value = urldecode(value, convall=True, spaceplus=(item == post and kb.postSpaceToPlus))
TypeError: urldecode() got an unexpected keyword argument 'spaceplus'
```

**Comment by stamparm** [comment] 2018-03-13 23:57
Duplicate of #2982

**Closed by stamparm** 2018-03-13 23:57 UTC
