### ISSUE TITLE
Unhandled exception (#ff7dee75)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2925] opened 2018-02-11 15:49 UTC
```
sqlmap version: 1.1.11.30#dev
Python version: 2.7.12
Operating system: posix
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 154, in main
    else:
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 27, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "plugins/dbms/mssqlserver/__init__.py", line 15, in <module>
    from plugins.dbms.mssqlserver.takeover import Takeover
  File "plugins/dbms/mssqlserver/takeover.py", line 14, in <module>
    from plugins.generic.takeover import Takeover as GenericTakeover
  File "plugins/generic/takeover.py", line 25, in <module>
    from lib.takeover.abstraction import Abstraction
  File "lib/takeover/abstraction.py", line 27, in <module>
    from lib.takeover.web import Web
  File "lib/takeover/web.py", line 50, in <module>
    from lib.core.settings import SHELL_RUNCMD_EXE_TAG
ImportError: cannot import name SHELL_RUNCMD_EXE_TAG
```

**Comment by stamparm** [comment] 2018-02-12 00:16
Duplicate of #2812 (fixed)

**Closed by stamparm** 2018-02-12 00:16 UTC
