### ISSUE TITLE
Unhandled exception (#6195e3f8)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1373] opened 2015-08-30 05:07 UTC
```
sqlmap version: 1.0-dev-nongit-20150826
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u **************************************** --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 100, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 521, in start
    injection = checkSqlInjection(place, parameter, value)
  File "share/sqlmap/lib/controller/checks.py", line 425, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "share/sqlmap/lib/request/connect.py", line 1054, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "share/sqlmap/lib/request/connect.py", line 436, in getPage
    conn = urllib2.urlopen(req)
  File "lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "share/sqlmap/lib/request/redirecthandler.py", line 89, in http_error_302
    content = decodePage(content, headers.get(HTTP_HEADER.CONTENT_ENCODING), headers.get(HTTP_HEADER.CONTENT_TYPE))
  File "share/sqlmap/lib/request/basic.py", line 292, in decodePage
    kb.pageEncoding = kb.pageEncoding or checkCharEncoding(getHeuristicCharEncoding(page))
  File "share/sqlmap/lib/request/basic.py", line 215, in getHeuristicCharEncoding
    retVal = detect(page)["encoding"]
  File "share/sqlmap/thirdparty/chardet/__init__.py", line 21, in detect
    import universaldetector
  File "share/sqlmap/thirdparty/chardet/universaldetector.py", line 32, in <module>
    from sbcsgroupprober import SBCSGroupProber # single-byte character sets
  File "share/sqlmap/thirdparty/chardet/sbcsgroupprober.py", line 36, in <module>
    from langthaimodel import TIS620ThaiModel
ValueError: bad marshal data (unknown type code)
```

**Comment by stamparm** [comment] 2015-08-30 20:44
Duplicate of #1369

**Closed by stamparm** 2015-08-30 20:44 UTC
