### ISSUE TITLE
Unhandled exception (#7d1c7af0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1087] opened 2015-01-02 18:06 UTC
```
sqlmap version: 1.0-dev-nongit-20150102
Python version: 2.7.2
Operating system: posix
Command line: sdl --disable-col -c /xbin/qem.dat -v 1 --timeout=30 --retries=3 --threads=1 --risk=1 --level=1 --technique=BEUSTQ --dependencies
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/sqlmap.py", line 76, in main
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 2297, in initOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 1935, in _mergeOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/parse/configfile.py", line 72, in configFileParser
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/ConfigParser.py", line 316, in readfp
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/ConfigParser.py", line 471, in _read
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 675, in readline
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 530, in readline
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 477, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 0: invalid start byte
```

**Comment by stamparm** [comment] 2015-01-03 21:17
Duplicate of #1064

**Closed by stamparm** 2015-01-03 21:17 UTC
Labels: duplicate
