### ISSUE TITLE
Unhandled exception (#3d60c0df)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3182] opened 2018-07-11 16:41 UTC
```
Running version: 1.2.6.14#dev
Python version: 2.7.15
Operating system: Linux-3.10.65-12808116-armv7l-with-libc
Command line: sqlmap.py sqlmap --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in main
    dataToStdout("[*] starting at %s\n\n" % time.strftime("%X"), forceOutput=True)
  File "lib/core/option.py", line 2685, in init
  File "lib/core/update.py", line 88, in update
    try:
OSError: [Errno 1] Operation not permitted: '/storage/emulated/0/Download/sqlmap/sqlmap.py'
```

**Comment by stamparm** [comment] 2018-07-12 08:34
Duplicate of #3142 (patched)

**Closed by stamparm** 2018-07-12 08:34 UTC
