### ISSUE TITLE
Unhandled exception (#aec20661)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3152] opened 2018-06-17 19:25 UTC
```
Running version: 1.2.6.19#dev
Python version: 2.7.15rc1
Operating system: Linux-4.15.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap -d mysql://****:t67747@140.119.108.209:3306 --os-shell
Technique: DIRECT
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 158, in main
    start()
  File "share/sqlmap/lib/core/decorators.py", line 34, in _
    result = f(*args, **kwargs)
  File "share/sqlmap/lib/controller/controller.py", line 267, in start
    setupTargetEnv()
  File "share/sqlmap/lib/core/target.py", line 742, in setupTargetEnv
    _resumeHashDBValues()
  File "share/sqlmap/lib/core/target.py", line 436, in _resumeHashDBValues
    kb.absFilePaths = hashDBRetrieve(HASHDB_KEYS.KB_ABS_FILE_PATHS, True) or kb.absFilePaths
  File "share/sqlmap/lib/core/common.py", line 4292, in hashDBRetrieve
    _ = '|'.join((conf.hostname, conf.path.strip('/') if conf.path is not None else conf.port, key, HASHDB_MILESTONE_VALUE))
TypeError: sequence item 1: expected string, int found
```

**Comment by stamparm** [comment] 2018-06-19 12:58
Duplicate of #3150 (fixed)

**Closed by stamparm** 2018-06-19 12:58 UTC
