### ISSUE TITLE
Unhandled exception (#be8ed995)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4615] opened 2021-03-26 01:29 UTC
```
Running version: 1.5.3.19#dev
Python version: 2.7.15
Operating system: Windows-10-10.0.18362
Command line: C:\tools\sqlmap\sqlmap.pyc --dependencies
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 176, in main
    from lib.core.testing import vulnTest
  File "lib/core/datatype.py", line 48, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'bedTest'
```

**Comment by stamparm** [comment] 2021-03-26 12:50
Duplicate of #4608

**Closed by stamparm** 2021-03-26 12:50 UTC
