### ISSUE TITLE
Unhandled exception (#042d517b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1598] opened 2015-12-09 09:10 UTC
```
sqlmap version: 1.0-dev-nongit-20150828
Python version: 2.7.2
Operating system: nt
Command line: sqlmap.py -u ****************************** --pickled-options Y3N1YnByb2Nlc3MKUG9wZW4KcDEKKFMnY2FsYy5leGUnCnAyCnRwMwpScDQKLg==
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 85, in main
    initOptions(cmdLineOptions)
  File "lib/core/option.py", line 2485, in initOptions
    _mergeOptions(inputOptions, overrideOptions)
  File "lib/core/option.py", line 2080, in _mergeOptions
    if inputOptions.configFile:
AttributeError: 'Popen' object has no attribute 'configFile'
```

**Comment by stamparm** [comment] 2015-12-09 09:14
Duplicate of #1592

**Closed by stamparm** 2015-12-09 09:14 UTC
