### ISSUE TITLE
Support ORDER BY when using --dump

### ISSUE THREAD

**Issue by TGDebug** [sqlmapproject/sqlmap#4538] opened 2021-01-12 14:09 UTC
**Is your feature request related to a problem? Please describe.**
When trying to dump a large table it takes a long time till sqlmap reaches the latest entries.

**Describe the solution you'd like**
Add a switch that allows to dump by using ORDER BY, for example 
`--order-by="id" --order-dir="DESC"`
or
`--order-by="id DESC"`

**Describe alternatives you've considered**
The current approach is to use the sql-shell/sql-query to manually order by the wanted column and then dump using --start to dump the latest _x_ rows.

**Additional context**
N/A

**Comment by stamparm** [comment] 2021-01-12 14:21
Duplicate of #4388

**Closed by stamparm** 2021-01-12 14:21 UTC
Labels: feature request
