### ISSUE TITLE
Unhandled exception (#0819c161)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2831] opened 2017-12-16 14:18 UTC
```
sqlmap version: 1.1.12#stable
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py C:\Users\*****\Desktop\Mr. Haxer\Sites\sqlmap\cmd.exe.lnk
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 123, in main
    cmdLineOptions.update(cmdLineParser().__dict__)
  File "lib/parse/cmdline.py", line 984, in cmdLineParser
    parser.error(errMsg)
  File "Python27/lib/optparse.py", line 1583, in error
    self.print_usage(sys.stderr)
  File "Python27/lib/optparse.py", line 1603, in print_usage
    print >>file, self.get_usage()
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2017-12-18 23:07
Duplicate of #2790

**Closed by stamparm** 2017-12-18 23:07 UTC
