### ISSUE TITLE
Unhandled exception (#0ff65742)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3703] opened 2019-05-24 16:03 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.5
Operating system: Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Command line: sqlmap.py -u ***************************************************** --data=******************************* --test-filter=MySQL >= 5.0 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR) -p pwd --random-agent --level=5 --risk=3 --technique=E --dbms=MySQL --sql-shell --threads=10
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 183, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 114, in sqlShell
    conf.dumper.sqlQuery(query, output)
  File "lib/core/dump.py", line 701, in sqlQuery
    self.string(query, queryRes, content_type=CONTENT_TYPE.SQL_QUERY)
  File "lib/core/dump.py", line 123, in string
    self.lister(header, data, content_type, sort)
  File "lib/core/dump.py", line 163, in lister
    self._write("[*] " + ", ".join(getUnicode(e) for e in element))
  File "lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-24 20:51
Duplicate of #3700

**Closed by stamparm** 2019-05-24 20:51 UTC
