### ISSUE TITLE
Unhandled exception (#3f480e15)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2915] opened 2018-02-06 13:01 UTC
```
sqlmap version: 1.1.12#stable
Python version: 2.7.12
Operating system: posix
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 154, in main
    else:
  File "lib/controller/controller.py", line 69, in <module>
    from lib.core.target import initTargetEnv
  File "lib/core/target.py", line 38, in <module>
    from lib.core.dump import dumper
  File "lib/core/dump.py", line 49, in <module>
    from lib.core.settings import UNSAFE_DUMP_FILEPATH_REPLACEMENT
ImportError: cannot import name UNSAFE_DUMP_FILEPATH_REPLACEMENT
```

**Comment by stamparm** [comment] 2018-02-07 09:59
Duplicate of #2812 (fixed)

**Closed by stamparm** 2018-02-07 09:59 UTC
