### ISSUE TITLE
Unhandled exception (#d1c9436e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1766] opened 2016-03-16 19:19 UTC
```
sqlmap version: 1.0-dev-3a94435
Python version: 2.7.5
Operating system: posix
Command line: sqlmap.py -u ****************************************************************************** --dbms=mssql --random-agent --level 5 --risk 3 --parse-errors --tamper=space2comment --dump-all
Technique: BOOLEAN
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 114, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 130, in action
    conf.dbmsHandler.dumpAll()
  File "plugins/generic/entries.py", line 392, in dumpAll
    self.dumpTable()
  File "plugins/generic/entries.py", line 272, in dumpTable
    retVal = pivotDumpTable(table, colList, count, blind=True)
  File "lib/utils/pivotdumptable.py", line 134, in pivotDumpTable
    value = _(column, pivotValue)
  File "lib/utils/pivotdumptable.py", line 126, in _
    return unArrayizeValue(inject.getValue(query, blind=blind, time=blind, union=not blind, error=not blind))
  File "lib/request/inject.py", line 456, in getValue
    conf.db = popValue()
  File "lib/core/common.py", line 2197, in popValue
    return getCurrentThreadData().valueStack.pop()
IndexError: pop from empty list
```

**Comment by stamparm** [comment] 2016-03-17 15:24
Duplicate of #1760 (fixed)

**Closed by stamparm** 2016-03-17 15:24 UTC
