### ISSUE TITLE
Unhandled exception (#1765a9f7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3708] opened 2019-05-24 21:46 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.16
Operating system: Linux-4.9.82-perf+-aarch64-with-libc
Command line: sqlmap.py -u ***************************************** -D ************** -T ************ -C ****************************************************** --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 453, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 605, in dbTableValues
    self._write("| %s%s" % (value, blank), newline=False, console=console)
  File "lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-24 21:54
Duplicate of #3700

**Closed by stamparm** 2019-05-24 21:54 UTC
