### ISSUE TITLE
Unhandled exception (#07cbf8ce)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2092] opened 2016-08-10 07:55 UTC
```
sqlmap version: 1.0.6.24#dev
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -v3 --random-agent --dbms=mysql --url=******************************** -D ** -T ******* --file-read=***********
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in ****
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 147, in action
    conf.dumper.rFile(conf.dbmsHandler.readFile(conf.rFile))
  File "plugins/generic/filesystem.py", line 253, in readFile
    localFilePath = dataToOutFile(remoteFile, fileContent)
  File "lib/core/common.py", line 944, in dataToOutFile
    f.write(data)
  File "usr/lib/python2.7/codecs.py", line 688, in write
    return self.writer.write(data)
  File "usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 7056: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-08-12 00:55
Duplicate of #1941 (patched)

**Closed by stamparm** 2016-08-12 00:55 UTC
