### ISSUE TITLE
Unhandled exception (#87e29fe5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3346] opened 2018-10-29 19:58 UTC
```
Running version: 1.2.10.12#dev
Python version: 2.7.15
Operating system: Windows-2012Server-6.2.9200-SP0
Command line: sqlmap.py --url=************* --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=MYSQL --random-agent --is-dba --exclude-sysdbs --current-db --answers=**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
  File "lib/controller/controller.py", line 12, in <module>
  File "lib/controller/action.py", line 8, in <module>
  File "lib/controller/handler.py", line 27, in <module>
NameError: Can't find file for module __init__.py
(filename C:\Users\*************\.sqlmap\plugins\dbms\__init__.py)
```

**Comment by stamparm** [comment] 2018-10-30 09:29
Duplicate of #3329

**Closed by stamparm** 2018-10-30 09:29 UTC
