### ISSUE TITLE
Unhandled exception (#96927450)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4274] opened 2020-07-17 16:19 UTC
```
Running version: 1.4.6.6#dev
Python version: 2.7.17
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py -r ********** -v 1 --level=5 --risk=3 --random-agent --threads=1 --tamper=randomcase --no-cast --dbs
Technique: STACKED
Back-end DBMS: SQLite (fingerprinted) Microsoft SQL Server (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 588, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 440, in checkSqlInjection
    templatePayload = agent.payload(place, parameter, value="", newValue=origValue, where=where)
  File "lib/core/agent.py", line 213, in payload
    retVal = paramString.replace(origValue, self.addPayloadDelimiters(newValue))
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by stamparm** [comment] 2020-07-20 10:46
Duplicate of #4270 (patched)

**Closed by stamparm** 2020-07-20 10:46 UTC
