### ISSUE TITLE
Unhandled exception (#483d535e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4675] opened 2021-05-10 07:59 UTC
```
Running version: 1.5#stable
Python version: 2.7.18
Operating system: Windows-10-10.0.19041
Command line: sqlmap.py -r *************************************************** --technique=S --os-cmd=ls
Technique: STACKED
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 218, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 60, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 219, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 183, in udfInjectSys
    return self.udfInjectCore(self.sysUdfs)
  File "lib/takeover/udf.py", line 147, in udfInjectCore
    self.udfSetRemotePath()
  File "plugins/dbms/mysql/takeover.py", line 41, in udfSetRemotePath
    if distutils.version.LooseVersion(banVer) >= distutils.version.LooseVersion("5.0.67"):
  File "/Python27/lib/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: LooseVersion instance has no attribute 'version'
```

**Comment by stamparm** [comment] 2021-05-10 08:38
Duplicate of #4504 (fixed)

**Closed by stamparm** 2021-05-10 08:38 UTC
