### ISSUE TITLE
Unhandled exception (#7ea1ba3f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2979] opened 2018-03-11 15:25 UTC
```
sqlmap version: 1.0.9.21#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ********************************************************************** --cookie=security=low; PHPSESSID=tijah3c3rrplmgdashjbhen4u3 -D dvwa -T users -p id
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 122, in main
    banner()
  File "lib/core/common.py", line 1142, in banner
    dataToStdout(_, forceOutput=True)
  File "lib/core/common.py", line 896, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-03-12 08:53
Duplicate of #2790 (fixed)

**Closed by stamparm** 2018-03-12 08:53 UTC
Labels: duplicate
