### ISSUE TITLE
Unhandled exception (#cab27b84)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3506] opened 2019-02-28 04:44 UTC
```
Running version: 1.3.2.30#dev
****** version: 2.7.10
Operating ******* Windows-7-6.1.7601-SP1
Command line: ********* -u ***************************************** --data=************** -v 3 --hex --risk 3 --level 5 --user-agent=random -o --time-sec=10 --tamper=between --skip-urlencode --flush-session --current-user --current-db --hostname --users --passwords --comments --forms --fresh-queries --dbs
Technique: UNION
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File ************ line 167, in main
    start()
  File ************************* line 53, in _
    result = f(*args, **kwargs)
  File ******************************* line 561, in start
    injection = checkSqlInjection(place, parameter, value)
  File *************************** line 835, in checkSqlInjection
    if not checkFalsePositives(injection):
  File ************************* line 53, in _
    result = f(*args, **kwargs)
  File *************************** line 916, in checkFalsePositives
    if not checkBooleanExpression("%d=%d" % (randInt1, randInt1)):
  File ************************ line 517, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, ******************************** suppressOutput=True, expectingNone=expectingNone)
  File ************************* line 53, in _
    result = f(*args, **kwargs)
  File ************************ line 350, in getValue
    if not hasattr(queries[Backend.getIdentifiedDbms()], "hex"):
********* None
```

**Comment by stamparm** [comment] 2019-02-28 12:31
Duplicate of #3503 (fixed)

**Closed by stamparm** 2019-02-28 12:31 UTC
