### ISSUE TITLE
Sqlmap give Database,Tables, and Columns name, but dont dump content

### ISSUE THREAD

**Issue by moku23** [sqlmapproject/sqlmap#2163] opened 2016-09-09 14:36 UTC
Hello everyone,

im try to dump database content, i take 
- Databases
- Tables of each DB
- Columns
but when i dump rows i take back:

>  .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .
> [16:40:46] [DEBUG] got HTTP error code: 500 (Internal Server Error)
> .

Any ideas?
Thanks for support

**Comment by stamparm** [comment] 2016-09-09 15:31
Which SQLi techniques have been found by sqlmap? Also, you haven't mentioned whether sqlmap nagged about WAF/IDS/IPS?

**Comment by moku23** [comment] 2016-09-09 15:34
I've tried Blind Time based, Stacked, and everytime when i dump rows i take back points.
Tried tamper too: randomcase, space2comment but nothing to do.
DBMS is Microsoft SQL Server

**Comment by stamparm** [comment] 2016-09-09 15:35
And you've still not replied to my question: `Also, you haven't mentioned whether sqlmap nagged about WAF/IDS/IPS?`

**Comment by moku23** [comment] 2016-09-09 15:40
WAF/IDS/IPS product hasn't been identified

**Comment by stamparm** [comment] 2016-09-09 16:06
But it was detected? That big red warning that there could be a protection?
You are skewing answers. Closing this down

**Closed** 2016-09-09 16:06 UTC
Labels: support

**Comment by moku23** [comment] 2016-09-10 12:45
Stamparm, no red warning message. :(

**Comment by drequil** [comment] 2018-11-05 22:44
@stamparm, that was pretty brutal how you shut down this guy 2 years ago and shut down another occurence of this issue in another thread.  The users are able to get table and column meta-data but not the data itself, and there is nothing wrong with us trying to understand why this is.  

Dang man.  I'm ne aplodirovat' you.

**Comment by stamparm** [comment] 2018-11-06 10:21
@drequil you have to have something useful to work with. Majority of users don't spend two minutes finding out the reason to behavior, while occasionally everything is written inside the console. Meta data is being retrieved from one set of tables, while the real table dump could be failing because of XYZ reason (e.g. too long parameter value, permission problems, blocking of some specific keyword from the WAF/IPS, etc.)

I have to have something useful from start. If I am not provided with a solid case, while I can't reproduce the issue inside the testing environment, I don't have much choice.

Also, I am a certified BOFH. If I catch users playing dumb or just being lazy to make a primitive triage, I don't react to well. Known fact, not too proud of it, but that's the practice got by dealing with thousands of issues during the years
