### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by x7art** [sqlmapproject/sqlmap#3042] opened 2018-04-11 04:42 UTC
Traceback (most recent call last):
  File "C:\Python27\sqlmap\lib\core\threads.py", line 139, in runThreads
    threadFunction()
  File "C:\Python27\sqlmap\lib\techniques\union\use.py", line 334, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "C:\Python27\sqlmap\lib\techniques\union\use.py", line 84, in _oneShotUnionUse
    page, headers, _ = Request.queryPage(payload, content=True, raise404=False)
  File "C:\Python27\sqlmap\lib\request\connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie,
 ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise40
4=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Python27\sqlmap\lib\request\connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "C:\Python27\lib\urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "C:\Python27\lib\urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by stamparm** [comment] 2018-04-11 10:09
Can you provide more details? There was a message at the end of that error message where it said to provide (if you can) more details to reproduce this issue (to `miroslav@sqlmap.org`). Thing is that I am trying to reproduce this for couple of months without any luck

**Comment by stamparm** [comment] 2018-04-11 10:10
Duplicate of #2886

**Closed** 2018-04-24 17:43 UTC
Labels: duplicate
