### ISSUE TITLE
Unhandled exception (#0e8c0c7b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4459] opened 2020-12-03 17:59 UTC
```
Running version: 1.4.6.20#dev
Python version: 3.4.0
Operating system: Windows-8-6.2.9200
Command line: sqlmap.py -u ************************************************************* --batch --tables --proxy-file=ip.txt
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 166, in main
    init()
  File "lib/core/option.py", line 2701, in init
    _setHTTPHandlers()
  File "lib/core/option.py", line 986, in _setHTTPHandlers
    conf.proxy = conf.proxyList[0]
IndexError: list index out of range
```

**Comment by stamparm** [comment] 2020-12-04 10:41
Duplicate of #4284 (fixed)

**Closed by stamparm** 2020-12-04 10:41 UTC
