### ISSUE TITLE
Unhandled exception (#5da72764)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2077] opened 2016-08-02 03:39 UTC
```
sqlmap version: 1.0.7.25#dev
Python version: 2.7.10
Operating system: posix
Command line: sqlmap.py --url ********************************************************** -p idioma -D ****** -T Usuarios --dump
Technique: None
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
  File "plugins/generic/databases.py", line 555, in getColumns
    values = unionUse(expression)
  File "lib/techniques/union/use.py", line 211, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 108, in _oneShotUnionUse
    root = xml.etree.ElementTree.fromstring("<root>%s</root>" % output)
  File "usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "usr/lib64/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 211: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-08-02 09:00
Duplicate of #2045 (fixed)

**Closed by stamparm** 2016-08-02 09:00 UTC
