### ISSUE TITLE
Unhandled exception (#739a544e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4894] opened 2021-11-29 19:16 UTC
```
Running version: 1.5.7.6#dev
Python version: 3.9.2
Operating system: Linux-4.9.0-15-amd64-x86_64-with-glibc2.24
Command line: sqlmap.py -u *********************************************** --random-agent --time-sec=10 --batch --current-user --is-dba --level=5 --risk=3 --threads=3 --output-dir=dumps --timeout=90 --retries=2400 --technique=BETQUS --exclude-sysdbs --cleanup --hex --answers=************************************************************
Technique: STACKED
Back-end DBMS: Oracle (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 244, in action
    conf.dbmsHandler.cleanup()
  File "plugins/generic/misc.py", line 161, in cleanup
    udfDict = self.sysUdfs
AttributeError: 'OracleMap' object has no attribute 'sysUdfs'
```

**Comment by stamparm** [comment] 2021-11-30 09:30
Duplicate of #4751 (fixed)

**Closed by stamparm** 2021-11-30 09:30 UTC
