### ISSUE TITLE
Unhandled exception (#7c85dc8b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2152] opened 2016-09-03 21:05 UTC
```
sqlmap version: 1.0.9#pip
Python version: 2.7.9
Operating system: posix
Command line: /usr/local/bin/sqlmap -u *********************************************************************************************************************************************************************************************************** --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 132, in main
    if conf.profile:
  File "lib/core/datatype.py", line 44, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'profile'
```

**Comment by stamparm** [comment] 2016-09-03 21:07
Duplicate of #2146

**Closed by stamparm** 2016-09-03 21:07 UTC
