### ISSUE TITLE
Unhandled exception (#2ffe276f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5217] opened 2022-10-29 18:18 UTC
```
Running version: 1.6.10.7#dev
Python version: 3.12.0a1
Operating system: Windows-10-10.0.19044-SP0
Command line: sqlmap.py -u *************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 589, in start
    injection = checkSqlInjection(place, parameter, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/controller/checks.py", line 507, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 1536, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 627, in getPage
    conn = _urllib.request.urlopen(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 518, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 535, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 495, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "lib/request/httpshandler.py", line 134, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/AppData/Local/Programs/Python/Python312/Lib/urllib/request.py", line 1347, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1296, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1342, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1291, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "lib/core/patch.py", line 61, in _send_output
    self.__send_output(*args, **kwargs)
  File "/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 1051, in _send_output
    self.send(msg)
  File "/AppData/Local/Programs/Python/Python312/Lib/http/client.py", line 989, in send
    self.connect()
  File "lib/request/httpshandler.py", line 98, in connect
    _ = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=protocol)
        ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by stamparm** [comment] 2022-11-01 21:22
Duplicate of #5216

**Closed by stamparm** 2022-11-01 21:22 UTC
