### ISSUE TITLE
Unhandled exception (#2fc6bf3e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5809] opened 2024-11-18 02:29 UTC
```
Running version: 1.8.11.8#dev
Python version: 3.13.0
Operating system: macOS-15.1-arm64-arm-64bit-Mach-O
Command line: sqlmap.py -r ****** --force-ssl --answers=********************************** --batch --risk=3 --level=5 --skip-waf --dbms=mysql -D *************** --sql-shell
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
    ~~~~~^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
    ~~~~~~^^
  File "lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "plugins/generic/custom.py", line 130, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 68, in sqlQuery
    if "SELECT" in sqlType and isListLike(output):
       ^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by stamparm** [comment] 2024-11-19 11:14
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5806

**Closed by stamparm** 2024-11-19 11:14 UTC
