### ISSUE TITLE
Unhandled exception (#317d3c4b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1927] opened 2016-06-04 20:21 UTC
```
sqlmap version: 1.0-dev-nongit-201604070a89
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u **************************************************************** -f -b -a -p catid --dbms sybase -D ********** --tables --random-agent --identify-waf --no-cast --risk 3 --level 5 --threads 6 --output /Desktop/sqlmap/output/
Technique: BOOLEAN
Back-end DBMS: Sybase (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 110, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 626, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 130, in action
    conf.dbmsHandler.dumpAll()
  File "share/sqlmap/plugins/generic/entries.py", line 361, in dumpAll
    self.dumpTable()
  File "share/sqlmap/plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
TypeError: getColumns() got an unexpected keyword argument 'dumpMode'
```

**Comment by stamparm** [comment] 2016-06-05 09:47
Duplicate of #1628 (fixed long ago)

**Closed by stamparm** 2016-06-05 09:47 UTC
