### ISSUE TITLE
Unhandled exception (#2fc0826a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4329] opened 2020-09-04 03:46 UTC
```
Running version: 1.3.12.1#dev
Python version: 2.7.17
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=********** --crawl=2 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql --technique=EUSQ --random-agent --is-dba --exclude-sysdbs --current-db --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: UNION
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 212, in main
    start()
  File "lib/core/decorators.py", line 75, in _
  File "lib/controller/controller.py", line 418, in start
  File "lib/core/target.py", line 738, in setupTargetEnv
  File "lib/core/target.py", line 651, in _createTargetDirs
  File "/Python27/lib/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
WindowsError: [Error 1450] Insufficient system resources exist to complete the requested service: 'c:\\users\\********\\appdata\\local\\temp\\2\\sqlmapul6ffl6328\\sqlmapoutputs_tva3'
```

**Comment by stamparm** [comment] 2020-09-04 08:49
Duplicate of  #4328

**Closed by stamparm** 2020-09-04 08:49 UTC
