### ISSUE TITLE
Unhandled exception (#23d2da0b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4064] opened 2020-01-07 04:03 UTC
```
Running version: 1.3.7.18#dev
Python version: 2.7.17
Operating system: Windows-10-10.0.18362
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    sys.stderr = StdDbOut(conf.taskid, messagetype="stderr")
  File "lib/core/option.py", line 2634, in init
  File "lib/core/update.py", line 117, in update
    finally:
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by stamparm** [comment] 2020-01-07 08:33
Duplicate of #3898 (patched)

**Closed by stamparm** 2020-01-07 08:33 UTC
