### ISSUE TITLE
Unhandled exception (#e538302e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4668] opened 2021-05-05 12:25 UTC
```
Running version: 1.5.3.1#dev
Python version: 2.7.15
Operating system: Windows-7-6.1.7601-SP1
Command line: sqlmap.py -r ************************************ --batch --dbms mysql --level 3
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 217, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 591, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 528, in checkSqlInjection
    trueResult = Request.queryPage(reqPayload, place, raise404=False)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1501, in queryPage
    return comparison(page, headers, code, getRatioValue, pageLength)
  File "lib/request/comparison.py", line 37, in comparison
    _ = _adjust(_comparison(page, headers, code, getRatioValue, pageLength), getRatioValue)
  File "lib/request/comparison.py", line 157, in _comparison
    key = (hash(seq1), hash(seq2))
TypeError: unhashable type: 'list'
```

**Comment by stamparm** [comment] 2021-05-05 16:41
Duplicate of #4591 (fixed)

**Closed by stamparm** 2021-05-05 16:41 UTC
Labels: duplicate
