### ISSUE TITLE
Unhandled exception (#48ab5145)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4729] opened 2021-07-03 08:53 UTC
```
Running version: 1.5.6#pip
Python version: 3.9.2
Operating system: Linux-5.10.0-6parrot1-amd64-x86_64-with-glibc2.31
Command line: /usr/local/bin/sqlmap -u ************************************* --tables --columns -DBMS=PostgreSQL --random-agent -passwords -f --technique=BEUSQT -level 4 -risk 3 --text-only --threads 5 --hex --dependencies -scope=payment --schema --current-db --current-user -a --dbms=PostgreSQL
Technique: BOOLEAN
Back-end DBMS: PostgreSQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 76, in action
    conf.dumper.users(conf.dbmsHandler.getUsers())
  File "plugins/generic/users.py", line 130, in getUsers
    query = rootQuery.blind.count3
AttributeError: 'DictObject' object has no attribute 'count3'
```

**Comment by stamparm** [comment] 2021-07-04 21:01
Duplicate of #4728

**Closed by stamparm** 2021-07-04 21:01 UTC
