### ISSUE TITLE
Unhandled exception (#be4ea397)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4952] opened 2022-01-19 10:37 UTC
```
Running version: 1.6.1.2#dev
Python version: 3.10.1
Operating system: Windows-2012ServerR2-6.3.9600-SP0
Command line: sqlmap.py --output-dir=output --url=******************************** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql --technique=EU --random-agent --is-dba --exclude-sysdbs --current-db --answers=******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 14, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 77, in <module>
    from plugins.dbms.mssqlserver.connector import Connector as MSSQLServerConn
  File "plugins/dbms/mssqlserver/__init__.py", line 12, in <module>
    from plugins.dbms.mssqlserver.filesystem import Filesystem
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 22] Invalid argument: 'C:\\Users\\*************\\.sqlmap\\plugins\\dbms\\mssqlserver\\filesystem.py'
```

**Comment by stamparm** [comment] 2022-01-19 13:59
Duplicate of #4950

**Closed by stamparm** 2022-01-19 13:59 UTC
