### ISSUE TITLE
Unhandled exception (#4a25fc34)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2258] opened 2016-11-01 19:08 UTC
```
sqlmap version: 1.0.10.38#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py --sqlmap-shell
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2629, in init
    _setTorProxySettings()
  File "lib/core/option.py", line 2305, in _setTorProxySettings
    _setTorSocksProxySettings()
  File "lib/core/option.py", line 2334, in _setTorSocksProxySettings
    port = findLocalPort(DEFAULT_TOR_SOCKS_PORTS if not conf.torPort else (conf.torPort,))
  File "lib/core/common.py", line 2414, in findLocalPort
    s.connect((LOCALHOST, port))
  File "thirdparty/socks/socks.py", line 753, in connect
    negotiate(self, dest_addr, dest_port)
  File "thirdparty/socks/socks.py", line 613, in _negotiate_SOCKS4
    raise SOCKS4Error("{0:#04x}: {1}".format(status, error))
SOCKS4Error: 0x5b: Request rejected or failed
```

**Comment by stamparm** [comment] 2016-11-02 10:49
Duplicate of #2231 (fixed)

**Closed by stamparm** 2016-11-02 10:49 UTC
