### ISSUE TITLE
Unhandled exception (#7d7ce943)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2686] opened 2017-09-05 14:42 UTC
```
sqlmap version: 1.1.9.4#dev
Python version: 2.7.13
Operating system: posix
Command line: sqlmap.py -u *********************************************************** --dbms=mssql --tamper space2comment.py --random-agent --time-sec 3 --os-cmd=whoami
Technique: TIME
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 155, in main
    start()
  File "lib/controller/controller.py", line 653, in start
    action()
  File "lib/controller/action.py", line 151, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 57, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 210, in initEnv
    self.xpCmdshellInit()
  File "lib/takeover/xp_cmdshell.py", line 248, in xpCmdshellInit
    result = self._xpCmdshellCheck()
  File "lib/takeover/xp_cmdshell.py", line 95, in _xpCmdshellCheck
    self.xpCmdshellExecCmd(cmd)
  File "lib/takeover/xp_cmdshell.py", line 183, in xpCmdshellExecCmd
    return inject.goStacked(self.xpCmdshellForgeCmd(cmd), silent)
  File "lib/takeover/xp_cmdshell.py", line 166, in xpCmdshellForgeCmd
    self._cmd = "0x%s" % hexencode(cmd)
  File "lib/core/convert.py", line 121, in hexencode
    return unicodeencode(value, conf.charset or UNICODE_ENCODING).encode("hex")
NameError: global name 'conf' is not defined
```

**Comment by stamparm** [comment] 2017-09-05 22:04
Duplicate of #2684 (fixed)

**Closed by stamparm** 2017-09-05 22:04 UTC
