### ISSUE TITLE
Unhandled exception (#b7f08bb7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5645] opened 2024-02-27 07:21 UTC
```
运行版本：1.8.1.6#dev
Python版本：3.8.2
操作系统：Windows-10-10.0.26058-SP0
命令行：sqlmap.py -u ************************************************************************************************************ -dbms=mysql --batch --os-shell
技术：BOOLEAN
后端DBMS： MySQL(已识别)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 219, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 707, in start
    action()
  File "lib/controller/action.py", line 217, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 82, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 190, in initEnv
    if mandatory and not self.isDba():
  File "plugins/generic/users.py", line 87, in isDba
    query = queries[Backend.getIdentifiedDbms()].is_dba.query % kb.data.currentUser.split("")[0]
ValueError: empty separator
```

**Comment by stamparm** [comment] 2024-02-27 12:54
duplicate of #5646

**Closed by stamparm** 2024-02-27 12:54 UTC
