### ISSUE TITLE
Unhandled exception (#ba758559)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3933] opened 2019-09-17 05:34 UTC
```
Running version: 1.3.7.7#dev
Python version: 2.7.15
Operating system: Windows-10-10.0.17134
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2634, in init
    _setMultipleTargets()
  File "lib/core/update.py", line 117, in update
    finally:
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by stamparm** [comment] 2019-09-17 06:07
Duplicate of #3898 (patched)

**Closed by stamparm** 2019-09-17 06:07 UTC
