### ISSUE TITLE
Unhandled exception (#72e0a61a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4834] opened 2021-09-28 13:17 UTC
```
Running version: 1.5.9.7#dev
Python version: 2.7.11
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py -r ************************************ --batch -p Referer --level 3 --is-dba
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 73, in action
    conf.dumper.dba(conf.dbmsHandler.isDba())
  File "plugins/generic/users.py", line 83, in isDba
    self.getCurrentUser()
  File "plugins/generic/users.py", line 72, in getCurrentUser
    kb.data.currentUser = unArrayizeValue(inject.getValue(query))
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 308, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 154, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 126, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected." % threadData.lastCode
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-09-29 11:05
Duplicate of #4824 (fixed)

**Closed by stamparm** 2021-09-29 11:05 UTC
