### ISSUE TITLE
How can I execute queries from a loop?

### ISSUE THREAD

**Issue by abdooz** [sqlmapproject/sqlmap#1181] opened 2015-02-28 04:14 UTC
Hello,
I tried to dump rows from a table using Blind injection technique, but some results are duplicated (even the ID column is duplicated). I don't know what the exact issue is.
The solution I thought about is to execute each SELECT statement separately. In PHP, it would be done like this:
```php
for ( $id = 1; $id <= 1000; ++$id )
      mysql_query("select column from table where id=$id");
```
That makes sure I will get a different result each time.
But how can I do this with sqlmap? How can I execute each SELECT statement separately, and get a unique result each time?

**Comment by stamparm** [comment] 2015-02-28 05:50
You can't do that from sqlmap. Which version of sqlmap are you using?

Also, you are messing things up here a bit. You are saying that each row should have a different ID and I am not sure why do you say that.

**Comment by abdooz** [comment] 2015-02-28 14:36
I am using the latest dev version from github.
For example, "SELECT id from user". Some results are duplicated like:
id = 105
id = 106
id = 105

And when I execute "SELECT COUNT(id) from user where id=105", the count is 1. So I don't know why  I am getting duplicate results.

**Comment by stamparm** [comment] 2015-03-01 17:43
Can you please send me url to miroslav@sqlmap.org. I really can't reproduce
this behavior. Also, you are the first one that report this problem for
MySQL?

**Comment by stamparm** [comment] 2015-04-08 12:51
Closing due to no

**Closed by stamparm** 2015-04-08 12:51 UTC
