### ISSUE TITLE
Unhandled exception (#ab1751d4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4045] opened 2019-12-18 01:58 UTC
```
Running version: 1.3.8.27#dev
Python version: 2.7.16
Operating system: Windows-10-10.0.17763
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    sys.stderr = StdDbOut(conf.taskid, messagetype="stderr")
  File "lib/core/option.py", line 2664, in init
    _setPreprocessFunctions()
  File "lib/core/update.py", line 117, in update
    finally:
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by stamparm** [comment] 2019-12-18 09:07
Duplicate of #3898 (patched)

**Closed by stamparm** 2019-12-18 09:07 UTC
