### ISSUE TITLE
Unhandled exception (#0faa1489)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4674] opened 2021-05-08 08:14 UTC
```
Running version: 1.4.12.39#dev
Python version: 2.7.16
Operating system: Linux-4.19.0-6-amd64-x86_64-with-debian-10.2
Command line: /usr/bin/sqlmap -u ************************************************ --os-shell
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 216, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 703, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 221, in action
    conf.dbmsHandler.osShell()
  File "/share/sqlmap/plugins/generic/takeover.py", line 85, in osShell
    self.initEnv(web=web)
  File "/share/sqlmap/lib/takeover/abstraction.py", line 219, in initEnv
    success = self.udfInjectSys()
  File "/share/sqlmap/lib/takeover/udf.py", line 183, in udfInjectSys
    return self.udfInjectCore(self.sysUdfs)
  File "/share/sqlmap/lib/takeover/udf.py", line 147, in udfInjectCore
    self.udfSetRemotePath()
  File "/share/sqlmap/plugins/dbms/mysql/takeover.py", line 41, in udfSetRemotePath
    if distutils.version.LooseVersion(banVer) >= distutils.version.LooseVersion("5.0.67"):
  File "/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: LooseVersion instance has no attribute 'version'
```

**Comment by stamparm** [comment] 2021-05-10 08:38
Duplicate of #4504 (fixed)

**Closed by stamparm** 2021-05-10 08:38 UTC
