### ISSUE TITLE
Unhandled exception (#d52ed878)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3291] opened 2018-10-15 10:58 UTC
```
Running version: 1.2.9.38#dev
Python version: 2.7.15
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --url=******************************************************* --threads=10 --tamper=space2comment.py --retries=0 --timeout=10 --dbms=MYSQL --technique=EUS --random-agent --is-dba --exclude-sysdbs --current-db --answers=**************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 153, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 31, in <module>
    from plugins.dbms.oracle import OracleMap
  File "plugins/dbms/oracle/__init__.py", line 13, in <module>
    from plugins.dbms.oracle.fingerprint import Fingerprint
ImportError: No module named fingerprint
```

**Comment by stamparm** [comment] 2018-10-15 14:29
Duplicate of #3288

**Closed by stamparm** 2018-10-15 14:29 UTC
