### ISSUE TITLE
pymysql doesn't work

### ISSUE THREAD

**Issue by Daybr4ak** [sqlmapproject/sqlmap#4217] opened 2020-05-27 03:43 UTC
Even if I downloaded pymysql and installed, sqlmap -d can't to be used. but old version can be used normally. :(

**Comment by stamparm** [comment] 2020-05-27 13:51
Duplicate of #4213 

p.s. please spare me of "old version can be used normally" without providing any kind of information

**Closed by stamparm** 2020-05-27 13:51 UTC
Labels: bug report
