### ISSUE TITLE
Unhandled exception (#43b71552)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2815] opened 2017-12-05 05:46 UTC
```
sqlmap version: 1.1.11.39#dev
Python version: 2.7.9
Operating system: nt
Command line: sqlmap.py -r c:\c.txt -v1 --current-db --random-agent -v 2 --tamper=space2hash.py,modsecurityversioned.py
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 547, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 412, in checkSqlInjection
    templatePayload = agent.payload(place, parameter, value="", newValue=origValue, where=where)
  File "lib/core/agent.py", line 170, in payload
    retVal = paramString.replace(_, self.addPayloadDelimiters(newValue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 1441: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-12-05 10:34
Duplicate of #2766 (fixed)

**Closed by stamparm** 2017-12-05 10:34 UTC
Labels: duplicate
