### ISSUE TITLE
Unhandled exception (#58d6bded)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1640] opened 2016-01-08 10:46 UTC
```
sqlmap version: 1.0-dev-b427f6c
Python version: 2.7.10
Operating system: posix
Command line: sqlmap.py -u **************************************************************** --data=************************* -p dia --dbs
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 32, in action
    setHandler()
  File "lib/controller/handler.py", line 103, in setHandler
    if handler.checkDbms():
  File "plugins/dbms/mssqlserver/fingerprint.py", line 97, in checkDbms
    result = inject.checkBooleanExpression(check)
  File "lib/request/inject.py", line 490, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, charsetType=CHARSET_TYPE.BINARY, suppressOutput=True, expectingNone=expectingNone)
  File "lib/request/inject.py", line 412, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 436, in errorUse
    value = _errorFields(expression, expressionFields, expressionFieldsList)
  File "lib/techniques/error/use.py", line 228, in _errorFields
    output = NULL if emptyFields and field in emptyFields else _oneShotErrorUse(expressionReplaced, field)
  File "lib/techniques/error/use.py", line 201, in _oneShotErrorUse
    retVal = re.sub(r"&#x([^;]+);", lambda match: chr(int(match.group(1), 16)), retVal)
  File "usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2016-01-08 10:47
Duplicate of #1639 (fixed this moment)

**Closed by stamparm** 2016-01-08 10:47 UTC
