### ISSUE TITLE
Unhandled exception (#79bb66a6)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2130] opened 2016-08-25 06:19 UTC
```
sqlmap version: 1.0.7.9#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ******************************************************
Technique: UNION
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 522, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 761, in checkSqlInjection
    urllib2.urlopen(uurl)
  File "lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "lib/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "lib/urllib2.py", line 449, in _open
    '_open', req)
  File "lib/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "lib/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "lib/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "lib/httplib.py", line 1074, in getresponse
    response.begin()
  File "lib/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "lib/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by stamparm** [comment] 2016-08-25 15:16
Duplicate of #2020 (there has never been a line `urllib2.urlopen(uurl)`)

**Closed by stamparm** 2016-08-25 15:16 UTC
