### ISSUE TITLE
Unhandled exception (#cce98436)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2854] opened 2017-12-28 12:24 UTC
```
sqlmap version: 1.1.12.29#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u *************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 547, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 476, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 721, in getPage
    return Connect._retryProxy(**kwargs)
  File "lib/request/connect.py", line 182, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "lib/request/connect.py", line 130, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "lib/request/connect.py", line 306, in getPage
    url = asciifyUrl(url)
  File "lib/core/decorators.py", line 20, in _
    cache[key] = f(*args, **kwargs)
  File "lib/core/common.py", line 3858, in asciifyUrl
    path = quote(parts.path, safe='/')
  File "lib/core/common.py", line 3852, in quote
    if s.encode("ascii", "replace") != s or forceQuote:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 17: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-12-28 12:26
Duplicate of #2853

**Closed by stamparm** 2017-12-28 12:26 UTC
Labels: duplicate
