### ISSUE TITLE
Unhandled exception (#e46a2e90)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3015] opened 2018-03-29 14:03 UTC
```
sqlmap version: 1.1.10.9#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ********************************************* --tables
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 155, in main
    start()
  File "lib/controller/controller.py", line 653, in start
    action()
  File "lib/controller/action.py", line 103, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/generic/databases.py", line 279, in getTables
    values = inject.getValue(query, blind=False, time=False)
  File "lib/request/inject.py", line 388, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 330, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 390, in unionUse
    runThreads(numThreads, unionThread)
  File "lib/core/threads.py", line 170, in runThreads
    print
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-03-29 14:27
Duplicate of #2790 (fixed)

**Closed by stamparm** 2018-03-29 14:27 UTC
