### ISSUE TITLE
Unhandled exception (#56657cc4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1862] opened 2016-05-12 19:05 UTC
```
sqlmap version: 1.0.5.0#dev
Python version: 2.7.11+
Operating system: posix
Command line: /usr/bin/sqlmap -u **********************************
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 105, in main
    init()
  File "share/sqlmap/lib/core/option.py", line 2578, in init
    _setSocketPreConnect()
  File "share/sqlmap/lib/core/option.py", line 1066, in _setSocketPreConnect
    thread.start()
  File "lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

**Comment by stamparm** [comment] 2016-05-12 22:32
Duplicate of #1853

**Closed by stamparm** 2016-05-12 22:32 UTC
