### ISSUE TITLE
Unhandled exception (#33b3e103)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1089] opened 2015-01-03 05:27 UTC
```
sqlmap version: 1.0-dev-nongit-20141212
Python version: 2.7.2
Operating system: posix
Command line: sdl --disable-col -c /init.usbdiag.sh -v 1 --timeout=30 --retries=3 --threads=1 --risk=1 --level=1 --technique=BEUSTQ
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/sqlmap.py", line 76, in main
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 2297, in initOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 1935, in _mergeOptions
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/parse/configfile.py", line 68, in configFileParser
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 881, in open
IOError: [Errno 13] Permission denied: u'/init.usbdiag.sh'
```

**Comment by stamparm** [comment] 2015-01-03 21:14
Duplicate of #1075

**Closed by stamparm** 2015-01-03 21:14 UTC
