### ISSUE TITLE
Unhandled exception (#ee393040)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4288] opened 2020-07-31 08:47 UTC
```
Running version: 1.4.7.16#dev
Python version: 2.7.18
Operating system: Linux-5.5.0-kali2-amd64-x86_64-with-debian-****-rolling
Command line: /usr/bin/sqlmap -u ******************************************** --level 5 --risk 3 -a
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 215, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 592, in start
    injection = checkSqlInjection(place, parameter, value)
  File "/share/sqlmap/lib/controller/checks.py", line 505, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "/share/sqlmap/lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/connect.py", line 1367, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/share/sqlmap/lib/request/connect.py", line 831, in getPage
    processResponse(page, responseHeaders, code, status)
  File "/share/sqlmap/lib/request/basic.py", line 386, in processResponse
    if not kb.tableFrom and Backend.getIdentifiedDbms() in (DBMS.ACCESS,):
  File "/share/sqlmap/lib/core/common.py", line 509, in getIdentifiedDbms
    elif Backend.getForcedDbms() is not None:
  File "/share/sqlmap/lib/core/common.py", line 473, in getForcedDbms
    return aliasToDbmsEnum(conf.get("forceDbms")) or aliasToDbmsEnum(kb.get("forcedDbms"))
  File "/share/sqlmap/lib/core/decorators.py", line 42, in _f
    key = int(hashlib.md5("|".join(str(_) for _ in (f, args, kwargs)).encode(UNICODE_ENCODING)).hexdigest(), 16) & 0x7fffffffffffffff
ValueError: invalid literal for int() with base 16: '9\x0b03~~\x18\x18\xd0\xd19\x9d\x8956\xee0\xd918211\xc85c0\xf614j4'
```

**Comment by stamparm** [comment] 2020-07-31 14:32
Duplicate of #4281

**Closed by stamparm** 2020-07-31 14:32 UTC
