### ISSUE TITLE
Unhandled exception (#48b282c5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4477] opened 2020-12-14 11:42 UTC
```
Running version: 1.4.12.7#dev
Python version: 2.7.18
Operating system: Linux-4.19.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap --url=********************************************************************************************** --random-agent --level=5 --risk=3 --dbms=MySQL --dbs
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 215, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 592, in start
    injection = checkSqlInjection(place, parameter, value)
  File "/share/sqlmap/lib/controller/checks.py", line 506, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "/share/sqlmap/lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/connect.py", line 1413, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/share/sqlmap/lib/request/connect.py", line 890, in getPage
    logHeaders = getUnicode("".join(responseHeaders.headers).strip())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 12: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2020-12-14 11:46
Duplicate of #4469 (fixed)

**Closed by stamparm** 2020-12-14 11:46 UTC
