### ISSUE TITLE
Unhandled exception (#58fd8e38)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1489] opened 2015-10-27 07:26 UTC
```
sqlmap version: 1.0-dev-nongit-20150729
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ********************************************* --os-cmd=net user
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 625, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 57, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 204, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 184, in udfInjectSys
    self.udfSetLocalPaths()
  File "plugins/dbms/mysql/takeover.py", line 94, in udfSetLocalPaths
    self.udfLocalFile = decloakToTemp(_)
  File "lib/core/common.py", line 3868, in decloakToTemp
    handle, filename = tempfile.mkstemp(prefix=prefix, suffix=suffix)
  File "lib/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "lib/tempfile.py", line 242, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "lib/ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 7: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2015-10-27 07:51
Duplicate of #1415 (fixed)

**Closed by stamparm** 2015-10-27 07:51 UTC
