### ISSUE TITLE
Unhandled exception (#f01a397d)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3561] opened 2019-04-02 04:11 UTC
```
Running version: 1.3.3.80#dev
Python version: 2.7.16
Operating system: Windows-10-10.0.17763
Command line: sqlmap.py -u *********************************** --os-cmd=ipconfig
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 172, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 667, in start
    action()
  File "lib/controller/action.py", line 201, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 58, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 198, in initEnv
    self.webInit()
  File "lib/takeover/web.py", line 382, in webInit
    if not self.webUpload(backdoorName, posixToNtSlashes(directory) if Backend.isOs(OS.WINDOWS) else directory, content=backdoorContent):
  File "lib/takeover/web.py", line 103, in webUpload
    return self._webFileStreamUpload(stream, destFileName, directory)
  File "lib/takeover/web.py", line 124, in _webFileStreamUpload
    page, _, _ = Request.getPage(url=self.webStagerUrl, multipart=multipartParams, raise404=False)
  File "lib/request/connect.py", line 494, in getPage
    conn = _urllib.request.urlopen(req)
  File "/lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/lib/urllib2.py", line 427, in open
    req = meth(req)
  File "thirdparty/multipart/multipartpost.py", line 67, in http_request
    boundary, data = self.multipart_encode(v_vars, v_files)
  File "thirdparty/multipart/multipartpost.py", line 90, in multipart_encode
    file_size = os.fstat(fd.fileno())[stat.ST_SIZE] if isinstance(fd, file) else fd.len
AttributeError: '_io.BytesIO' object has no attribute 'len'
```

**Comment by stamparm** [comment] 2019-04-03 09:18
Duplicate of #3560 (fixed)

**Closed by stamparm** 2019-04-03 09:18 UTC
