### ISSUE TITLE
Unhandled exception (#2620e41a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2183] opened 2016-09-24 21:48 UTC
```
sqlmap version: 1.0.9.24#dev
Python version: 2.7.12
Operating system: posix
Command line: sqlmap.py -u ****************************************************************** --dbs
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 100, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 140, in getDbs
    db = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/request/inject.py", line 429, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 157, in _goInferenceProxy
    _, _, _, _, _, expressionFieldsList, expressionFields, _ = agent.getFields(expression)
  File "lib/core/agent.py", line 532, in getFields
    if re.search("\A\w+\(.*\)", fieldsToCastStr, re.I) or (fieldsSelectCase and "WHEN use" not in query) or fieldsSubstr:
  File "usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2016-09-26 09:06
Duplicate of #2176 (fixed). Please update

**Closed by stamparm** 2016-09-26 09:06 UTC
