### ISSUE TITLE
Unhandled exception (#a5cd99da)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3007] opened 2018-03-26 01:29 UTC
```
Running version: 1.2.3.4#dev
Python version: 2.7.13
Operating system: Linux-4.9.0-kali3-686-pae-i686-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap -r 924.txt
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 157, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 514, in start
    check = checkDynParam(place, parameter, value)
  File "share/sqlmap/lib/controller/checks.py", line 1106, in checkDynParam
    dynResult = Request.queryPage(payload, place, raise404=False)
  File "share/sqlmap/lib/request/connect.py", line 938, in queryPage
    auxHeaders[value.split(',')[0]] = value.split(',', 1)[1]
IndexError: list index out of range
```

**Comment by stamparm** [comment] 2018-03-26 12:51
Duplicate of #2969 (fixed)

**Closed by stamparm** 2018-03-26 12:51 UTC
