### ISSUE TITLE
Unhandled exception (#4a496f3b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3008] opened 2018-03-26 08:06 UTC
```
sqlmap version: 1.1.9.9#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ************************************************************************************************* -D ************** -T ***** --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 155, in main
    start()
  File "lib/controller/controller.py", line 653, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 222, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 407, in getValue
    value = _goUnion(query, unpack, dump)
  File "lib/request/inject.py", line 330, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 390, in unionUse
    runThreads(numThreads, unionThread)
  File "lib/core/threads.py", line 187, in runThreads
    print
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-03-26 12:51
Duplicate of #2790 (fixed)

**Closed by stamparm** 2018-03-26 12:51 UTC
Labels: duplicate
