### ISSUE TITLE
Using sqlmap as python library, is that possible?

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#4177] opened 2020-04-27 10:50 UTC
Hi

Is it possible to use sqlmap as a python library to be called directly from other python scripts, or is it only a CLI tool?

Thanks

**Comment by stamparm** [comment] 2020-04-27 12:55
Duplicate of #2968

**Closed by stamparm** 2020-04-27 12:55 UTC
Labels: duplicate, feature request

**Comment by javixeneize** [comment] 2020-04-27 12:59
Thanks. It means that it is still not available to be used as a dependency. Is this something you might consider in the future?

**Comment by stamparm** [comment] 2020-04-27 13:04
Sorry, but no. The same thing(s) apply as in the referenced Issue
