### ISSUE TITLE
Unhandled exception (#2cdb3e6a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1908] opened 2016-05-27 14:46 UTC
```
sqlmap version: 1.0.5.59#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -g *********** -passwords
Technique: UNION
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 138, in main
    start()
  File "lib/controller/controller.py", line 662, in start
    _saveToResultsFile()
  File "lib/controller/controller.py", line 229, in _saveToResultsFile
    for injection in kb.injectionections + kb.falsePositives:
  File "lib/core/datatype.py", line 44, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'injectionections'
```

**Comment by stamparm** [comment] 2016-05-27 14:48
Duplicate of #1892 (fixed)

**Closed by stamparm** 2016-05-27 14:48 UTC
