### ISSUE TITLE
Error after script is done testing a url

### ISSUE THREAD

**Issue by miktoro** [sqlmapproject/sqlmap#4605] opened 2021-03-13 21:19 UTC
Hello,

Not sure if this is a bug or a feature on my laptop but the program runs just fine until it says "ending @ time xxx" and out comes the error:

multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

And the log file it creates is empty. I have tried different command options like wizard and changing the levels, crawl, risk and -a all settings but it always ends up with that error. I have mac osx catalina and python 3.8.1. I did have a packet tqdm that had a bug that produced those errors but i updated it so it wasnt that one. Thanks in advance.

**Comment by stamparm** [comment] 2021-03-15 10:07
Duplicate of #4367

p.s. this can be ignored up until I get my hands on one Mac. Thing is that I don't have the means to reproduce this and properly debug

**Closed by stamparm** 2021-03-15 10:07 UTC
Labels: feature request
