### ISSUE TITLE
Accept invalid certificate

### ISSUE THREAD

**Issue by analyserdmz** [sqlmapproject/sqlmap#4532] opened 2021-01-08 09:50 UTC
**Describe the bug**
I am trying to inject a valid, injectable parameter with SQLmap, but since the certificate is invalid (expired whatsoever), it won't accept it.

**To Reproduce**
Just run SQLmap against invalid SSL certificate host, with or without --force-ssl and it will respond with **[CRITICAL] can't establish SSL connection**.

**Expected behavior**
Accept the certificate anyway (?) like when we manually accept it through our browser.

**Running environment:**
 - sqlmap version: 1.4.7.25#dev
 - Operating system: Microsoft Windows 10
 - Python version: 3.9.0

**Comment by stamparm** [comment] 2021-01-08 12:23
Duplicate of #4462 (fixed with 1.4.12.8)

**Closed by stamparm** 2021-01-08 12:23 UTC
Labels: bug report
