### ISSUE TITLE
sqlmap error after two hours of work

### ISSUE THREAD

**Issue by 4val0v** [sqlmapproject/sqlmap#3000] opened 2018-03-20 13:57 UTC
## What's the problem (or question)?
Everything worked fine, but after two hours of work, an error occurred
```
[22:15:31] [INFO] retrieved: 0
[22:15:35] [INFO] retrieved: port
[22:15:39] [INFO] retrieved: master.slave
Traceback (most recent call last):
  File "C:\Users\root\Desktop\sqlmap-master\sqlmap.py", line 157, in main
    start()
  File "C:\Users\root\Desktop\sqlmap-master\lib\controller\controller.py", line 651, in start
    action()
  File "C:\Users\root\Desktop\sqlmap-master\lib\controller\action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "C:\Users\root\Desktop\sqlmap-master\plugins\generic\entries.py", line 406, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 435, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 288, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 131, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 103, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\techniques\blind\inference.py", line 616, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "C:\Users\root\Desktop\sqlmap-master\lib\techniques\blind\inference.py", line 334, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\connect.py", line 1234, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "C:\Python27\lib\urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "C:\Python27\lib\urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

[22:16:17] [ERROR] please contact 'miroslav@sqlmap.org' with details for this issue as he is trying to reproduce it for long time

[*] shutting down at 22:16:17 
```

## What are the running context details?
* Installation method: git clone or zip
* Client OS (Microsoft Windows 10)
* Program version (1.2.3.18#dev): 
* Target DBMS (MySQL): 
* SQLi techniques found by sqlmap (boolean-based blind)

**Comment by stamparm** [comment] 2018-03-20 14:04
@4val0v are you able to reproduce it (on following runs) or it happened just once? Thing is that (as the message says) I am trying to find a source of this for a long time (e.g. #2966, #2947, #2886, #2875, #2826, #2885, #2830)

**Comment by 4val0v** [comment] 2018-03-20 18:20
Да, ошибка повторилась спустя некоторого времени
Если быть точнее то в 17 часов запустил повторно
`sqlmap.py -r target.txt --dump-format=SQLite --dbms=MySQL -D MediaDB -T profiles --dump`
Спустя минуты `[INFO] resumed:` пошли `[INFO] retrieved:`
Все было очень хорошо, до 20:41 после чего опять повторилась ошибка:
```
[20:41:26] [INFO] retrieved: 0
[20:41:30] [INFO] retrieved:
[20:41:34] [INFO] retrieved: 0
[20:41:38] [INFO] retrieved: 0
[20:41:42] [INFO] retrieved:
Traceback (most recent call last):
  File "C:\Users\root\Desktop\sqlmap-master\sqlmap.py", line 157, in main
    start()
  File "C:\Users\root\Desktop\sqlmap-master\lib\controller\controller.py", line 651, in start
    action()
  File "C:\Users\root\Desktop\sqlmap-master\lib\controller\action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "C:\Users\root\Desktop\sqlmap-master\plugins\generic\entries.py", line 406, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 435, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 288, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 131, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\inject.py", line 103, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "C:\Users\root\Desktop\sqlmap-master\lib\techniques\blind\inference.py", line 616, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "C:\Users\root\Desktop\sqlmap-master\lib\techniques\blind\inference.py", line 334, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\connect.py", line 1234, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Users\root\Desktop\sqlmap-master\lib\request\connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "C:\Python27\lib\urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "C:\Python27\lib\urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

[20:41:46] [ERROR] please contact 'miroslav@sqlmap.org' with details for this issue as he is trying to reproduce it for long time

[*] shutting down at 20:41:46
```
Мирослав подскажите **с какими параметрами запустить**? _(буду очень рад если вам поможет выловить данную ошибку)_
И возможно есть возможность отладки, поставить точки остановки и посмотреть из-за чего вылетает ?

**Comment by stamparm** [comment] 2018-03-20 22:30
@4val0v sorry, I am from Croatia, not from Russia. By using Google translate I was able to understand what you wrote.

1) Are there any non-ASCII (e.g. Cyrillic) letters inside the provided URL and/or request file (I don't know which method you used)
2) You can try to rerun everything with `-t traffic.txt` and either send me the content or take a look yourself into it, especially for any weird stuff inside last request/response
3) If you know Python, you could take a look into the `connect.py/getPage()` and put debugging prints of variable url at different spots of that same function. I am interested where variable `url` becomes `None` as it must be a string when provided to that same function
4) Also, there is an option for you to provide me with all data to reproduce this directly to `miroslav@sqlmap.org`

**Comment by 4val0v** [comment] 2018-03-20 23:16
@stamparm 

1. GET request, only ASCII characters
2. Launched with the -t traffic.tht, has been working for a few hours, more than 356,000 queries have been sent, I hope the error will repeat
3. I am not familiar in Python, and catch this error will be difficult.
Is it possible to write to the file also the data from the variables, so that you can see at what stage it went wrong ?

**Comment by stamparm** [comment] 2018-03-20 23:24
I thought of that (dumping all variables across all functions in traceback), but I believe that the most important variable (`url` inside function `getPage()`) is being overridden for a couple of times before the crash. Hence, I am not sure that this would be enough.

Maybe traffic file will show something, though, I would not bet on it

**Comment by 4val0v** [comment] 2018-03-21 10:12
At 10 o'clock again there was an error
the traffic file turned out to be more than a gigabyte

Alas, there is nothing useful in this file
There are request and response, until the moment everything fell down

Tell me how to fix executable files so that they show more information (variables) ?

**Comment by 4val0v** [comment] 2018-03-21 11:37
It would be very good to be able to run with the `--debug` parameter
To write file debug all events

**Comment by stamparm** [comment] 2018-03-21 11:40
I've said everything in https://github.com/sqlmapproject/sqlmap/issues/3000#issuecomment-374791202. Problem is that the variable `url` is overridden somewhere inside the `getPage()`. By the time of crash nothing useful can be found from variables itself. I need to know the exact location inside the `getPage()` where `url` is set to `None` and that can be done only from within the code itself.

**Comment by 4val0v** [comment] 2018-03-21 14:11
@stamparm Miroslav, I do not know the python programming language :sweat::tired_face:
Installed the IDE PyCharm, to debug [connect.py/getPage()](https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py) step by step very hemorrhoids and it will take a year for this

Prompt in what locations to place this code `traceback.print_stack()`?

**Comment by stamparm** [comment] 2018-03-21 15:55
I am closing this down as duplicate of #2886. Will wait for some other example.

That bug can't be debugged by placing `traceback.print_stack()` at random places as that doesn't make any sense. I've already described in previous comments that there is a place inside the `getPage()` where `url` is being changed to `None`.

**Closed by stamparm** 2018-03-21 15:55 UTC

**Comment by 4val0v** [comment] 2018-03-21 19:24
Maybe it's something that will give:
![image](https://user-images.githubusercontent.com/11297476/37732434-aa164f40-2d4d-11e8-91c7-ffa8f12593b8.png)
`[DEBUG] running code integrity check` - this message appears after which everything crumbles

**Comment by Ekultek** [comment] 2018-03-21 22:44
That would mean that you edited the code somewhere

**Comment by stamparm** [comment] 2018-03-22 09:46
`[DEBUG] running code integrity check` <- this is just a check to see if there were any code changes prior to sending an automated error report. Nothing special regarding your issue

**Comment by 4val0v** [comment] 2018-03-23 12:30
@Ekultek I did not edit the code
Updated for version 1.2.3.41 #dev
```
[14:09:39] [PAYLOAD] %' AND ORD(MID((SELECT IFNULL(CAST(password AS CHAR),0x20) FROM xxxxx.users ORDER BY exp LIMIT 246,1),17,1))>51 AND '%'='

[14:09:39] [DEBUG] running code integrity check
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "C:\Users\roooo\Desktop\sqlmap\lib\controller\controller.py", line 650, in start
    action()
  File "C:\Users\roooo\Desktop\sqlmap\lib\controller\action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "C:\Users\roooo\Desktop\sqlmap\plugins\generic\entries.py", line 409, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\inject.py", line 432, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\inject.py", line 131, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\inject.py", line 103, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "C:\Users\roooo\Desktop\sqlmap\lib\techniques\blind\inference.py", line 616, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "C:\Users\roooo\Desktop\sqlmap\lib\techniques\blind\inference.py", line 334, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\connect.py", line 1237, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Users\roooo\Desktop\sqlmap\lib\request\connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "C:\Python27\lib\urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "C:\Python27\lib\urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

[14:09:42] [ERROR] please contact 'miroslav@sqlmap.org' with details for this issue as he is trying to reproduce it for long time

[*] shutting down at 14:09:42
```

@stamparm if I give you a URL you can solve this problem?

**Comment by stamparm** [comment] 2018-03-23 14:43
@4val0v if I'll be able to reproduce it, then I am pretty sure that I'll be able to solve the problem
