### ISSUE TITLE
Unhandled exception (#70a99fb7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1998] opened 2016-07-01 05:08 UTC
```
sqlmap version: 1.0-dev-nongit-201512140967
Python version: 2.7.2
Operating system: nt
Command line: sqlmap.py -u **************************** --forms --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 101, in main
    init()
  File "lib/core/option.py", line 2571, in init
    _findPageForms()
  File "lib/core/option.py", line 621, in _findPageForms
    findPageForms(page, conf.url, True, True)
  File "lib/core/common.py", line 3570, in findPageForms
    forms = ParseResponse(response, backwards_compat=False)
  File "thirdparty/clientform/clientform.py", line 1066, in ParseResponse
    return _ParseFileEx(response, response.geturl(), *args, **kwds)[1:]
  File "thirdparty/clientform/clientform.py", line 1139, in _ParseFileEx
    type, name, attrs, select_default=select_default, index=ii*10)
  File "thirdparty/clientform/clientform.py", line 2853, in new_control
    control = klass(type, name, a, index)
  File "thirdparty/clientform/clientform.py", line 2454, in __init__
    if self.value is None and not self.disabled: self.value = ""
  File "thirdparty/clientform/clientform.py", line 1341, in __setattr__
    raise AttributeError("control '%s' is readonly" % self.name)
AttributeError: control 'None' is readonly
```

**Comment by stamparm** [comment] 2016-07-01 13:58
Ancient duplicate of #1385 (fixed)

**Closed by stamparm** 2016-07-01 13:58 UTC
