### ISSUE TITLE
Unhandled exception (#419d56b0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4713] opened 2021-06-16 01:11 UTC
```
Running version: 1.3.4#stable
Python version: 2.7.11
Operating system: Windows-10-10.0.19041
Command line: sqlmap.py -u ****************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 165, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 29, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
    from plugins.dbms.mssqlserver.enumeration import Enumeration
  File "plugins/dbms/mssqlserver/enumeration.py", line 32, in <module>
    from plugins.generic.enumeration import Enumeration as GenericEnumeration
  File "plugins/generic/enumeration.py", line 20, in <module>
    from plugins.generic.entries import Entries
  File "plugins/generic/entries.py", line 46, in <module>
    from lib.utils.hash import attackDumpedTable
  File "lib/utils/hash.py", line 17, in <module>
    import multiprocessing
  File "/lib/multiprocessing/__init__.py", line 64, in <module>
    from multiprocessing.process import Process, current_process, active_children
  File "/lib/multiprocessing/process.py", line 1
SyntaxError: Non-ASCII character '\xec' in file /lib/multiprocessing/process.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by stamparm** [comment] 2021-06-16 21:24
Duplicate of #3752 (patched)

**Closed by stamparm** 2021-06-16 21:24 UTC
