### ISSUE TITLE
can't use touch keyboard

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3699] opened 2019-05-24 13:25 UTC
press `Up Arrow` key --> `^[[A` 
(when I using `--sqlmap-shell`)

```
sqlmap-shell> ^[[A
```

**Comment by huitc** [comment] 2019-05-24 13:53
or... just me???.... (termux

**Comment by huitc** [comment] 2019-05-24 16:21
https://github.com/sqlmapproject/sqlmap/issues/3702

**Comment by stamparm** [comment] 2019-05-24 20:31
Duplicate of #3702

**Closed by stamparm** 2019-05-24 20:31 UTC
Labels: bug report
