### ISSUE TITLE
Unhandled exception (#628e6962)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4829] opened 2021-09-26 15:19 UTC
```
Running version: 1.5.9.7#dev
Python version: 2.7.16
Operating system: Darwin-20.6.0-x86_64-i386-64bit
Command line: sqlmap.py -u ************************************************** --random-agent -D ****** -C ************ --dump --threads=8 --hex
Technique: BOOLEAN
Back-end DBMS: PostgreSQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 163, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 308, in dumpTable
    count = inject.getValue(query, union=False, error=False, expected=EXPECTED.INT, charsetType=CHARSET_TYPE.DIGITS)
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 308, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 154, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 126, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected."
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-09-26 19:16
Duplicate of #4824 (fixed)

**Closed by stamparm** 2021-09-26 19:16 UTC
