### ISSUE TITLE
Unhandled exception (#7bb13bf6)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4078] opened 2020-01-16 02:09 UTC
```
Running version: 1.3.4.2#dev
Python version: 2.7.17
Operating system: Windows-10-10.0.17134
Command line: sqlmap.py -d ****************************************** --os-shell
Technique: DIRECT
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 172, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 279, in start
    action()
  File "lib/controller/action.py", line 204, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 81, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 217, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 180, in udfInjectSys
    self.udfSetLocalPaths()
  File "plugins/dbms/mysql/takeover.py", line 94, in udfSetLocalPaths
    self.udfLocalFile = decloakToTemp(_)
  File "lib/core/common.py", line 4539, in decloakToTemp
    content = decloak(filename)
  File "extra/cloak/cloak.py", line 40, in decloak
    with open(inputFile, "rb") as f:
IOError: [Errno 2] No such file or directory: u'D:\\Python27\\Scripts\\sqlmap\\udf\\mysql\\linux\\32\\lib_mysqludf_sys.so_'
```

**Comment by stamparm** [comment] 2020-01-20 14:46
Duplicate of #3648 (patched)

**Closed by stamparm** 2020-01-20 14:46 UTC
