### ISSUE TITLE
Unhandled exception (#fb8899ad)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2899] opened 2018-01-29 23:51 UTC
```
sqlmap version: 1.0.10.6#dev
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -u **************************************** -D *********** -T ****** -C ********************************************************** --dump --thread=9
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 151, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 334, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 429, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 95, in _goInference
    length = queryOutputLength(injExpression, payload)
  File "lib/techniques/blind/inference.py", line 665, in queryOutputLength
    count, length = bisection(payload, lengthExprUnescaped, charsetType=CHARSET_TYPE.DIGITS)
  File "lib/techniques/blind/inference.py", line 638, in bisection
    dataToStdout("\n")
  File "lib/core/common.py", line 891, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-01-30 09:56
Duplicate of #2790 (fixed)

**Closed by stamparm** 2018-01-30 09:56 UTC
