### ISSUE TITLE
Unhandled exception (#bc901007)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3711] opened 2019-05-25 06:30 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.13
Operating system: Windows-7-6.1.7601-SP1
Command line: sqlmap.py -u ****************************************** -D ************* -T member -C **************************************************** --dump
Technique: ERROR
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 205, in dumpTable
    value = inject.getValue(query, blind=False, time=False, dump=True) or ""
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 430, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 449, in errorUse
    value = _errorFields(expression, expressionFields, expressionFieldsList)
  File "lib/techniques/error/use.py", line 256, in _errorFields
    dataToStdout("%s\n" % status)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self._write(text[start:end])
  File "thirdparty/colorama/ansitowin32.py", line 182, in _write
    self.wrapped.write(text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 17: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-26 13:53
Duplicate of #3700

**Closed by stamparm** 2019-05-26 13:53 UTC
