### ISSUE TITLE
Unhandled exception (#e37310c7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2887] opened 2018-01-18 11:27 UTC
```
sqlmap version: 1.1.11.40#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u ************************************************************************************************************************************ --time-sec=5 --level 5 --threads 10 --risk=3 --eta --charset=ISO8859-1-1987 --delay 3 --sql-shell
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 133, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 107, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 50, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "lib/request/inject.py", line 434, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 287, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 130, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 102, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 628, in bisection
    progress.progress(time.time() - charStart, index)
NameError: global name 'charStart' is not defined
```

**Comment by stamparm** [comment] 2018-01-19 11:31
Duplicate of #2824 (fixed)

**Closed by stamparm** 2018-01-19 11:31 UTC
