### ISSUE TITLE
Unhandled exception (#1313009e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3685] opened 2019-05-19 15:15 UTC
```
Running version: 1.3.3.10#dev
Python version: 2.7.16
Operating system: Windows-2003Server-5.2.3790-SP2
Command line: sqlmap.py -g **************** Cat_id = site:com.vn --random-agent -f --batch --answer=*************************************
Technique: UNION
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 167, in main
    start()
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 549, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 1028, in heuristicCheckSqlInjection
    page, _, _ = Request.queryPage(payload, place, content=True, raise404=False)
  File "lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1280, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 608, in getPage
    logHTTPTraffic(requestMsg, "%s%s\r\n\r\n%s" % (responseMsg, logHeaders, (page or "")[:MAX_CONNECTION_CHUNK_SIZE]), start, time.time())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 293: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-19 22:05
Duplicate of #3572 (fixed)

**Closed by stamparm** 2019-05-19 22:05 UTC
