### ISSUE TITLE
Unhandled exception (#0b490e32)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5097] opened 2022-05-11 03:11 UTC
```
Running version: 1.6.5.2#dev
Python version: 3.11.0a7
Operating system: Windows-10-10.0.19042-SP0
Command line: sqlmap.py -u *************************************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "lib/core/datatype.py", line 45, in __getattr__
    return self.__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'lastRequestUID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
    ^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 435, in start
    if not checkConnection(suppressOutput=conf.forms):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/controller/checks.py", line 1504, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 1526, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 941, in getPage
    if kb.resendPostOnRedirect is False:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/datatype.py", line 48, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: unable to access item 'lastRequestUID'
```

**Comment by stamparm** [comment] 2022-05-13 16:00
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5102

**Closed by stamparm** 2022-05-13 16:00 UTC
