### ISSUE TITLE
Unhandled exception (#23b4eb0b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3782] opened 2019-06-27 13:58 UTC
```
Running version: 1.2.11#stable
Python version: 2.7.16
Operating system: Darwin-17.7.0-x86_64-i386-64bit
Command line: /usr/local/bin/sqlmap --identify-waf --tamper=between,randomcase,space2comment -v 3 --risk 2 --thread 1 --random-agent --dbs --form -u ***************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 146, in main
    init()
  File "/Cellar/sqlmap/1.2.11/libexec/lib/core/option.py", line 2507, in init
    _findPageForms()
  File "/Cellar/sqlmap/1.2.11/libexec/lib/core/option.py", line 443, in _findPageForms
    if conf.url and not checkConnection():
  File "/Cellar/sqlmap/1.2.11/libexec/lib/controller/checks.py", line 1529, in checkConnection
    socket.getaddrinfo(conf.hostname, None)
  File "/Cellar/sqlmap/1.2.11/libexec/lib/core/option.py", line 873, in _getaddrinfo
    kb.cache.addrinfo[args] = socket._getaddrinfo(*args, **kwargs)
  File "/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/idna.py", line 73, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
```

**Comment by stamparm** [comment] 2019-06-28 10:46
Duplicate of #3395 (fixed) - different symptoms, same Issue

**Closed by stamparm** 2019-06-28 10:46 UTC
