### ISSUE TITLE
Unhandled exception (#a835bc76)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3838] opened 2019-07-19 03:23 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.16
Operating system: Linux-4.19.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py -u ********************************** --batch --os-shell
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 204, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 84, in osShell
    self.shell()
  File "lib/takeover/abstraction.py", line 161, in shell
    self.runCmd(command)
  File "lib/takeover/abstraction.py", line 100, in runCmd
    conf.dumper.string("command standard output", output)
  File "lib/core/dump.py", line 139, in string
    self._write("%s: %s" % (header, ("'%s'" % _) if isinstance(data, six.string_types) else _))
  File "lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-07-19 09:10
Duplicate of #3700 (fixed)

**Closed by stamparm** 2019-07-19 09:10 UTC
