### ISSUE TITLE
Support for base64 parameters

### ISSUE THREAD

**Issue by tiedot1** [sqlmapproject/sqlmap#1387] opened 2015-09-03 07:44 UTC
I have seen lots of sites use something like this:

http://link.tosite/function.php?aaa=dmFsdWUxPXh4eCZpZD0xMDEwMTAmaT0x

Where aaa is a base64-encoded input of "value1=xxx&phone=101010&i=1".

I need to be able to inject something into value1. Would it be possible to implement this?

Thanks in advance.

**Comment by stamparm** [comment] 2015-09-03 08:36
Duplicate of #25

**Comment by stamparm** [comment] 2015-09-03 08:37
@tiedot1 there are workarounds here, but the automation part is still problematic. Inside the "encoded" value there can be anything. It can be a plain value, it can be a whole new GET request (like in your case), there can be structure data (e.g. JSON), ... Problem is how to automate this :)

**Comment by stamparm** [comment] 2015-09-03 08:40
Also, there is a problem that the parameter/value itself is SQLi injectable, while the decoded value(s) is not (e.g. `par=MTIz' AND 1=1-- -`)

**Comment by tiedot1** [comment] 2015-09-03 13:41
@stamparm I guess I'll just pass it decoded to sqlmap and have a tamper script encode the "aaa" value before sending the request...

**Closed** 2015-09-05 10:28 UTC
Labels: duplicate

**Comment by planitlady** [comment] 2019-04-06 05:22
I'm having the same issue as with this post. Do we already have an updated solution for this using sqlmap please?

**Comment by stamparm** [comment] 2019-04-17 12:25
@planitlady with the latest revision, you can try to use (hidden) parameter `--base64`. Inside of it you should put parameter names containing Base64 encoded values. Support is currently limited to only non-serializable content (e.g. Base64 encoded JSON serialized values are still not supported), but simple values should work without problems.

The following example should work:

`-u "...?id=MQ==" --base64=id`

**Comment by huitc** [comment] 2019-04-17 12:48
Also applies to HTTP header?😅
