### ISSUE TITLE
Unhandled exception (#4efe7a12)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1790] opened 2016-04-01 07:28 UTC
```
sqlmap version: 1.0-dev-nongit-20160226-0b4b
Python version: 2.7.3
Operating system: nt
Command line: sqlmap.py -r 1213.txt --dbs --tamper=between.py,base64encode.py --threads 10
Technique: BOOLEAN
Back-end DBMS: Oracle (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 111, in main
    start()
  File "lib/controller/controller.py", line 626, in start
    action()
  File "lib/controller/action.py", line 106, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "lib/core/dump.py", line 217, in dbs
    self.lister("available databases", dbs, content_type=CONTENT_TYPE.DBS)
  File "lib/core/dump.py", line 147, in lister
    self._write("[*] %s" % element)
  File "lib/core/dump.py", line 70, in _write
    dataToStdout(text)
  File "lib/core/common.py", line 835, in dataToStdout
    sys.stdout.write(setColor(message, bold))
  File "thirdparty/colorama/ansitowin32.py", line 34, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 115, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 142, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 147, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2016-04-01 08:25
Duplicate of #1789

**Closed by stamparm** 2016-04-01 08:25 UTC
