### ISSUE TITLE
Unhandled exception (#7ce847e9)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3073] opened 2018-04-27 12:50 UTC
```
Running version: 1.2.3#pip
Python version: 2.6.6
Operating system: Linux-4.14.0-1.el6.elrepo.i686-i686-with-centos-6.9-Final
Command line: /usr/bin/sqlmap -d ******************************************************* --os-shell
Technique: DIRECT
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 266, in start
    action()
  File "lib/controller/action.py", line 32, in action
    setHandler()
  File "lib/controller/handler.py", line 103, in setHandler
    conf.dbmsConnector.connect()
  File "plugins/dbms/mysql/connector.py", line 39, in connect
    self.connector = pymysql.connect(host=self.hostname, user=self.user, passwd=self.password, db=self.db, port=self.port, connect_timeout=conf.timeout, use_unicode=True)
  File "pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "pymysql/connections.py", line 699, in __init__
    self.connect()
  File "pymysql/connections.py", line 935, in connect
    self._get_server_information()
  File "pymysql/connections.py", line 1249, in _get_server_information
    packet = self._read_packet()
  File "pymysql/connections.py", line 991, in _read_packet
    packet_header = self._read_bytes(4)
  File "pymysql/connections.py", line 1025, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "io.py", line 940, in read
    return self._read_unlocked(n)
  File "io.py", line 974, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "io.py", line 591, in read
    n = self.readinto(b)
  File "pymysql/_socketio.py", line 59, in readinto
    return self._sock.recv_into(b)
TypeError: recv_into() argument 1 must be pinned buffer, not bytearray
```

**Comment by stamparm** [comment] 2018-04-30 08:52
Duplicate of #3041 (patched)

**Closed by stamparm** 2018-04-30 08:52 UTC
