### ISSUE TITLE
Unhandled exception (#c8b1dd79)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3707] opened 2019-05-24 21:08 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.16
Operating system: Linux-4.19.0-kali5-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: /usr/bin/sqlmap -u ******************************** -D *** --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 180, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 673, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "/share/sqlmap/plugins/generic/entries.py", line 453, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "/share/sqlmap/lib/core/dump.py", line 605, in dbTableValues
    self._write("| %s%s" % (value, blank), newline=False, console=console)
  File "/share/sqlmap/lib/core/dump.py", line 79, in _write
    dataToStdout(text)
  File "/share/sqlmap/lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-24 21:21
Duplicate of #3700

**Closed by stamparm** 2019-05-24 21:21 UTC
