### ISSUE TITLE
Unhandled exception (#f763018f)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2494] opened 2017-04-19 21:17 UTC
```
sqlmap version: 1.1.4.39#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ******************************** dbms=mysysql ûdbs --level=5
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 140, in main
    init()
  File "lib/core/option.py", line 2606, in init
    parseTargetUrl()
  File "lib/core/common.py", line 1453, in parseTargetUrl
    conf.httpHeaders = filter(lambda key, value: key != HTTP_HEADER.HOST, conf.httpHeaders)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by stamparm** [comment] 2017-04-19 21:26
Duplicate of #2491 (fixed)

**Closed by stamparm** 2017-04-19 21:26 UTC
