### ISSUE TITLE
Unhandled exception (#bdf02fb2)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4553] opened 2021-01-21 05:49 UTC
```
Running version: 1.4.12.25#dev
Python version: 2.7.17
Operating system: Windows-10-10.0.19041
Command line: sqlmap.py -r ********* --dbs --risk=3 --level=3 --tamper=hibernate
Technique: BOOLEAN
Back-end DBMS: H2 (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 703, in start
    action()
  File "lib/controller/action.py", line 33, in action
    setHandler()
  File "lib/controller/handler.py", line 173, in setHandler
    if conf.forceDbms == dbms or handler.checkDbms():
  File "plugins/dbms/h2/fingerprint.py", line 90, in checkDbms
    result = inject.checkBooleanExpression("ZERO() IS 0")
  File "lib/request/inject.py", line 561, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, charsetType=CHARSET_TYPE.BINARY, suppressOutput=True, expectingNone=expectingNone)
  File "lib/core/decorators.py", line 94, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 395, in getValue
    forgeCaseExpression = agent.forgeCaseStatement(expression)
  File "lib/core/agent.py", line 1177, in forgeCaseStatement
    caseExpression = queries[Backend.getIdentifiedDbms()].case.query % expression
KeyError: 'H2'
```

**Comment by stamparm** [comment] 2021-01-21 09:24
Duplicate of #3914

**Closed by stamparm** 2021-01-21 09:24 UTC
