### ISSUE TITLE
Unhandled exception (#3c34f5dc)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1098] opened 2015-01-07 23:29 UTC
```
sqlmap version: 1.0-dev-4f602da
Python version: 2.6.6
Operating system: posix
Command line: /usr/bin/sqlmap --random-agent --output-dir=/var/www/html/_smap/sam/ --dump-format=HTML -u ********************************************************************** --dbs --no-cast --threads=10 --time-sec=10 --flush-session --tamper=charencode.py,modsecurityversioned.py,randomcase.py,space2morehash.py,varnish.py --level=5 --risk=3 --regexp=*
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 103, in main
    start()
  File "opt/sqlmap/lib/controller/controller.py", line 369, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "opt/sqlmap/lib/controller/checks.py", line 1083, in checkRegexp
    if not re.search(conf.regexp, rawResponse, re.I | re.M):
  File "lib64/python2.6/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "lib64/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
error: nothing to repeat
```

**Comment by stamparm** [comment] 2015-01-08 07:55
Duplicate of #1079 (patched)

**Closed by stamparm** 2015-01-08 07:55 UTC
