### ISSUE TITLE
Unhandled exception (#c1c6e630)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1965] opened 2016-06-17 01:24 UTC
```
sqlmap version: 1.0.5.6#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u ****************************************** --tamper=safedog1.py --delay 3
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 105, in main
    init()
  File "lib/core/option.py", line 2559, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 917, in _setTamperingFunctions
    raise SqlmapSyntaxException("cannot import tamper script '%s' (%s)" % (filename[:-3], msg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 44: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-06-17 13:09
Duplicate of #1960

**Closed by stamparm** 2016-06-17 13:09 UTC
