### ISSUE TITLE
Unhandled exception (#3e073b4e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3727] opened 2019-05-30 12:45 UTC
```
Running version: 1.3.5.135#dev
Python version: 2.7.14
Operating system: Windows-8-6.2.9200-SP0
Command line: sqlmap.py -u *********************************************************** -D *********** -T ***** --dump --level=5 --risk=3 --batch --random-agent --threads 10 --time-sec 10 --current-db
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 673, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 448, in dumpTable
    attackDumpedTable()
  File "lib/utils/hash.py", line 684, in attackDumpedTable
    results = dictionaryAttack(attack_dict)
  File "lib/utils/hash.py", line 984, in dictionaryAttack
    choice = readInput(message, default='1')
  File "lib/core/common.py", line 1087, in readInput
    dataToStdout("%s%s\n" % (message, options), forceOutput=not kb.wizardMode, bold=True)
  File "lib/core/common.py", line 975, in dataToStdout
    sys.stdout.write(stdoutEncode(setColor(data, bold=bold)))
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self._write(text[start:end])
  File "thirdparty/colorama/ansitowin32.py", line 182, in _write
    self.wrapped.write(text)
  File "/Python27/lib/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "/Python27/lib/encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 79: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-30 18:18
Duplicate of #3700

**Closed by stamparm** 2019-05-30 18:18 UTC
