### ISSUE TITLE
Unhandled exception (#846e4ec2)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1445] opened 2015-10-04 06:45 UTC
```
sqlmap version: 1.0-dev-nongit-20151004
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u ********************* --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 100, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "share/sqlmap/lib/controller/checks.py", line 1310, in checkConnection
    page, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "share/sqlmap/lib/request/connect.py", line 1054, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "share/sqlmap/lib/request/connect.py", line 638, in getPage
    processResponse(page, responseHeaders)
  File "share/sqlmap/lib/request/basic.py", line 316, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None)
  File "share/sqlmap/lib/request/basic.py", line 129, in parseResponse
    headersParser(headers)
  File "share/sqlmap/lib/parse/headers.py", line 41, in headersParser
    parseXmlFile(xmlfile, handler)
  File "share/sqlmap/lib/core/common.py", line 1806, in parseXmlFile
    with contextlib.closing(StringIO(readCachedFileContent(xmlFile))) as stream:
  File "share/sqlmap/lib/core/common.py", line 1867, in readCachedFileContent
    kb.cache.content[filename] = f.read()
  File "lib/python2.7/codecs.py", line 668, in read
    return self.reader.read(size)
  File "lib/python2.7/codecs.py", line 468, in read
    newdata = self.stream.read()
IOError: [Errno 5] Input/output error
```

**Comment by stamparm** [comment] 2015-10-05 14:37
Duplicate of #1446

**Closed by stamparm** 2015-10-05 14:37 UTC
