### ISSUE TITLE
Unhandled exception (#1debc830)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2048] opened 2016-07-20 09:53 UTC
```
sqlmap version: 1.0.7.35#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ******************************************* --dump
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 143, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 193, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 215, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 108, in _oneShotUnionUse
    root = xml.etree.ElementTree.fromstring("<root>%s</root>" % output)
  File "lib/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "lib/xml/etree/ElementTree.py", line 1651, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-49: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-20 14:49
Duplicate of #2045

**Closed by stamparm** 2016-07-20 14:49 UTC
