### ISSUE TITLE
Unhandled exception (#510a4eec)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5223] opened 2022-11-03 06:03 UTC
```
Running version: 1.6.10.4#dev
Python version: 3.10.8
Operating system: Windows-10-10.0.22000-SP0
Command line: sqlmap.py -r .\request.txt tfUPass --random-agent --tamper=space2comment --batch --force-ssl --level 5 --risk 3 --threads 10 --batch --banner --os-shell --sql-shell
Technique: BOOLEAN
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 701, in start
    action()
  File "lib/controller/action.py", line 192, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 117, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 62, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 402, in getValue
    query = expandAsteriskForColumns(query)
  File "lib/core/common.py", line 1841, in expandAsteriskForColumns
    conf.tbl = safeSQLIdentificatorNaming(conf.tbl, True)
  File "lib/core/common.py", line 4272, in safeSQLIdentificatorNaming
    if conf.db.lower() != "information_schema":     # NOTE: https://github.com/sqlmapproject/sqlmap/issues/5192
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stamparm** [comment] 2022-11-03 22:33
Duplicate of https://github.com/sqlmapproject/sqlmap/issues/5202 (fixed)

**Closed by stamparm** 2022-11-03 22:33 UTC
