### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by maximusfox** [sqlmapproject/sqlmap#3923] opened 2019-09-13 05:24 UTC
```
[08:19:25] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.3.9.11#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.3.9.11#dev
Python version: 3.7.0
Operating system: Windows-8.1-6.3.9600-SP0
Command line: sqlmap.py -m input.txt --crawl=2 --random-agent --threads 10 --forms --level=5 --risk=3 --smart --answers=follow=Y,recursion=N,check for the existence=Y --batch --save=config.ini
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 897, in recursiveChildGenerator
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\lib\core\threads.py", line 149, in runThreads
    threadFunction()
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\lib\utils\crawler.py", line 92, in crawlThread
    soup = BeautifulSoup(content)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 1539, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 1164, in __init__
    self._feed(isHTML=isHTML)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 1183, in _feed
    if not hasattr(self, 'originalEncoding'):
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 1221, in __getattr__
    return Tag.__getattr__(self, methodName)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 682, in __getattr__
    return self.find(tag)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 846, in find
    l = self.findAll(name, attrs, recursive, text, 1, **kwargs)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 866, in findAll
    return self._findAll(name, attrs, text, limit, generator, **kwargs)
  File "C:\Users\User\Desktop\sqlmapproject-sqlmap-af8a2af\thirdparty\beautifulsoup\beautifulsoup.py", line 392, in _findAll
    i = next(g)
RuntimeError: generator raised StopIteration
```

**Comment by stamparm** [comment] 2019-09-13 09:40
Duplicate of #3924 (patched)

**Closed by stamparm** 2019-09-13 09:40 UTC
