### ISSUE TITLE
Unhandled exception (#7c2e0139)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2145] opened 2016-09-02 06:53 UTC
```
sqlmap version: 1.0-dev-nongit-201609010a89
Python version: 2.7.11
Operating system: posix
Command line: /usr/bin/sqlmap -u ******************************************* --data=*************************************** -p usuario --dbms=Sybase -D ***** -T alumnos -C ***************** --dump
Technique: ERROR
Back-end DBMS: Sybase (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 110, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 626, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 127, in action
    conf.dbmsHandler.dumpTable()
  File "share/sqlmap/plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
TypeError: getColumns() got an unexpected keyword argument 'dumpMode'
```

**Comment by stamparm** [comment] 2016-09-02 08:21
Duplicate of #1628 (fixed long ago)

**Closed by stamparm** 2016-09-02 08:21 UTC
Labels: duplicate
