### ISSUE TITLE
Unhandled exception (#f51d4983)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3266] opened 2018-10-02 06:49 UTC
```
sqlmap version: 1.1.12#stable
Python version: 2.7.15
Operating system: nt
Command line: sqlmap.py -r 2.txt --random-agent --no-cast -D ******* -T asksearch_data_tbl --threads=5 -C ****** --dump
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 187, in dumpTable
    value = inject.getValue(query, blind=False, time=False, dump=True) or ""
  File "lib/request/inject.py", line 389, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 331, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 223, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 84, in _oneShotUnionUse
    page, headers, _ = Request.queryPage(payload, content=True, raise404=False)
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "lib/urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "lib/urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by stamparm** [comment] 2018-10-02 07:44
Duplicate of #2886 (fixed)

**Closed by stamparm** 2018-10-02 07:44 UTC
