### ISSUE TITLE
Unhandled exception (#96730f91)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3920] opened 2019-09-12 20:18 UTC
```
Running version: 1.3.8#stable
Python version: 2.7.16
Operating system: Linux-5.2.14-arch1-1-ARCH-x86_64-with-glibc2.2.5
Command line: sqlmap.py --url=******************************************* --user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; ******************************** --data=******************************************************************************************** --threads=10 --risk=3 --level=5 --eta --dbms=MySQL --os=Linux --banner --is-dba --users --passwords --current-user --dbs -p cid --tamper=sp_password,modsecurityversioned --udf-inject --prefix=?id=1%09and%091=1%09-- --sql-query=SUBSTR('SQL',1,1) --suffix=or 2 like 2 --os-shell --regex=[A-Z] --eta
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 75, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 571, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 402, in checkSqlInjection
    ptype = boundary.ptype
  File "lib/core/datatype.py", line 46, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'ptype'
```

**Comment by stamparm** [comment] 2019-09-13 09:44
Duplicate of #3921

**Closed by stamparm** 2019-09-13 09:44 UTC
