### ISSUE TITLE
Unhandled exception (#a7e8cc2e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1123] opened 2015-01-18 21:44 UTC
```
sqlmap version: 1.0-dev-nongit-20150112
Python version: 2.7.2
Operating system: posix
Command line: sdl --disable-col -m /init.mmi.boot.sh -v 1 --timeout=30 --retries=3 --threads=1 --risk=1 --level=1 --technique=BEUSTQ
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/sqlmap.py", line 91, in main
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 2338, in init
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/option.py", line 626, in _setBulkMultipleTargets
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/app/sqlmap/lib/core/common.py", line 1892, in getFileItems
  File "Volumes/BADA/repos/my/sqlmapchik/.buildozer/android/platform/python-for-android/dist/sqlmapchik/private/lib/python2.7/codecs.py", line 881, in open
IOError: [Errno 13] Permission denied: u'/init.mmi.boot.sh'
```

**Comment by stamparm** [comment] 2015-01-18 21:59
Duplicate of #1075

**Closed by stamparm** 2015-01-18 21:59 UTC
