### ISSUE TITLE
Unhandled exception (#8c72e713)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5778] opened 2024-09-12 23:45 UTC
```
Running version: 1.8.6.9#dev
Python version: 3.12.6
Operating system: Windows-2019Server-10.0.17763-SP0
Command line: sqlmap.py -u **************************************************** --data=******************************************************************************* -p id --batch --random-agent --risk=3 --level=5 --threads=10 --tables
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 115, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/generic/databases.py", line 324, in getTables
    table = unArrayizeValue(table).strip()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by stamparm** [comment] 2024-09-13 16:17
Duplicate of #5735 (fixed long ago)

**Closed by stamparm** 2024-09-13 16:17 UTC
