### ISSUE TITLE
Unhandled exception (#ce30de86)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3328] opened 2018-10-29 07:49 UTC
```
Running version: 1.2.10.12#dev
Python version: 2.7.15
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --url=**************** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=MYSQL --random-agent --is-dba --exclude-sysdbs --current-db --answers=**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 33, in <module>
    from plugins.dbms.postgresql import PostgreSQLMap
ImportError: No module named postgresql
```

**Comment by stamparm** [comment] 2018-10-29 08:38
Duplicate of #3308

**Closed by stamparm** 2018-10-29 08:38 UTC
