### ISSUE TITLE
Unhandled exception (#2cd06a79)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2794] opened 2017-11-22 01:07 UTC
```
sqlmap version: 1.0.11.16#dev
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -u *************************************** --flush-session --level 3 -v 3 --risk 3 --tamper=space2comment,randomcase，equaltolike /**/
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2653, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 905, in _setTamperingFunctions
    elif os.path.exists(os.path.join(paths.SQLMAP_TAMPER_PATH, script if script.endswith(".py") else "%s.py" % script)):
  File "lib/ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 10: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-11-22 12:02
Duplicate of #2348 (fixed LONG ago). Please update

**Closed by stamparm** 2017-11-22 12:02 UTC
