### ISSUE TITLE
Unhandled exception (#294169bb)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4454] opened 2020-12-02 17:14 UTC
```
Running version: 1.4.12.5#dev
Python version: 2.7.18
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=******************************************************************************** --crawl=1 --threads=10 --retries=0 --timeout=5 --dbms=mysql,mssql --technique=EU --random-agent --is-dba --exclude-sysdbs --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: UNION
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 449, in start
    checkWaf()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/checks.py", line 1426, in checkWaf
    retVal = (Request.queryPage(place=place, value=value, getRatioValue=True, noteResponseTime=False, silent=True, raise404=False, disableTampering=True)[1] or 0) < IPS_WAF_CHECK_RATIO
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1413, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 872, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 398, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", getUnicode("".join(responseHeaders.headers if responseHeaders else [])), page)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 38: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2020-12-02 20:28
Duplicate of #4453

**Closed by stamparm** 2020-12-02 20:28 UTC
