### ISSUE TITLE
Unhandled exception (#fa05dee4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2184] opened 2016-09-25 03:29 UTC
```
sqlmap version: 1.0.9.21#dev
Python version: 2.7.7
Operating system: nt
Command line: sqlmap.py -r 1.txt -p tbusername -D ****** -T ********** --columns --delay 3
Technique: STACKED
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 112, in action
    conf.dumper.dbTableColumns(conf.dbmsHandler.getColumns(), CONTENT_TYPE.COLUMNS)
  File "plugins/generic/databases.py", line 717, in getColumns
    column = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 579, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 272, in getChar
    position = charTbl.index(ord('a') - 1)  # 96
AttributeError: 'xrange' object has no attribute 'index'
```

**Comment by stamparm** [comment] 2016-09-26 09:03
Duplicate of #2175 (fixed). Please update

**Closed by stamparm** 2016-09-26 09:04 UTC
