### ISSUE TITLE
Unhandled exception (#03776d5a)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4721] opened 2021-06-24 21:30 UTC
```
Running version: 1.4.12.5#dev
Python version: 2.7.18
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=********************************************************************************************************************************************************************************************************************************************************************************************************* --crawl=1 --threads=10 --retries=0 --timeout=5 --dbms=mysql,mssql,sqlite --technique=EUBSTQ --random-agent --is-dba --exclude-sysdbs --current-db --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: UNION
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 215, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 592, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 506, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1413, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 872, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 398, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", getUnicode("".join(responseHeaders.headers if responseHeaders else [])), page)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 124: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2021-06-25 08:33
Duplicate of #4465 (fixed)

**Closed by stamparm** 2021-06-25 08:33 UTC
