### ISSUE TITLE
Unhandled exception (#779a01b3)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2998] opened 2018-03-20 03:09 UTC
```
sqlmap version: 1.1.5.10#dev
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ************************************************ --sql-shell
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 150, in main
    start()
  File "lib/controller/controller.py", line 652, in start
    action()
  File "lib/controller/action.py", line 133, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 107, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 50, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 389, in unionUse
    runThreads(numThreads, unionThread)
  File "lib/core/threads.py", line 170, in runThreads
    print
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2018-03-20 09:18
Duplicate of #2790 (fixed)

**Closed by stamparm** 2018-03-20 09:18 UTC
