### ISSUE TITLE
Unhandled exception (#841ca55e)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3309] opened 2018-10-21 16:24 UTC
```
Running version: 1.2.9.38#dev
Python version: 2.7.15
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --url=************************************************************************** --threads=10 --tamper=space2comment.py --retries=0 --timeout=10 --dbms=MYSQL --technique=EUS --random-agent --is-dba --exclude-sysdbs --current-db --answers=**************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 153, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 70, in <module>
    from lib.core.target import initTargetEnv
  File "lib/core/target.py", line 37, in <module>
    from lib.core.dump import dumper
ImportError: No module named dump
```

**Comment by stamparm** [comment] 2018-10-22 09:02
Duplicate of #3308

**Comment by stamparm** [comment] 2018-10-22 09:02
Duplicate of #3308

**Closed by stamparm** 2018-10-22 09:02 UTC
Labels: duplicate
