### ISSUE TITLE
Unhandled exception (#dbc8b025)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3320] opened 2018-10-27 03:44 UTC
```
Running version: 1.2.10.36#dev
Python version: 2.7.15rc1
Operating system: Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
Command line: sqlmap.py --forms -u ************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 146, in main
    init()
  File "lib/core/option.py", line 2498, in init
    _findPageForms()
  File "lib/core/option.py", line 443, in _findPageForms
    if conf.url and not checkConnection():
  File "lib/controller/checks.py", line 1523, in checkConnection
    if not re.search(r"\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\Z", conf.hostname):
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by stamparm** [comment] 2018-10-27 12:30
Duplicate of #3319

**Closed by stamparm** 2018-10-27 12:30 UTC
Labels: duplicate
