### ISSUE TITLE
Unhandled exception (#336f417b)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2043] opened 2016-07-19 14:43 UTC
```
sqlmap version: 1.0.7.22#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py --url=****************************************** -p id --dump -T TaiKhoan
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 193, in dumpTable
    entries = inject.getValue(query, blind=False, time=False, dump=True)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 211, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 108, in _oneShotUnionUse
    root = xml.etree.ElementTree.fromstring("<root>%s</root>" % output)
  File "Python27/lib/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "Python27/lib/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1ef3' in position 346: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2016-07-19 14:44
Duplicate of #2042

**Closed by stamparm** 2016-07-19 14:44 UTC
