### ISSUE TITLE
lib error

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3019] opened 2018-03-31 16:54 UTC
Version of use 1.2.3.51 revision 8a90512
On Linux System

The issue is when I start sqlmap with  
`--url="*********************" --tamper=******** --random-agent --ignore-redirects --level=5 --risk=3 --text-only --threads=4 --is-dba -v 2 -f --banner --parse-errors --skip-waf`

it gives me 
```
> /root/sqlmap-dev/lib/controller/checks.py(1058)heuristicCheckSqlInjection()
-> infoMsg += "be injectable"
(Pdb) 
```

Could you solved it, please

**Comment by alienus** [comment] 2018-04-01 05:02
Same
Darwin t******-Mac-mini.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by stamparm** [comment] 2018-04-01 09:31
My fault. Duplicate of #3020 (fixed)

**Closed by stamparm** 2018-04-01 09:31 UTC
