### ISSUE TITLE
Proxy response error

### ISSUE THREAD

**Issue by kilikintien** [sqlmapproject/sqlmap#2569] opened 2017-06-07 21:59 UTC
Hi, here again
Am getting database name, tables and columns but I don't have output data entries when am trying to dump. Could someone help me? you can find below the error message from proxy

HTTP/1.1 500 Internal Server Error
Date: Wed, 07 Jun 2017 21:53:14 GMT
Server: Apache
Cache-Control: no-cache
Pragma: no-cache
Connection: close
Content-Type: text/html; charset=UTF-8
Content-Length: 178

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY #__content.created DESC' at line 1

**Comment by stamparm** [comment] 2017-06-07 22:05
Duplicate of #2567. I've told you what to do there and you are still not trying to find out what is happening. For example, this message with `#__content.created` is interesting but there is absolutely no context whatsoever. Like, "DBMS is this, SQLi technique is that, table name is ..., column name(s) are that...".

Please don't open this kind of issues. You are presented with a nice template at each new Issue request and you are not filling anything. Hence, closing this down as invalid

**Closed by stamparm** 2017-06-07 22:05 UTC
