### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Kalimon12** [sqlmapproject/sqlmap#3910] opened 2019-09-04 18:12 UTC
how fix this

#!/usr/bin/env python

from lib.core.enums import PRIORITY
from lib.core.settings import UNICODE_ENCODING
priority = PRIORITY.LOW
def dependencies():
pass
def tamper(payload, **kwargs):

if payload:
payload=payload.replace(" ","/!/")
payload=payload.replace("=","/!/=/!/")
payload=payload.replace("AND","/!/AND/!/")
payload=payload.replace("UNION","union/!88888cas/")
payload=payload.replace("#","/!/#")
payload=payload.replace("USER()","USER/!()/")
payload=payload.replace("DATABASE()","DATABASE/!()/")
payload=payload.replace("--","/!/--")
payload=payload.replace("SELECT","/!88888cas/select")
payload=payload.replace("FROM","/!99999c//!99999c/from")
print payload

return payload

[13:56:13] [CRITICAL] cannot import tamper module 'bypass' (IndentationError: expected an indented block)

**Comment by stamparm** [comment] 2019-09-05 09:16
Duplicate of #3909

**Closed** 2019-09-05 09:16 UTC
Labels: duplicate
