### ISSUE TITLE
Unhandled exception (#9f9d8de4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2813] opened 2017-12-04 15:41 UTC
```
sqlmap version: 1.1.11.39#dev
Python version: 2.7.14
Operating system: posix
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 154, in main
    else:
  File "lib/controller/controller.py", line 69, in <module>
    from lib.core.target import initTargetEnv
  File "lib/core/target.py", line 65, in <module>
    from lib.core.settings import SESSION_SQLITE_FILE
ImportError: cannot import name SESSION_SQLITE_FILE
```

**Comment by stamparm** [comment] 2017-12-04 15:42
Duplicate of #2812 (fixed)

**Closed by stamparm** 2017-12-04 15:42 UTC
