### ISSUE TITLE
Unhandled exception (#d4279d14)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2216] opened 2016-10-07 03:49 UTC
```
sqlmap version: 1.0.10.2#dev
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u ********************************************** --dbs
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2617, in init
    _createTemporaryDirectory()
  File "lib/core/option.py", line 1574, in _createTemporaryDirectory
    except (OSError, IOError, WindowsError), ex:
NameError: global name 'WindowsError' is not defined
```

**Comment by stamparm** [comment] 2016-10-07 07:58
Duplicate of #2208 (fixed)

**Closed by stamparm** 2016-10-07 07:58 UTC
