### ISSUE TITLE
Unhandled exception (#ee5b61b4)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2790] opened 2017-11-20 05:35 UTC
```
sqlmap version: 1.1.11.13#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py --random-agent -u ***************************************************** --forms --sql-shell
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 155, in main
    start()
  File "lib/controller/controller.py", line 653, in start
    action()
  File "lib/controller/action.py", line 133, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 89, in sqlShell
    query = raw_input("sql-shell> ")
  File "thirdparty/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "thirdparty/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "thirdparty/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "thirdparty/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by stamparm** [comment] 2017-11-20 08:52
Reference: https://github.com/tartley/colorama/issues/101

**Comment by stamparm** [comment] 2018-01-06 01:23
Duplicate of #2790

**Comment by stamparm** [comment] 2018-01-12 15:16
Applying patch from https://github.com/robotframework/robotframework/commit/828c67695d85519e4435c556c43ed1b00985df05

**Closed** 2018-01-12 15:18 UTC
Labels: bug, miscellaneous, normal
