### ISSUE TITLE
http Get request with encoding data (Reverse + base64)

### ISSUE THREAD

**Issue by infinity1234** [sqlmapproject/sqlmap#2346] opened 2017-01-14 15:21 UTC
I have a target that http get request from that encoded As follows:

data request post first url Reversed and then base64 encoded.
example request post from mentioned target As follows:

```
GET /test/test-page.html?multipage=NT1lZ2FwJjI5OD10bHVzZXJibl9lZ2FwaXRsdW0mMjA3MT15dGl2aXRjYV9kaSY9ZW1hbiZzaXJhcD1lZG9jcGl6X3l0aWM= HTTP/1.1
Host: target.com
```

for decoding data request post first must base64 decode and then Reverse string. actualy after decoding Something like the following:

```
GET /test/test-page.html?multipage=city_zipcode=paris&name=&id_activity=1702&multipage_nbresult=892&page=5 HTTP/1.1
Host: target.com
```

Now my question is: how to run sqlmap on this target while injected queries in parameter values from data request post and then encode Similar as mentioned and then send to server target?

i think it's possible by use a tamper script like this ? :

``` 
python sqlmap.py -r you/request/file/path --dbs --tamper=base64encode 
```

but i don't have knowledge of python so my question is how to mod the base64encode.py tamper script with " [::-1] " for reverse the string before base64 encode

**Comment by stamparm** [comment] 2017-01-14 23:19
Duplicate of #2335. Take a look at https://github.com/sqlmapproject/sqlmap/issues/2335#issuecomment-271121099

**Closed by stamparm** 2017-01-14 23:19 UTC

**Comment by infinity1234** [comment] 2017-01-15 18:41
Thank's for the reply but it's not the same situation ; 
i need to reverse the string before base 64 encode :

step 1
```
name1=value1&name2=value2
```

step 2
```
2eulav=2eman&1eulav=1eman
```

step 3
```
MmV1bGF2PTJlbWFuJjFldWxhdj0xZW1hbg==
```

maybe i can do this job by modding the tamper script base64encode.py with this " [::-1] " for reverse the sting before encode ?

**Comment by stamparm** [comment] 2017-01-15 19:49
As said, you'll need to modify the code
