### ISSUE TITLE
Unhandled exception (#ee19ffd5)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2833] opened 2017-12-17 19:14 UTC
```
sqlmap version: 1.1.12#pip
Python version: 2.7.12
Operating system: posix
Command line: /data/user/0/org.qpython.qpy/files/bin/sqlmap -u ************************************** --exclude-sysdbs --eta --tables --columns --output-dir=/sdcard/qpython/cache
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 649, in start
    action()
  File "lib/controller/action.py", line 103, in action
    conf.dumper.dbTables(conf.dbmsHandler.getTables())
  File "plugins/generic/databases.py", line 220, in getTables
    dbs = self.getDbs()
  File "plugins/generic/databases.py", line 141, in getDbs
    db = unArrayizeValue(inject.getValue(query, union=False, error=False))
  File "lib/request/inject.py", line 434, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 287, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 130, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 102, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 628, in bisection
    progress.progress(time.time() - charStart, index)
NameError: global name 'charStart' is not defined
```

**Comment by stamparm** [comment] 2017-12-18 22:44
Duplicate of #2824 (fixed)

**Closed by stamparm** 2017-12-18 22:44 UTC
