### ISSUE TITLE
Unhandled exception (#e9563070)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1483] opened 2015-10-23 14:12 UTC
```
sqlmap version: 1.0-dev-nongit-20151005
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u ************************************************* --data=************************** --random-agent --level 3 -p razeni --tamper=between --threads=4 -D ************ --sql-shell --fresh-queries --hex
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 625, in start
    action()
  File "lib/controller/action.py", line 139, in action
    conf.dbmsHandler.sqlShell()
  File "plugins/generic/custom.py", line 102, in sqlShell
    output = self.sqlQuery(query)
  File "plugins/generic/custom.py", line 48, in sqlQuery
    output = inject.getValue(query, fromUser=True)
  File "lib/request/inject.py", line 423, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 193, in _goInferenceProxy
    _ = countedExpression.upper().rindex(" ORDER BY ")
ValueError: substring not found
```

**Comment by stamparm** [comment] 2015-10-23 14:19
Duplicate of #1474 (fixed)

**Closed by stamparm** 2015-10-23 14:19 UTC
