### ISSUE TITLE
Unhandled exception (#3166d624)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2788] opened 2017-11-18 06:17 UTC
```
sqlmap version: 1.1.11.21#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u ************************************************************************** --level=5 -v 3 -D libreria_bookscenter -T glmcpedcli -C ************** --technique=BEUST --dump
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 156, in main
    start()
  File "lib/controller/controller.py", line 655, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 429, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 410, in dbTableValues
    dumpDbPath = os.path.join(conf.dumpPath, unsafeSQLIdentificatorNaming(db))
  File "Python27/lib/ntpath.py", line 67, in join
    p_drive, p_path = splitdrive(p)
  File "Python27/lib/ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'bool' has no len()
```

**Comment by stamparm** [comment] 2017-11-19 01:52
Duplicate of #2786

**Closed by stamparm** 2017-11-19 01:52 UTC
