### ISSUE TITLE
Unhandled exception (#5f79ddfb)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1966] opened 2016-06-17 14:12 UTC
```
sqlmap version: 1.0.6.27#dev
Python version: 2.7.6
Operating system: posix
Command line: /usr/bin/sqlmap -u *************************** --technique=BEUSTQ --tamper=between --random-agent
Technique: UNION
Back-end DBMS: Firebird (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 140, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 633, in start
    action()
  File "share/sqlmap/lib/controller/action.py", line 32, in action
    setHandler()
  File "share/sqlmap/lib/controller/handler.py", line 104, in setHandler
    if handler.checkDbms():
  File "share/sqlmap/plugins/dbms/firebird/fingerprint.py", line 109, in checkDbms
    Backend.setVersion(v)
NameError: global name 'v' is not defined
```

**Comment by stamparm** [comment] 2016-06-17 14:15
Duplicate of #1932 (fixed)

**Closed by stamparm** 2016-06-17 14:15 UTC
