### ISSUE TITLE
Unhandled exception (#c8492365)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2701] opened 2017-09-16 17:07 UTC
```
sqlmap version: 1.1.9.7#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ************************************ --dump -D ********** -T **** --start 500 --stop 1000 --output-dir=check
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 155, in main
    start()
  File "lib/controller/controller.py", line 653, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 429, in dumpTable
    conf.dumper.dbTableValues(kb.data.dumpedTable)
  File "lib/core/dump.py", line 600, in dbTableValues
    dataToDumpFile(dumpFP, "%s%s" % (safeCSValue(value), conf.csvDel))
  File "lib/core/common.py", line 929, in dataToDumpFile
    if (dumpFile=="pipe"):
  File "Python27/lib/encodings/base64_codec.py", line 24, in base64_encode
    output = base64.encodestring(input)
  File "Python27/lib/base64.py", line 322, in encodestring
    pieces.append(binascii.b2a_base64(chunk))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 16: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2017-09-17 21:08
Duplicate of #2699

**Closed by stamparm** 2017-09-17 21:08 UTC
