### ISSUE TITLE
Unhandled exception (#8fbc60a3)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4597] opened 2021-03-06 12:54 UTC
```
Running version: 1.5.3.1#dev
Python version: 2.7.18
Operating system: Linux-4.19.95-perf+-aarch64-with-debian-****-rolling
Command line: /usr/bin/sqlmap ****************************************** --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap", line 217, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 458, in start
    checkStability()
  File "/share/sqlmap/lib/controller/checks.py", line 1339, in checkStability
    checkDynamicContent(firstPage, secondPage)
  File "/share/sqlmap/lib/controller/checks.py", line 1230, in checkDynamicContent
    while not Request.queryPage():
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/connect.py", line 1501, in queryPage
    return comparison(page, headers, code, getRatioValue, pageLength)
  File "/share/sqlmap/lib/request/comparison.py", line 37, in comparison
    _ = _adjust(_comparison(page, headers, code, getRatioValue, pageLength), getRatioValue)
  File "/share/sqlmap/lib/request/comparison.py", line 157, in _comparison
    key = (hash(seq1), hash(seq2))
TypeError: unhashable type: 'list'
```

**Comment by stamparm** [comment] 2021-03-07 19:32
Duplicate of #4591 (fixed)

**Closed by stamparm** 2021-03-07 19:32 UTC
