### ISSUE TITLE
Unhandled exception (#74083765)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1094] opened 2015-01-06 08:22 UTC
```
sqlmap version: 1.0-dev
Python version: 2.7.3
Operating system: nt
Command line: D:\Python\App\sql\sqlmap.py -r D:\Python\App\request5.txt --level=5 --eta -o --threads=10 -D ******** --tables
Technique: None
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 98, in main
    start()
  File "y", line 581, in start
    _showInjections()
  File "y", line 162, in _showInjections
    conf.dumper.string(header, data)
  File "y", line 113, in string
    self._write("%s:\n---\n%s\n---" % (header, _))
  File "y", line 69, in _write
    self._outputFP.write(text)
  File "y", line 691, in write
    return self.writer.write(data)
  File "y", line 352, in write
    self.stream.write(data)
IOError: [Errno 28] No space left on device
```

**Comment by stamparm** [comment] 2015-01-06 14:21
Duplicate of #904 (patched)

**Closed by stamparm** 2015-01-06 14:21 UTC
Labels: duplicate
