### ISSUE TITLE
Unhandled exception (#15d7db71)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2294] opened 2016-12-01 16:33 UTC
```
sqlmap version: 1.0.9.21#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u **************************** --os-cmd -v 1
Technique: STACKED
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 151, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 60, in osCmd
    self.runCmd(conf.osCmd)
  File "lib/takeover/abstraction.py", line 89, in runCmd
    output = self.evalCmd(cmd)
  File "lib/takeover/abstraction.py", line 69, in evalCmd
    retVal = self.xpCmdshellEvalCmd(cmd, first, last)
  File "lib/takeover/xp_cmdshell.py", line 224, in xpCmdshellEvalCmd
    output.append(inject.getValue(query, union=False, error=False, resumeValue=False))
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 579, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 272, in getChar
    position = charTbl.index(ord('a') - 1)  # 96
AttributeError: 'xrange' object has no attribute 'index'
```

**Comment by Ekultek** [comment] 2016-12-01 19:36
Is this literally just a bot that finds errors in the program?

**Comment by stormwin** [comment] 2016-12-01 20:22
@Ekultek, sqlmap uses this github account (created specially for sqlmap from maintainers) for reporting crash when occurred.
When crash occurred in sqlmap, a message shows up asking user whether you want to report this crash to developers. If you confirm, new github issue will be created.
With this technique, crash reporting is some kind of "automated", giving useful information to developers to reproduce it and fix it

**Comment by stamparm** [comment] 2016-12-01 20:29
Duplicate of #2203 (fixed two months ago)

**Closed by stamparm** 2016-12-01 20:29 UTC

**Comment by Ekultek** [comment] 2016-12-02 00:25
@stormwin that's pretty smart, I was like they literally made a bot to run the script over and over again to find errors, that would be ingenious
