### ISSUE TITLE
Unhandled exception (#70d42db0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1585] opened 2015-12-07 15:34 UTC
```
sqlmap version: 1.0-dev-nongit-20151201
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u ********************** --forms --random-agent -v 2 --level=5 --risk=3 --parse-errors --profile
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 94, in main
    profile()
  File "share/sqlmap/lib/core/profiling.py", line 89, in profile
    win.open_file(dotOutputFile)
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1786, in open_file
    self.set_dotcode(fp.read(), filename)
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1774, in set_dotcode
    if self.widget.set_dotcode(dotcode, filename):
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1435, in set_dotcode
    self.set_xdotcode(xdotcode)
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1451, in set_xdotcode
    self.graph = parser.parse()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1138, in parse
    DotParser.parse(self)
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 948, in parse
    self.parse_graph()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 957, in parse_graph
    self.parse_stmt()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 979, in parse_stmt
    self.handle_graph(attrs)
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 1098, in handle_graph
    self.shapes.extend(parser.parse())
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 608, in parse
    points = self.read_polygon()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 500, in read_polygon
    x, y = self.read_point()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 483, in read_point
    x = self.read_number()
  File "share/sqlmap/thirdparty/xdot/xdot.py", line 477, in read_number
    return int(self.read_code())
ValueError: invalid literal for int() with base 10: '595.5'
```

**Comment by bb1ox1bb** [comment] 2015-12-07 15:36
testing command dont take an atention on that  :) --profile

**Comment by stamparm** [comment] 2015-12-07 15:37
@bb1ox1bb Duplicate of #1584 (fixed ;)

**Closed by stamparm** 2015-12-07 15:37 UTC
