### ISSUE TITLE
Unhandled exception (#e21134df)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1569] opened 2015-11-27 05:39 UTC
```
sqlmap version: 1.0-dev-nongit-20150823
Python version: 2.7
Operating system: nt
Command line: sqlmap.py -u *********************************************** --os-cmd=ipconfig
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 109, in main
    start()
  File "lib/controller/controller.py", line 625, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 57, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 204, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 184, in udfInjectSys
    self.udfSetLocalPaths()
  File "plugins/dbms/mysql/takeover.py", line 90, in udfSetLocalPaths
    self.udfLocalFile = decloakToTemp(_)
  File "lib/core/common.py", line 3868, in decloakToTemp
    handle, filename = tempfile.mkstemp(prefix=prefix, suffix=suffix)
  File "lib/tempfile.py", line 293, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "lib/tempfile.py", line 226, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "lib/ntpath.py", line 108, in join
    path += "\\" + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 9: ordinal not in range(128)
```

**Comment by atsuyim** [comment] 2015-11-27 14:50
lol never have i saw that :(

**Comment by stamparm** [comment] 2015-11-27 17:38
Duplicate of #1415 (fixed)

**Closed by stamparm** 2015-11-27 17:38 UTC
