### ISSUE TITLE
Unhandled exception (#a7e16501)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4594] opened 2021-03-04 14:49 UTC
```
Running version: 1.5.3.1#dev
Python version: 3.8.5
Operating system: Linux-5.8.0-44-generic-x86_64-with-glibc2.29
Command line: sqlmap.py --tor --tor-type=socks5 --check-tor -m /home/******/scanner-master/output/savedork.txt --random-agent --flush-session -technique=BEUSTQ --tamper=space2comment,between,charencode --level=5 --risk=3 --dbs --ignore-code=404 --time-sec=2 --cookie=**************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 217, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 591, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 507, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1501, in queryPage
    return comparison(page, headers, code, getRatioValue, pageLength)
  File "lib/request/comparison.py", line 37, in comparison
    _ = _adjust(_comparison(page, headers, code, getRatioValue, pageLength), getRatioValue)
  File "lib/request/comparison.py", line 157, in _comparison
    key = (hash(seq1), hash(seq2))
TypeError: unhashable type: 'list'
```

**Comment by stamparm** [comment] 2021-03-04 15:04
Duplicate of #4591 (fixed)

**Closed by stamparm** 2021-03-04 15:04 UTC
