### ISSUE TITLE
Unhandled exception (#5dacb952)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3657] opened 2019-05-14 06:00 UTC
```
Running version: 1.3.5.28#dev
Python version: 2.7.14
Operating system: Windows-10-10.0.17134
Command line: sqlmap.py -u ******************************************************** -D ************ -T ***************** --dump
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 179, in main
    start()
  File "lib/core/decorators.py", line 54, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 675, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 448, in dumpTable
    attackDumpedTable()
  File "lib/utils/hash.py", line 682, in attackDumpedTable
    results = dictionaryAttack(attack_dict)
  File "lib/utils/hash.py", line 920, in dictionaryAttack
    item = [(****, decodeBase64(hash_, binary=False).encode("hex")), {}]
  File "/Python27/lib/encodings/hex_codec.py", line 24, in hex_encode
    output = binascii.b2a_hex(input)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-14 10:11
Duplicate of #3633 (fixed)

**Closed by stamparm** 2019-05-14 10:11 UTC
