### ISSUE TITLE
Unhandled exception (#de960610)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4370] opened 2020-10-08 19:31 UTC
```
Running version: 1.3.10.13#dev
Python version: 3.9.0
Operating system: Windows-10-10.0.18362-SP0
Command line: sqlmap.py -u ******************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2676, in init
    loadBoundaries()
  File "lib/parse/payloads.py", line 89, in loadBoundaries
    parseXmlNode(root)
  File "lib/parse/payloads.py", line 44, in parseXmlNode
    for element in node.getiterator("boundary"):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

**Comment by stamparm** [comment] 2020-10-08 19:52
Duplicate of #4126 (fixed long ago)

**Closed by stamparm** 2020-10-08 19:52 UTC
