### ISSUE TITLE
Unhandled exception (#339382ab)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2542] opened 2017-05-21 09:25 UTC
```
sqlmap version: 1.1.5.9#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py -u ********************************************* --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 150, in main
    start()
  File "lib/controller/controller.py", line 393, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1458, in checkConnection
    page, headers = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1188, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 495, in getPage
    page = decodePage(page, responseHeaders.get(HTTP_HEADER.CONTENT_ENCODING), responseHeaders.get(HTTP_HEADER.CONTENT_TYPE))
  File "lib/request/basic.py", line 313, in decodePage
    page = re.sub(r"%([0-9a-fA-F]{2})", lambda _: _.group(1).decode("hex"), page)
  File "Python27/lib/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "lib/request/basic.py", line 313, in <lambda>
    page = re.sub(r"%([0-9a-fA-F]{2})", lambda _: _.group(1).decode("hex"), page)
  File "Python27/lib/encodings/__init__.py", line 100, in search_function
    level=0)
  File "Python27/lib/encodings/hex_codec.py", line 1
SyntaxError: Non-ASCII character '\x8d' in file Python27/lib/encodings/hex_codec.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by stamparm** [comment] 2017-05-21 20:44
Duplicate of #2541 (invalid one)

**Closed by stamparm** 2017-05-21 20:44 UTC
