### ISSUE TITLE
Unhandled exception (#d665d775)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4521] opened 2021-01-05 12:54 UTC
```
Running version: 1.5.1.7#dev
Python version: 2.7.18
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=********************************************************* --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql --technique=EU --random-agent --is-dba --exclude-sysdbs --current-db --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 449, in start
    checkWaf()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/checks.py", line 1427, in checkWaf
    retVal = (Request.queryPage(place=place, value=value, getRatioValue=True, noteResponseTime=False, silent=True, raise404=False, disableTampering=True)[1] or 0) < IPS_WAF_CHECK_RATIO
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1423, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 882, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 384, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None, status)
  File "lib/request/basic.py", line 151, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 37, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/Python27/lib/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/Python27/lib/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/Python27/lib/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/Python27/lib/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/Python27/lib/xml/sax/expatreader.py", line 336, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "lib/parse/handler.py", line 65, in startElement
    if self._dbmsVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-01-05 13:52
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-01-05 13:52 UTC
Labels: duplicate
