### ISSUE TITLE
Unhandled exception (#5f92cec7)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4531] opened 2021-01-07 20:03 UTC
```
Running version: 1.5.1.7#dev
Python version: 2.7.13
Operating system: Windows-10-10.0.19041
Command line: sqlmap.py -u ***************************************************** --level=5 --risk=3 --random-agent --user-agent -v3 --batch --threads=10 --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 557, in start
    check = checkDynParam(place, parameter, value)
  File "lib/controller/checks.py", line 1184, in checkDynParam
    dynResult = Request.queryPage(payload, place, raise404=False)
  File "lib/core/decorators.py", line 78, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1423, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 882, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 384, in processResponse
    parseResponse(page, responseHeaders if kb.processResponseCounter < PARSE_HEADERS_LIMIT else None, status)
  File "lib/request/basic.py", line 151, in parseResponse
    headersParser(headers)
  File "lib/parse/headers.py", line 37, in headersParser
    parseXmlFile(xmlfile, handler)
  File "lib/core/common.py", line 2347, in parseXmlFile
    parse(stream, handler)
  File "/lib/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/lib/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/lib/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/lib/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/lib/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "lib/parse/handler.py", line 65, in startElement
    if self._dbmsVersion.isdigit():
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

**Comment by stamparm** [comment] 2021-01-08 12:24
Duplicate of #4513 (fixed)

**Closed by stamparm** 2021-01-08 12:24 UTC
