### ISSUE TITLE
Unhandled exception (#e678dab6)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1101] opened 2015-01-09 14:34 UTC
```
sqlmap version: 1.0-dev-nongit-20141220
Python version: 2.7.2
Operating system: posix
Command line: sqlmap.py --sqlmap-shell
Technique: None
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 78, in main
    cmdLineOptions.update(cmdLineParser().__dict__)
  File "lib/parse/cmdline.py", line 842, in cmdLineParser
    for arg in shlex.split(command):
  File "system/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "system/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "system/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "system/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by stamparm** [comment] 2015-01-09 14:37
Duplicate of #1032 (patched)

**Closed by stamparm** 2015-01-09 14:37 UTC
