### ISSUE TITLE
Unhandled exception (#471a6194)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3716] opened 2019-05-26 13:37 UTC
```
Running version: 1.3.5.134#dev
Python version: 2.7.16
Operating system: Linux-3.10.65-11682285-armv7l-with-libc
Command line: sqlmap.py -u *********************** --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 180, in main
    start()
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 569, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 498, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1322, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 798, in getPage
    processResponse(page, responseHeaders, code, status)
  File "lib/request/basic.py", line 388, in processResponse
    rawResponse = "%s %s %s\n%s\n%s" % (_http_client.HTTPConnection._http_vsn_str, code or "", status or "", "".join(responseHeaders.headers), page)
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by stamparm** [comment] 2019-05-26 13:52
Duplicate of #3710 (fixed)

**Closed by stamparm** 2019-05-26 13:52 UTC
