### ISSUE TITLE
Unhandled exception (#41c9175d)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4823] opened 2021-09-25 13:50 UTC
```
Running version: 1.5.9.7#dev
Python version: 2.7.18
Operating system: Linux-5.4.0-1045-aws-x86_64-with-Ubuntu-20.04-focal
Command line: /usr/bin/sqlmap -u **************************************************************************************************************************************************** --random-agent --risk 3 --level 5 --tamper=./tripleencode.py --dump-all
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap", line 216, in main
    start()
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/controller/controller.py", line 703, in start
    action()
  File "/share/sqlmap/lib/controller/action.py", line 171, in action
    conf.dbmsHandler.dumpAll()
  File "/share/sqlmap/plugins/generic/entries.py", line 513, in dumpAll
    self.dumpTable()
  File "/share/sqlmap/plugins/generic/entries.py", line 128, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
  File "/share/sqlmap/plugins/generic/databases.py", line 805, in getColumns
    count = inject.getValue(query, union=False, error=False, expected=EXPECTED.INT, charsetType=CHARSET_TYPE.DIGITS)
  File "/share/sqlmap/lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/share/sqlmap/lib/request/inject.py", line 468, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "/share/sqlmap/lib/request/inject.py", line 308, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "/share/sqlmap/lib/request/inject.py", line 154, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "/share/sqlmap/lib/request/inject.py", line 126, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "/share/sqlmap/lib/techniques/blind/inference.py", line 654, in bisection
    val = getChar(index, asciiTbl, not(charsetType is None and conf.charset))
  File "/share/sqlmap/lib/techniques/blind/inference.py", line 369, in getChar
    warnMsg = "unexpected response detected." % threadData.lastCode
TypeError: not all arguments converted during string formatting
```

**Comment by stamparm** [comment] 2021-09-25 23:10
Duplicate of #4824

**Closed by stamparm** 2021-09-25 23:10 UTC
