### ISSUE TITLE
Unhandled exception (#a2126cd1)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2027] opened 2016-07-16 13:50 UTC
```
sqlmap version: 1.0.7.21#dev
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -u ************************************************ --dump -D ************** -T tblUsers
Technique: None
Back-end DBMS: Microsoft SQL Server (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 124, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 108, in dumpTable
    self.getColumns(onlyColNames=True, dumpMode=True)
  File "plugins/generic/databases.py", line 555, in getColumns
    values = unionUse(expression)
  File "lib/techniques/union/use.py", line 211, in unionUse
    output = _oneShotUnionUse(_, False)
  File "lib/techniques/union/use.py", line 108, in _oneShotUnionUse
    root = xml.etree.ElementTree.fromstring("<root>%s</root>" % output)
  File "Python27/lib/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "Python27/lib/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "Python27/lib/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 16
```

**Comment by stamparm** [comment] 2016-07-16 13:51
Duplicate of #2026 (fixed this moment)

**Closed by stamparm** 2016-07-16 13:51 UTC
