### ISSUE TITLE
Unhandled exception (#db02a772)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3335] opened 2018-10-29 18:31 UTC
```
Running version: 1.2.10.12#dev
Python version: 2.7.15
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --url=******************** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=MYSQL --random-agent --is-dba --exclude-sysdbs --current-db --answers=**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 29, in <module>
    from plugins.dbms.mysql import MySQLMap
ImportError: No module named mysql
```

**Comment by stamparm** [comment] 2018-10-30 09:21
Duplicate of #3329

**Closed by stamparm** 2018-10-30 09:21 UTC
