### ISSUE TITLE
Unhandled exception (#a3f9fa89)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2886] opened 2018-01-17 01:27 UTC
```
sqlmap version: 1.2.1.11#dev
Python version: 2.7.14
Operating system: nt
Command line: sqlmap.py -u *************************************************** --tamper=space2comment --level 5 --risk 3 --dbs
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    start()
  File "lib/controller/controller.py", line 547, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 615, in checkSqlInjection
    trueResult = Request.queryPage(reqPayload, place, timeBasedCompare=True, raise404=False)
  File "lib/request/connect.py", line 1233, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 432, in getPage
    req = urllib2.Request(url, post, headers)
  File "Python27/lib/urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "Python27/lib/urllib.py", line 1071, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by stamparm** [comment] 2018-02-07 15:11
Duplicate of #2886 (should be fixed)

**Closed** 2018-04-24 17:46 UTC
