### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ChineseOldboy** [sqlmapproject/sqlmap#5796] opened 2024-10-31 04:26 UTC
C:\Users\Administrator\Desktop\bug\bug\sqlmap>py sqlmap.py -u "https://colegioanglomorumbi.com.br/'%20OR%20'1'='1'%20--"
        ___
       __H__
 ___ ___[']_____ ___ ___  {1.7.7#stable}
|_ -| . [.]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 12:25:34 /2024-10-31/

[12:25:34] [WARNING] you've provided target URL without any GET parameters (e.g. 'http://www.site.com/article.php?id=1') and without providing any POST parameters through option '--data'

[12:25:34] [CRITICAL] unhandled exception occurred in sqlmap/1.7.7#stable. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.7.7#stable
Python version: 3.13.0
Operating system: Windows-10-10.0.19045-SP0
Command line: sqlmap.py -u ********************************************************
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "lib/core/common.py", line 1167, in readInput
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/core/common.py", line 1187, in readInput
    raise SqlmapUserQuitException
lib.core.exception.SqlmapUserQuitException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
    ~~~~~^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 434, in start
    setupTargetEnv()
    ~~~~~~~~~~~~~~^^
  File "lib/core/target.py", line 767, in setupTargetEnv
    _setRequestParams()
    ~~~~~~~~~~~~~~~~~^^
  File "lib/core/target.py", line 258, in _setRequestParams
    choice = readInput(message, default='Y').upper()
             ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/common.py", line 1190, in readInput
    logging._releaseLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_releaseLock'

[12:25:34] [WARNING] your sqlmap version is outdated

[*] ending @ 12:25:34 /2024-10-31/


C:\Users\Administrator\Desktop\bug\bug\sqlmap>py sqlmap.py -u "https://colegioanglomorumbi.com.br/'"
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.7.7#stable}
|_ -| . [']     | .'| . |
|___|_  [,]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 12:25:41 /2024-10-31/

[12:25:41] [WARNING] you've provided target URL without any GET parameters (e.g. 'http://www.site.com/article.php?id=1') and without providing any POST parameters through option '--data'


[12:25:41] [CRITICAL] unhandled exception occurred in sqlmap/1.7.7#stable. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.7.7#stable
Python version: 3.13.0
Operating system: Windows-10-10.0.19045-SP0
Command line: sqlmap.py -u ************************************
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "lib/core/common.py", line 1167, in readInput
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/core/common.py", line 1187, in readInput
    raise SqlmapUserQuitException
lib.core.exception.SqlmapUserQuitException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
    ~~~~~^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 434, in start
    setupTargetEnv()
    ~~~~~~~~~~~~~~^^
  File "lib/core/target.py", line 767, in setupTargetEnv
    _setRequestParams()
    ~~~~~~~~~~~~~~~~~^^
  File "lib/core/target.py", line 258, in _setRequestParams
    choice = readInput(message, default='Y').upper()
             ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/common.py", line 1190, in readInput
    logging._releaseLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_releaseLock'

[12:25:41] [WARNING] your sqlmap version is outdated

[*] ending @ 12:25:41 /2024-10-31/

**Comment by stamparm** [comment] 2024-10-31 16:24
so, you are using `1.7.7#stable` (Jul 6, 2023), while the latest revision is `1.8.10.2#dev`

even you got a clear warning message for that `[WARNING] your sqlmap version is outdated`

p.s. duplicate of #5731

**Closed as completed by stamparm** 2024-10-31 16:24 UTC
Labels: duplicate
