### ISSUE TITLE
Unhandled exception (#9a7ab615)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1103] opened 2015-01-10 08:12 UTC
```
sqlmap version: 1.0-dev-nongit-20141128
Python version: 2.7.8
Operating system: nt
Command line: sqlmap.py -r apm.txt --os-shell
Technique: ERROR
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 596, in start
    action()
  File "lib/controller/action.py", line 160, in action
    conf.dbmsHandler.osShell()
  File "plugins/generic/takeover.py", line 80, in osShell
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 183, in initEnv
    self.webInit()
  File "lib/takeover/web.py", line 228, in webInit
    self._webFileInject(stagerContent, stagerName, directory)
  File "lib/takeover/web.py", line 144, in _webFileInject
    query += getSQLSnippet(DBMS.MYSQL, "write_file_limit", OUTFILE=outFile, HEXSTRING=hexencode(uplQuery))
  File "lib/core/common.py", line 1803, in getSQLSnippet
    retVal = retVal.replace(r"%%%s%%" % var, val)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by stamparm** [comment] 2015-01-11 13:34
Duplicate of #1028 (patched)

**Closed by stamparm** 2015-01-11 13:34 UTC
Labels: duplicate
