### ISSUE TITLE
Unhandled exception (#ed95a7f0)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3632] opened 2019-05-06 05:02 UTC
```
Running version: 1.3.5.26#dev
Python version: 2.7.16
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --output-dir=output --url=********** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=mysql,mssql --technique=EUBSTQ --random-agent --is-dba --exclude-sysdbs --current-db --answers=*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 179, in main
    start()
  File "lib/core/decorators.py", line 54, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 570, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 506, in checkSqlInjection
    Request.queryPage(genCmpPayload(), place, raise404=False)
  File "lib/core/decorators.py", line 54, in _
    result = f(*args, **kwargs)
  File "lib/request/connect.py", line 1312, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 622, in getPage
    responseMsg += "[#%d] (%s %s):\r\n" % (threadData.lastRequestUID, code, status)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 17: ordinal not in range(128)
```

**Comment by stamparm** [comment] 2019-05-06 09:48
Duplicate of #3630

**Closed by stamparm** 2019-05-06 09:48 UTC
