### ISSUE TITLE
Unhandled exception (#979213ab)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3340] opened 2018-10-29 19:05 UTC
```
Running version: 1.2.10.12#dev
Python version: 2.7.15
Operating system: Windows-2012ServerR2-6.3.9600
Command line: sqlmap.py --url=********** --crawl=1 --threads=10 --tamper=space2comment.py --retries=0 --timeout=5 --dbms=MYSQL --random-agent --is-dba --exclude-sysdbs --current-db --answers=**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 157, in main
    from lib.controller.controller import start
  File "lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "lib/controller/handler.py", line 27, in <module>
  File "plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
  File "plugins/dbms/mssqlserver/enumeration.py", line 32, in <module>
  File "plugins/generic/enumeration.py", line 20, in <module>
  File "plugins/generic/entries.py", line 46, in <module>
  File "lib/utils/hash.py", line 89, in <module>
NameError: Can't find file for module __init__.py
(filename C:\Users\*************\.sqlmap\thirdparty\pydes\__init__.py)
```

**Comment by stamparm** [comment] 2018-10-30 09:29
Duplicate of #3329

**Closed by stamparm** 2018-10-30 09:29 UTC
