### ISSUE TITLE
Unhandled exception (#7aa6a774)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3983] opened 2019-10-24 03:16 UTC
```
Running version: 1.3.8.12#dev
Python version: 3.7.4
Operating system: Windows-10-10.0.17134-SP0
Command line: sqlmap.py --update
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "lib/core/update.py", line 110, in update
    process = subprocess.Popen("git checkout . && git pull %s HEAD" % GIT_REPOSITORY, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=paths.SQLMAP_ROOT_PATH)
  File "lib/core/common.py", line 4914, in pollProcess
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2664, in init
    _setHTTPExtraHeaders()
  File "lib/core/update.py", line 117, in update
    finally:
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by stamparm** [comment] 2019-10-24 07:38
Duplicate of #3898 (patched)

**Closed by stamparm** 2019-10-24 07:38 UTC
