### ISSUE TITLE
Unhandled exception (#36ace3af)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#3344] opened 2018-10-29 19:42 UTC
```
sqlmap version: 1.0.12.10#dev
Python version: 2.7.12
Operating system: nt
Command line: sqlmap.py -u ************************************************************************************** -D *********** --columns
Technique: UNION
Back-end DBMS: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 151, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 112, in action
    conf.dumper.dbTableColumns(conf.dbmsHandler.getColumns(), CONTENT_TYPE.COLUMNS)
  File "plugins/generic/databases.py", line 561, in getColumns
    values = inject.getValue(query, blind=False, time=False)
  File "lib/request/inject.py", line 384, in getValue
    value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)
  File "lib/request/inject.py", line 329, in _goUnion
    output = unionUse(expression, unpack=unpack, dump=dump)
  File "lib/techniques/union/use.py", line 389, in unionUse
    runThreads(numThreads, unionThread)
  File "lib/core/threads.py", line 211, in runThreads
    except thread.error:
UnboundLocalError: local variable 'thread' referenced before assignment
```

**Comment by stamparm** [comment] 2018-10-30 09:40
Duplicate of #2356 (fixed LONG ago)

**Closed by stamparm** 2018-10-30 09:40 UTC
