### ISSUE TITLE
Unhandled exception (#64a4d560)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#2928] opened 2018-02-12 07:47 UTC
```
sqlmap version: 1.2.2.9#dev
Python version: 2.7.13
Operating system: Windows-10-10.0.16299
Command line: sqlmap.py -u **************************************************** --dbms mysql --proxy ************************ --tamper=space2hash.py,modsecurityversioned.py
Technique: None
Back-end DBMS: MySQL (identified)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 141, in main
    init()
  File "lib/core/option.py", line 2636, in init
    _setTamperingFunctions()
  File "lib/core/option.py", line 965, in _setTamperingFunctions
    function()
  File "tamper/modsecurityversioned.py", line 16, in dependencies
    singleTimeWarnMessage("tamper script '%s' is only meant to be run against %s" % (os.path.basename(__file__).split(".")[0], DBMS.MYSQL))
NameError: global name 'os' is not defined
```

**Comment by stamparm** [comment] 2018-02-12 09:17
Duplicate of #2923 (fixed)

**Closed by stamparm** 2018-02-12 09:17 UTC
