### ISSUE TITLE
--search & --dump issue, and Automatic Tamper

### ISSUE THREAD

**Issue by franx47** [sqlmapproject/sqlmap#1234] opened 2015-04-30 00:45 UTC
Hi, 

There are 2 things I would like to report and wish to be fixed:

#1 When trying to search for any table or column name which contains any string, using --search, the result should only retrieve the table or column name, but SQLMap continue the process to dump all data. 

eg: 

./sqlmap.py -u "sample.com/product.php?id=10" -T orders --search 

Suppose, the database contains table name "orders". When SQLMap found the table name which match with the search string, it should only retrieve the table name, not continue to dump the data. The same case apply to column search.

Imagine, how if the table (with 50 columns/fields, 10 of the fields are TEXT/BLOB variable) and contains 1,000,000 records and SQLMap dump them all at once??

If --search has to continue dump the data, it will be better if it only dumps the TOP 2 rows or not dump at all or there's an additional command along with --search, eg: --no-dump. 

I hope this can be fixed. 

#2 Tamper is very useful on injection process or retrieving data.

I think it will be better, if SQLMap can automate the process of applying the tampers. Since, sometimes certain tamper is useful for certain attack type and certain injection method. 

eg: 

Attack type: T,B (Time, Boolean)

./sqlmap.py -u "sample.com/product.php?id=10" --hex --tamper "securesphere.py" -T orders --dump

Using this tamper "securesphere.py", data from table "orders" could be retrieved successfully. 

But.. 

Using tamper "space2comment.py"

./sqlmap.py -u "sample.com/product.php?id=10" --hex --tamper "space2comment.py" -T orders --dump

Data from table "orders" could not be retrieved.

Since SQLMap has many tamper scripts, we have to apply the tamper scripts one by one, to find which is good for data retrieval.

Thats why, I think it's better if the tamper scripts could be set automatically, without change the tamper script manually. This will reduce time and more effective way.

Maybe adding a command like this: 

./sqlmap.py -u "sample.com/product.php?id=10" --hex --auto-tamper -T orders --dump

"--auto-tamper" command will set the tamper scripts automatically one by one from the "tamper" directory, until it shows the correct data retrieval.

I hope this can be implemented. 

Thank you very much. 

Regards,

**Comment by stamparm** [comment] 2015-04-30 22:25
1) You are being asked, so its not true that sqlmap does it (without user's consent)

![capture](https://cloud.githubusercontent.com/assets/921555/7423729/874bb450-ef98-11e4-94bd-c6806d37236d.PNG)

2) Duplicate of #1236

**Closed by stamparm** 2015-04-30 22:25 UTC

**Comment by franx47** [comment] 2015-05-01 20:19
Hi, 

Thanks for the reply. 

#1. Sorry, I forgot that I use --batch. You are right. 

#2. About the Auto Tamper. Well, I'm the first one who propose this Auto Tamper, check the posting date or issue number. So, this isn't duplicate from the other issues, maybe somebody else asked the same after my post. 

I have read your explanation on issue https://github.com/sqlmapproject/sqlmap/issues/1236.

I mean, we use auto tamper to be set automatically after finding injection on certain point, with certain method. 

eg: 

Suppose we got injection on this, with BT (Boolean, Time) techniques.

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2comment.py" --dbs

It succesfully retrieves the DB list. 

DB1 [current DB]
DB2

Next, we try to list the table and its columns on DB1. 

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2comment.py" -D DB1 --tables --columns

table1 [id,username]
table2 [pid,desc]

Last, we try to dump certain table (table1). 

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2comment.py" -D DB1 -T table1 --dump

Sometimes, it gives result or not at all. 

When it gives no result, it's really clueless at this point. Something has to be changed and tuned, and that is the tamper.

I try to change the tamper from space2comment.py to other tamper, say, "securepshere.py", and it successfully gives result. But, I'm not saying that securesphere.py always give result, it is ofcourse depends on the injection type. I still have to set the tamper manually one by one from the 42 tamper scripts available, until it gives true result.

Thats why, I'm thinking, why not just set the tamper automatically from the tamper list, other than set it manually one by one to deal on data retrieval.

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2plus.py" -D DB1 -T table1 --dump

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "securesphere.py" -D DB1 -T table1 --dump

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "between.py" -D DB1 -T table1 --dump

(Using multiple tampers at once also not a good solution)

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2comment.py,between.py,securesphere.py,base64encode.py" -D DB1 -T table1 --dump

etc...

The use case maybe something like this. 

./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --auto-tamper -D DB1 -T table1 --dump

[Set tamper space2plus.py]
./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "space2plus.py" -D DB1 -T table1 --dump
.....
[No result]

[Set tamper between.py]
./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "between.py" -D DB1 -T table1 --dump
.....
[Successfully retrieve data from table1 column id,username]

Do you want to try with other tamper [Y/N]? Y

[Set tamper charencode.py]
./sqlmap.py -u "sample.com/products.php?id=10" --hex --level 2 --risk 2 --tamper "charencode.py" -D DB1 -T table1 --dump
.....
[No result]

From the examples above, the tamper "between.py" is the suitable tamper exactly we need to deal with this injection.

So, it is somehow like looping the tamper list, after the injection point has been found and the session is set, not on injection process.

Anyway, isn't the tamper only change and mask the payload (?)


Thank you for your time.


Regards,

**Comment by stamparm** [comment] 2015-05-04 09:00
To be frank to other users, this idea came couple of years ago. 3-4 users proposed it (mailing list and privately) but nobody gave good solution to this problem.

You gave an good idea, but it still has flaws.

Biggest one is that majority of users would use that switch BEFORE the injection is found at the first place. Also, that kind of switch would give false hope to users that are eager to find ANYTHING.

As said, using this kind of mechanism in the detection phase would make just more problems than benefits (40 times more requests, 40 times slower sqlmap run).

Comments?

**Comment by seyedhojjathosseini** [comment] 2019-10-30 06:36
> 
> 
> Hi,
> 
> There are 2 things I would like to report and wish to be fixed:
> #1 When trying to search for any table or column name which contains any string, using --search, the result should only retrieve the table or column name, but SQLMap continue the process to dump all data.
> 
> eg:
> 
> ./sqlmap.py -u "sample.com/product.php?id=10" -T orders --search
> 
> Suppose, the database contains table name "orders". When SQLMap found the table name which match with the search string, it should only retrieve the table name, not continue to dump the data. The same case apply to column search.
> 
> Imagine, how if the table (with 50 columns/fields, 10 of the fields are TEXT/BLOB variable) and contains 1,000,000 records and SQLMap dump them all at once??
> 
> If --search has to continue dump the data, it will be better if it only dumps the TOP 2 rows or not dump at all or there's an additional command along with --search, eg: --no-dump.
> 
> I hope this can be fixed.
> #2 Tamper is very useful on injection process or retrieving data.
> 
> I think it will be better, if SQLMap can automate the process of applying the tampers. Since, sometimes certain tamper is useful for certain attack type and certain injection method.
> 
> eg:
> 
> Attack type: T,B (Time, Boolean)
> 
> ./sqlmap.py -u "sample.com/product.php?id=10" --hex --tamper "securesphere.py" -T orders --dump
> 
> Using this tamper "securesphere.py", data from table "orders" could be retrieved successfully.
> 
> But..
> 
> Using tamper "space2comment.py"
> 
> ./sqlmap.py -u "sample.com/product.php?id=10" --hex --tamper "space2comment.py" -T orders --dump
> 
> Data from table "orders" could not be retrieved.
> 
> Since SQLMap has many tamper scripts, we have to apply the tamper scripts one by one, to find which is good for data retrieval.
> 
> Thats why, I think it's better if the tamper scripts could be set automatically, without change the tamper script manually. This will reduce time and more effective way.
> 
> Maybe adding a command like this:
> 
> ./sqlmap.py -u "sample.com/product.php?id=10" --hex --auto-tamper -T orders --dump
> 
> "--auto-tamper" command will set the tamper scripts automatically one by one from the "tamper" directory, until it shows the correct data retrieval.
> 
> I hope this can be implemented.
> 
> Thank you very much.
> 
> Regards,

https://github.com/seyedhojjathosseini/sqlmap-AutoTamper

**Comment by stamparm** [comment] 2019-10-31 22:03
@seyedhojjathosseini 
![screenshot](https://user-images.githubusercontent.com/921555/67989262-8b786b80-fc32-11e9-8987-bf5a102fa317.png)
