### ISSUE TITLE
Unhandled exception (#f5ceba5c)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1091] opened 2015-01-04 16:22 UTC
```
sqlmap version: 1.0-dev
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u **************************************************** --os-cmd=id
Technique: UNION
Back-end DBMS: PostgreSQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 100, in main
    start()
  File "lib/controller/controller.py", line 594, in start
    action()
  File "lib/controller/action.py", line 157, in action
    conf.dbmsHandler.osCmd()
  File "plugins/generic/takeover.py", line 57, in osCmd
    self.initEnv(web=web)
  File "lib/takeover/abstraction.py", line 200, in initEnv
    success = self.udfInjectSys()
  File "lib/takeover/udf.py", line 184, in udfInjectSys
    self.udfSetLocalPaths()
  File "plugins/dbms/postgresql/takeover.py", line 64, in udfSetLocalPaths
    self.udfLocalFile = os.path.join(self.udfLocalFile, "postgresql", "linux", "%d" % Backend.getArch(), majorVer, "lib_postgresqludf_sys.so")
NameError: global name 'os' is not defined
```

**Comment by stamparm** [comment] 2015-01-04 23:30
Duplicate of #895 (patched)

**Closed by stamparm** 2015-01-04 23:30 UTC
