### ISSUE TITLE
Unhandled exception (#de960610)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4658] opened 2021-04-27 16:20 UTC
```
Running version: 1.3.11.115#dev
Python version: 3.9.2
Operating system: macOS-11.2.3-x86_64-i386-64bit
Command line: sqlmap.py -u ****************************************************** --batch
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 166, in main
    init()
  File "lib/core/option.py", line 2687, in init
    loadBoundaries()
  File "lib/parse/payloads.py", line 89, in loadBoundaries
    parseXmlNode(root)
  File "lib/parse/payloads.py", line 44, in parseXmlNode
    for element in node.getiterator("boundary"):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

**Comment by stamparm** [comment] 2021-04-28 06:50
Duplicate of #4126 (fixed)

**Closed by stamparm** 2021-04-28 06:50 UTC
